Repository AmericanMedicalAssociation/ama-style-guide-2, pull requests merged in 2018-12, with the labels that each got.

#565 Feature/freida theme
  styleguide/source/assets/js/form-items.js
  styleguide/source/assets/js/tabs.js
  styleguide/source/assets/scss/05-pages/_frieda.scss
Labels: question, ready for review

#554 EWL-6637: Related news article font is bold.
  styleguide/source/assets/scss/02-molecules/_article-stub.scss
Labels: ok to merge

#563 EWL-6644: Address safari button styling.
  styleguide/source/assets/scss/02-molecules/_subscribe-promo.scss
Labels: ok to merge, ready for review

#488 EWL-6479 related block search
  styleguide/source/assets/scss/02-molecules/_promo.scss
Labels: Needs second review, has D8 dependency, ready for review

#552 EWL-6623 IE11 specific fix to prevent hub card images from blowing out of porp…
  styleguide/source/assets/scss/02-molecules/hub/_hub-card.scss
  styleguide/source/assets/scss/02-molecules/hub/_hub-hero.scss
Labels: Needs second review, priority, ready for review

#535 [EWL-6262] Subcat Stacking Bug
  styleguide/source/_patterns/05-pages/category.json
  styleguide/source/assets/js/subcategory.js
  styleguide/source/assets/scss/03-organisms/_subcategory-exploration-as-with-images.scss
Labels: Needs second review, priority, ready for review
