Repository AmericanMedicalAssociation/ama-style-guide-2, pull requests merged in 2018-11, with the labels that each got.

#489 [EWL-6491] Homepage JAMA Component Padding and Border Color
  styleguide/source/assets/scss/02-molecules/_jama.scss
Labels: priority, ready for review

#492 EWL-6365 Add hover style to org links
  styleguide/source/assets/scss/03-organisms/_org-nav.scss
Labels: priority

#493 EWL-6506: Fix margin on Category Nav li, a
  styleguide/source/assets/scss/03-organisms/_category-nav.scss
Labels: in review, priority, ready for review

#494 Footer Updates
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-instagram-white.twig
  styleguide/source/assets/icons/svg/icon-instagram-white.svg
  styleguide/source/assets/scss/03-organisms/_footer.scss
Labels: in review, priority, ready for review

#495 EWL-6510: Target ama__layout--split on homepage, override previously …
  styleguide/source/assets/scss/05-pages/_homepage.scss
Labels: in review, priority, ready for review

#498 [EWL-6511/EWL-6523] Homepage Main Content Subscribe Promo
  styleguide/source/assets/scss/02-molecules/_subscribe-promo.scss
Labels: ok to merge, priority

#499 EWL-6507 ribbon desktop
  styleguide/source/assets/scss/03-organisms/_category-navigation-menu.scss
  styleguide/source/assets/scss/03-organisms/_main-navigation.scss
Labels: has D8 dependency, ok to merge, priority

#500 [EWL-6519] Homepage Tablet - Upcoming Events
  styleguide/source/assets/scss/02-molecules/_upcoming-event.scss
Labels: in review, priority

#504 Updates SG2 to v2.26.6
  styleguide/package-lock.json
  styleguide/package.json
Labels: ready for review

#502 EWL-6500 search mobile
  styleguide/source/assets/scss/02-molecules/_search-header.scss
Labels: ok to merge, priority

#505 EWL-6513: Homepage - mobile view all products
  styleguide/source/assets/scss/02-molecules/_product.scss
Labels: ok to merge

#506 BUGFIX: Fix search placeholder in Safari
  styleguide/source/assets/scss/02-molecules/_global-search.scss
  styleguide/source/assets/scss/02-molecules/_search-header.scss
Labels: ok to merge, priority

#490 EWL-6460 Fixes homepage subscribe input not showing in IE11
  styleguide/source/assets/scss/02-molecules/_subscribe-promo.scss
Labels: ok to merge

#507 EWL-6532 Fix menu and ribbon styling
  styleguide/source/assets/scss/01-atoms/_menu-icon.scss
  styleguide/source/assets/scss/03-organisms/_category-navigation-menu.scss
  styleguide/source/assets/scss/03-organisms/_product-nav.scss
Labels: has D8 dependency, in review, priority, ready for review

#496 EWL-6527 homepage membership block spacing and margins
  styleguide/source/assets/scss/02-molecules/_hero-story.scss
  styleguide/source/assets/scss/02-molecules/_member-feature-rail.scss
  styleguide/source/assets/scss/03-organisms/_main-navigation.scss
  styleguide/source/assets/scss/03-organisms/_member-feature.scss
Labels: in review, priority, ready for review

#509 EWL-6537 Fix people listing cards last row getting split
  styleguide/source/assets/scss/02-molecules/_people-listing.scss
  styleguide/source/assets/scss/05-pages/_people-listing.scss
Labels: in review, priority, ready for review

#503 [Release] Style Guide v2.27.0
  styleguide/package-lock.json
  styleguide/package.json
Labels: ready for review

#510 EWL6546 Fix padding of category page mobile between hero article
  styleguide/source/assets/js/main-navigation.js
  styleguide/source/assets/scss/05-pages/_category.scss
Labels: ok to merge, priority

#512 EWL-6544: Resource page - Eliminate divider lines in between items on Download tab
  styleguide/source/assets/scss/02-molecules/_tool.scss
Labels: in review, ready for review

#513 EWL-6563 Hub hero should match the sizing on D7
  styleguide/source/assets/scss/02-molecules/hub/_hub-card.scss
Labels: ok to merge, ready for review

#514 EWL-6538: News Article - numbered list options not displaying on frontend
  styleguide/source/_patterns/05-pages/news/news.json
  styleguide/source/_patterns/05-pages/news/news.twig
  styleguide/source/assets/scss/05-pages/_news.scss
Labels: has D8 dependency, ok to merge

#511 EWL-6481 Fixes buttons overlapping names when there are no photos
  styleguide/source/assets/scss/02-molecules/_people-listing.scss
Labels: ok to merge, priority

#523 EWL-6568 Fix images getting stretched on hub cards
  styleguide/source/assets/scss/02-molecules/hub/_hub-card.scss
Labels: P1, in review, ready for review

#519 EWL-6484 Fix magnifying glass and search input to match zeplin
  styleguide/source/assets/scss/01-atoms/_search-field.scss
Labels: P1, ok to merge, ready for review

#517 EWL-6567: Update select pattern and add jump menu JS.
  styleguide/source/_patterns/01-atoms/forms/select-menu.twig
  styleguide/source/assets/js/jump-menu.js
Labels: P2, ok to merge

#520 EWL-6562 mobile search drawer
  styleguide/source/_patterns/02-molecules/global-search.twig
  styleguide/source/assets/js/main-navigation.js
  styleguide/source/assets/scss/02-molecules/_global-search.scss
Labels: P2, has D8 dependency, ok to merge

#524 EWL-6566 adds margin on top of resource nav tabs
  styleguide/source/assets/scss/03-organisms/_resource-tabs.scss
Labels: P2, ok to merge

#526 EWL:6569: Display 5 Articles on homepage
  styleguide/source/assets/scss/04-templates/_split.scss
Labels: P2, ok to merge

#527 Fix email subscription button getting cut off in tablet view
  styleguide/source/assets/scss/02-molecules/_subscribe-promo.scss
Labels: P1, in review, ok to merge

#487 EWL-6447 Themes 50/50 video hub card
  styleguide/source/assets/scss/02-molecules/hub/_hub-card.scss
  styleguide/source/assets/scss/02-molecules/hub/_hub-hero.scss
Labels: P2, has D8 dependency, ready for review

#530 EWL-6148: Add special formatting for related article news teasers.
  styleguide/source/assets/scss/02-molecules/_article-stub.scss
Labels: Needs second review, P2, has D8 dependency, ready for review

#532 [Hotfix] Resource page split layout
  styleguide/source/assets/scss/04-templates/_split.scss
Labels: P2, ok to merge, priority

#529 EWL-6096: hover purple color
  styleguide/source/assets/scss/00-base/_colors.scss
  styleguide/source/assets/scss/01-atoms/_links.scss
  styleguide/source/assets/scss/05-pages/_resource.scss
Labels: P2, ok to merge

#533 P2 integration
  styleguide/source/_patterns/01-atoms/forms/select-menu.twig
  styleguide/source/_patterns/02-molecules/global-search.twig
  styleguide/source/_patterns/03-organisms/tools.json
  styleguide/source/_patterns/05-pages/category.json
  styleguide/source/_patterns/05-pages/event.json
  styleguide/source/_patterns/05-pages/news/news-as-gated.json
  styleguide/source/_patterns/05-pages/news/news-with-jama-examples.json
  styleguide/source/_patterns/05-pages/news/news.json
  styleguide/source/_patterns/05-pages/people-bio.json
  styleguide/source/_patterns/05-pages/press-release.json
  styleguide/source/_patterns/05-pages/topic.json
  styleguide/source/assets/js/jump-menu.js
  styleguide/source/assets/js/main-navigation.js
  styleguide/source/assets/scss/00-base/_colors.scss
  styleguide/source/assets/scss/01-atoms/_links.scss
  styleguide/source/assets/scss/02-molecules/_article-stub.scss
  styleguide/source/assets/scss/02-molecules/_global-search.scss
  styleguide/source/assets/scss/02-molecules/hub/_hub-card.scss
  styleguide/source/assets/scss/02-molecules/hub/_hub-hero.scss
  styleguide/source/assets/scss/03-organisms/_resource-tabs.scss
  styleguide/source/assets/scss/03-organisms/_tools.scss
  styleguide/source/assets/scss/04-templates/_split.scss
  styleguide/source/assets/scss/05-pages/_resource.scss
Labels: ready for review

#538 Release 2.27.2
  styleguide/package-lock.json
  styleguide/package.json
Labels: ready for review

#537 [EWL-6154] Resource page downloads tab updates
  styleguide/source/_patterns/02-molecules/download-link.json
  styleguide/source/_patterns/02-molecules/download-link.twig
  styleguide/source/_patterns/03-organisms/resource-tabs.json
  styleguide/source/_patterns/03-organisms/resource-tabs.twig
  styleguide/source/_patterns/05-pages/resource.json
  styleguide/source/assets/scss/02-molecules/_download-link.scss
  styleguide/source/assets/scss/03-organisms/_resource-tabs.scss
Labels: ok to merge

#543 [EWL-6595] Product Exploration IE Fix
  styleguide/source/assets/scss/02-molecules/_product.scss
Labels: in review, ok to merge, priority

#541 [EWL-6594] Event Detail Masthead Regression
  styleguide/source/assets/scss/03-organisms/_masthead.scss
Labels: in review, ok to merge, priority

#518 EWL-6549 Fix category navigation padding and margins
  styleguide/source/_patterns/03-organisms/subcategory-exploration.twig
  styleguide/source/assets/js/subcategory-exploration.js
  styleguide/source/assets/scss/03-organisms/_subcategory-exploration.scss
Labels: Needs second review, P1, priority, ready for review

#544 Add border-top to footer Product menu
  styleguide/source/assets/scss/03-organisms/_footer.scss
Labels: ok to merge, priority, quick fix!

#545 EWL-6538: Enable OL on resource pages.
  styleguide/source/assets/scss/05-pages/_resource.scss
Labels: ok to merge, priority

#546 EWL-6538: Fix bullets on News Articles
  styleguide/source/assets/scss/05-pages/_news.scss
Labels: ok to merge, priority

#540 EWL-6566 Fixes height of resource tabs flowing into footer
  styleguide/source/assets/scss/03-organisms/_resource-tabs.scss
Labels: Needs second review, P2, in review, ready for review

#539 EWL-6582 Fixes hover and active state for sub cat search box
  styleguide/source/assets/scss/01-atoms/_search-field.scss
Labels: P2, ok to merge, ready for review

#547 [Release] Style Guide v2.27.3
  styleguide/package-lock.json
  styleguide/package.json
Labels: ready for review

#549 EWL-6566 removes height of 100% to resource tabs
  styleguide/source/assets/scss/03-organisms/_resource-tabs.scss
Labels: Needs second review, priority

#550 Hot Fix: removes padding that causes differences in grid
  styleguide/source/assets/scss/00-base/_grid.scss
Labels: Needs second review, in review, priority
