Repository AmericanMedicalAssociation/ama-style-guide-2, pull requests merged in 2018-07, with the labels that each got.

#312 update backstop screenshots
  styleguide/backstop.json
  styleguide/backstop_data/bitmaps_reference/backstop_default_category_page_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_category_page_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_category_page_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_category_page_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_category_page_0_document_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_resource_tabs_0_ama__resource-tabs_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_resource_tabs_0_ama__resource-tabs_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_resource_tabs_0_ama__resource-tabs_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_resource_tabs_0_ama__resource-tabs_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_resource_tabs_0_ama__resource-tabs_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_subcategory_featured_content_0_ama__subcategory-featured-content_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_visual_subcategory_exploration_with_images_0_ama__subcategory-exploration-with-images_1_bp-small.png
Labels: ok to merge, priority

#313 EWL-5411 Add people listing page stub
  styleguide/backstop.json
  styleguide/backstop_data/bitmaps_reference/backstop_default_people_listing_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_people_listing_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_people_listing_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_people_listing_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_people_listing_0_document_4_bp-xl.png
  styleguide/source/_patterns/05-pages/people-listing.json
  styleguide/source/_patterns/05-pages/people-listing.md
  styleguide/source/_patterns/05-pages/people-listing.twig
  styleguide/source/assets/scss/05-pages/_people-listing.scss
Labels: in review, priority

#319 Adds page title caps
  styleguide/backstop.json
  styleguide/backstop_data/bitmaps_reference/backstop_default_atoms_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_atoms_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_atoms_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_atoms_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_atoms_0_document_4_bp-xl.png
  styleguide/source/_patterns/00-base/style-guide-welcome.twig
  styleguide/source/_patterns/01-atoms/page-title.twig
  styleguide/source/_patterns/01-atoms/page-title/page-title.json
  styleguide/source/_patterns/01-atoms/page-title/page-title.md
  styleguide/source/_patterns/01-atoms/page-title/page-title.twig
  styleguide/source/_patterns/01-atoms/page-title/page-title~as-all-caps.json
  styleguide/source/_patterns/05-pages/error.twig
  styleguide/source/_patterns/05-pages/topic.twig
  styleguide/source/assets/scss/01-atoms/_page-title.scss
Labels: in review

#320 EWL-5289 Add two column right full width
  styleguide/backstop.json
  styleguide/backstop_data/bitmaps_reference/backstop_default_templates-two-column-right-full-width_0__0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_templates-two-column-right-full-width_0__1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_templates-two-column-right-full-width_0__2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_templates-two-column-right-full-width_0__3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_templates-two-column-right-full-width_0__4_bp-xl.png
  styleguide/source/_patterns/04-templates/two-column-right-full-width.twig
  styleguide/source/assets/scss/04-templates/_two-column-right--full-width.scss
Labels: in review

#311 EWL-5303 - Fix overflow issue in IE 11 and view all not working correctly
  styleguide/backstop_data/bitmaps_reference/backstop_default_category_page_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_category_page_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_category_page_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_category_page_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_category_page_0_document_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_templates-two-column-right-full-width_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_templates-two-column-right-full-width_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_templates-two-column-right-full-width_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_templates-two-column-right-full-width_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_templates-two-column-right-full-width_0_document_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_visual_subcategory_exploration_with_images_0_ama__subcategory-exploration-with-images_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_visual_subcategory_exploration_with_images_0_ama__subcategory-exploration-with-images_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_visual_subcategory_exploration_with_images_0_ama__subcategory-exploration-with-images_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_visual_subcategory_exploration_with_images_0_ama__subcategory-exploration-with-images_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_visual_subcategory_exploration_with_images_0_ama__subcategory-exploration-with-images_4_bp-xl.png
  styleguide/source/assets/js/subcategory.js
  styleguide/source/assets/scss/03-organisms/_subcategory-exploration-as-with-images.scss
Labels: in review, priority

#325 EWL-5392 create bio page
  styleguide/backstop.json
  styleguide/backstop_data/bitmaps_reference/backstop_default_bio_image_with_body_0_ama__bio-image-with-body_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_bio_image_with_body_0_ama__bio-image-with-body_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_bio_image_with_body_0_ama__bio-image-with-body_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_bio_image_with_body_0_ama__bio-image-with-body_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_bio_image_with_body_0_ama__bio-image-with-body_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_bio_section_0_ama__bio-section_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_bio_section_0_ama__bio-section_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_bio_section_0_ama__bio-section_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_bio_section_0_ama__bio-section_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_bio_section_0_ama__bio-section_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_content_with_label_0_dt_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_content_with_label_0_dt_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_content_with_label_0_dt_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_content_with_label_0_dt_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_content_with_label_0_dt_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_content_with_label_as_list_0_dl_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_content_with_label_as_list_0_dl_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_content_with_label_as_list_0_dl_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_content_with_label_as_list_0_dl_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_content_with_label_as_list_0_dl_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_people_bio_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_people_bio_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_people_bio_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_people_bio_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_people_bio_0_document_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_templates-two-column-right-full-width_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_templates-two-column-right-full-width_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_templates-two-column-right-full-width_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_templates-two-column-right-full-width_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_templates-two-column-right-full-width_0_document_4_bp-xl.png
  styleguide/config/config.yml
  styleguide/source/_patterns/01-atoms/subtitle.twig
  styleguide/source/_patterns/02-molecules/content-with-label-as-list.json
  styleguide/source/_patterns/02-molecules/content-with-label-as-list.md
  styleguide/source/_patterns/02-molecules/content-with-label-as-list.twig
  styleguide/source/_patterns/02-molecules/content-with-label.json
  styleguide/source/_patterns/02-molecules/content-with-label.md
  styleguide/source/_patterns/02-molecules/content-with-label.twig
  styleguide/source/_patterns/02-molecules/content-with-label~as-gated.json
  styleguide/source/_patterns/03-organisms/bio-image-with-body.json
  styleguide/source/_patterns/03-organisms/bio-image-with-body.md
  styleguide/source/_patterns/03-organisms/bio-image-with-body.twig
  styleguide/source/_patterns/03-organisms/bio-section.json
  styleguide/source/_patterns/03-organisms/bio-section.md
  styleguide/source/_patterns/03-organisms/bio-section.twig
  styleguide/source/_patterns/04-templates/two-column-right-full-width.twig
  styleguide/source/_patterns/05-pages/people-bio.json
  styleguide/source/_patterns/05-pages/people-bio.twig
  styleguide/source/assets/scss/02-molecules/_content-with-label.scss
  styleguide/source/assets/scss/03-organisms/_bio-image-with-body.scss
  styleguide/source/assets/scss/03-organisms/_bio-section.scss
  styleguide/source/assets/scss/04-templates/_two-column-right--full-width.scss
  styleguide/source/assets/scss/05-pages/_people_bio.scss
Labels: in review, priority

#317 EWL-5386 people listing page finalized
  styleguide/backstop.json
  styleguide/backstop_data/bitmaps_reference/backstop_default_category_page_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_category_page_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_category_page_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_category_page_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_category_page_0_document_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_error-page_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_error-page_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_error-page_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_error-page_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_error-page_0_document_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_people_listing_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_people_listing_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_people_listing_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_people_listing_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_people_listing_0_document_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_promo_group_0_ama__promo-group_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_promo_group_0_ama__promo-group_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_promo_group_0_ama__promo-group_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_promo_group_0_ama__promo-group_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_promo_group_0_ama__promo-group_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_subcategory_featured_content_0_ama__subcategory-featured-content_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_subcategory_featured_content_0_ama__subcategory-featured-content_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_subcategory_featured_content_0_ama__subcategory-featured-content_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_subcategory_featured_content_0_ama__subcategory-featured-content_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_subcategory_featured_content_0_ama__subcategory-featured-content_4_bp-xl.png
  styleguide/source/_patterns/01-atoms/link/link.twig
  styleguide/source/_patterns/02-molecules/people-listing/people-listing.md
  styleguide/source/_patterns/02-molecules/people-listing/people-listing.twig
  styleguide/source/_patterns/02-molecules/people-listing/people-listing~as-card-with-cta.json
  styleguide/source/_patterns/02-molecules/people-listing/people-listing~as-card.json
  styleguide/source/_patterns/03-organisms/promo-group.twig
  styleguide/source/_patterns/03-organisms/subcategory-featured-content.twig
  styleguide/source/_patterns/05-pages/category.twig
  styleguide/source/_patterns/05-pages/people-listing.json
  styleguide/source/_patterns/05-pages/people-listing.twig
  styleguide/source/assets/scss/02-molecules/_people-listing.scss
  styleguide/source/assets/scss/05-pages/_people-listing.scss
Labels: in review

#323 EWL-5433: Add $homepagePurple to color palette
  styleguide/source/_patterns/00-base/colors.json
  styleguide/source/_patterns/00-base/colors.twig
  styleguide/source/assets/scss/00-base/_colors.scss
Labels: ok to merge, priority

#326 EWL-5434: Create "headings as homepage" variant
  styleguide/backstop_data/bitmaps_reference/backstop_default_atoms_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_atoms_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_atoms_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_atoms_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_atoms_0_document_4_bp-xl.png
  styleguide/source/_patterns/01-atoms/heading/headings.twig
  styleguide/source/_patterns/01-atoms/heading/headings~as-homepage.json
  styleguide/source/assets/scss/00-base/__01.mixins/_font-variables.scss
  styleguide/source/assets/scss/00-base/_typography.scss
Labels: ok to merge

#327 EWL-5446: Create "section title" atom
  styleguide/source/_patterns/01-atoms/section-title.json
  styleguide/source/_patterns/01-atoms/section-title.md
  styleguide/source/_patterns/01-atoms/section-title.twig
  styleguide/source/assets/scss/01-atoms/_section-title.scss
Labels: ok to merge

#324 EWL-5449: Create "button as homepage" and "button as homepage secondary"
  styleguide/backstop_data/bitmaps_reference/backstop_default_atoms_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_atoms_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_atoms_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_atoms_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_atoms_0_document_4_bp-xl.png
  styleguide/source/_patterns/01-atoms/button/button.md
  styleguide/source/_patterns/01-atoms/button/button~as-homepage-secondary.json
  styleguide/source/_patterns/01-atoms/button/button~as-homepage.json
  styleguide/source/assets/scss/00-base/__01.mixins/_ama-button.scss
  styleguide/source/assets/scss/01-atoms/_button.scss
Labels: ok to merge

#330 EWL-5457 SG2 | Create "Link List" Molecule
  styleguide/backstop.json
  styleguide/backstop_data/bitmaps_reference/backstop_default_link_list_0_ama__link-list_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_link_list_0_ama__link-list_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_link_list_0_ama__link-list_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_link_list_0_ama__link-list_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_link_list_0_ama__link-list_4_bp-xl.png
  styleguide/source/_patterns/02-molecules/link-list.json
  styleguide/source/_patterns/02-molecules/link-list.md
  styleguide/source/_patterns/02-molecules/link-list.twig
  styleguide/source/assets/scss/00-base/__01.mixins/_font-variables.scss
  styleguide/source/assets/scss/00-base/_typography.scss
  styleguide/source/assets/scss/01-atoms/_links.scss
  styleguide/source/assets/scss/02-molecules/_link-list.scss
Labels: in review, priority

#328 EWL-5435: Create homepage stub pattern
  styleguide/backstop.json
  styleguide/backstop_data/bitmaps_reference/backstop_default_homepage_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_homepage_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_homepage_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_homepage_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_homepage_0_document_4_bp-xl.png
  styleguide/source/_patterns/05-pages/homepage.json
  styleguide/source/_patterns/05-pages/homepage.md
  styleguide/source/_patterns/05-pages/homepage.twig
  styleguide/source/assets/scss/05-pages/_homepage.scss
Labels: in review

#333 EWL-5402 Adds Profession to the four list links molecule
  styleguide/backstop_data/bitmaps_reference/backstop_default_four_up_list_links_0_ama__four-up-links_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_four_up_list_links_0_ama__four-up-links_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_four_up_list_links_0_ama__four-up-links_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_four_up_list_links_0_ama__four-up-links_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_people_listing_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_people_listing_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_people_listing_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_people_listing_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_people_listing_0_document_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_ribbon_0_ama__ribbon__dropdown_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_ribbon_1_ama__ribbon__dropdown__n1_1_bp-small.png
  styleguide/source/_patterns/02-molecules/link-list.md
  styleguide/source/_patterns/02-molecules/people-listing/people-listing.twig
  styleguide/source/_patterns/02-molecules/people-listing/people-listing~as-card-with-cta.json
  styleguide/source/_patterns/02-molecules/people-listing/people-listing~as-card.json
  styleguide/source/_patterns/05-pages/people-listing.json
  styleguide/source/_patterns/05-pages/resource.md
Labels: ready for review

#316 [EWL-5018] SG2 | Code standards to-dos for Resource page
  styleguide/backstop_data/bitmaps_reference/backstop_default_resource_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_resource_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_resource_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_resource_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_resource_0_document_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_resource_tabs_0_ama__resource-tabs_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_resource_tabs_0_ama__resource-tabs_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_resource_tabs_0_ama__resource-tabs_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_resource_tabs_0_ama__resource-tabs_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_resource_tabs_0_ama__resource-tabs_4_bp-xl.png
  styleguide/source/_patterns/02-molecules/resource-link-as-inline.twig
  styleguide/source/_patterns/03-organisms/resource-tabs.json
  styleguide/source/_patterns/03-organisms/resource-tabs.twig
  styleguide/source/_patterns/05-pages/resource.json
  styleguide/source/_patterns/05-pages/resource.md
  styleguide/source/_patterns/05-pages/resource.twig
  styleguide/source/assets/js/tabs.js
  styleguide/source/assets/scss/01-atoms/_links.scss
  styleguide/source/assets/scss/03-organisms/_resource-tabs.scss
  styleguide/source/assets/scss/04-templates/_split.scss
Labels: ok to merge, priority

#329 EWL-5437: Create "article stub for homepage" molecule
  styleguide/backstop.json
  styleguide/source/_patterns/02-molecules/article-stub/article-stub.md
  styleguide/source/_patterns/02-molecules/article-stub/article-stub.twig
  styleguide/source/_patterns/02-molecules/article-stub/article-stub~as-hero-for-homepage.json
  styleguide/source/_patterns/02-molecules/article-stub/article-stub~for-homepage.json
  styleguide/source/assets/scss/00-base/__01.mixins/_font-variables.scss
  styleguide/source/assets/scss/00-base/_typography.scss
  styleguide/source/assets/scss/02-molecules/_article-stub.scss
Labels: ok to merge, priority

#341 [EWL-5018] SG2 | Update Build Config for Resource Tabs
  styleguide/build.config.json
  styleguide/source/assets/js/tabs.js
Labels: has D8 dependency, ok to merge, priority

#335 Adds EWL-5445 subscribe promo as wide
  styleguide/source/_patterns/02-molecules/subscribe-promo.twig
  styleguide/source/_patterns/02-molecules/subscribe-promo~as-wide.json
  styleguide/source/assets/scss/02-molecules/_subscribe-promo.scss
Labels: in review

#336 [EWL-5438] SG2 | Create "Product Nav" Organism
  styleguide/backstop.json
  styleguide/source/_patterns/03-organisms/product-nav.json
  styleguide/source/_patterns/03-organisms/product-nav.md
  styleguide/source/_patterns/03-organisms/product-nav.twig
  styleguide/source/_patterns/05-pages/homepage.json
  styleguide/source/_patterns/05-pages/homepage.twig
  styleguide/source/assets/scss/03-organisms/_product-nav.scss
Labels: ok to merge, priority

#331 [EWL-5448] SG2 | Create "Hero Story" Molecule
  styleguide/source/_patterns/02-molecules/hero-story.json
  styleguide/source/_patterns/02-molecules/hero-story.md
  styleguide/source/_patterns/02-molecules/hero-story.twig
  styleguide/source/_patterns/02-molecules/hero-story~as-video.json
  styleguide/source/assets/scss/02-molecules/_hero-story.scss
Labels: in review, priority

#337 EWl-5459 adds partner promo as homepage molecule
  styleguide/backstop.json
  styleguide/source/_patterns/01-atoms/button/button.md
  styleguide/source/_patterns/01-atoms/button/button~as-promo.json
  styleguide/source/_patterns/02-molecules/partner-promo.json
  styleguide/source/_patterns/02-molecules/partner-promo.twig
  styleguide/source/_patterns/02-molecules/partner-promo~as-homepage.json
  styleguide/source/assets/scss/00-base/__01.mixins/_ama-button.scss
  styleguide/source/assets/scss/01-atoms/_button.scss
  styleguide/source/assets/scss/02-molecules/_partner-promo.scss
Labels: in review

#338 EWL-5460 adds promo as homepage variant
  styleguide/backstop.json
  styleguide/source/_patterns/02-molecules/promo/promo-as-homepage.md
  styleguide/source/_patterns/02-molecules/promo/promo.json
  styleguide/source/_patterns/02-molecules/promo/promo.md
  styleguide/source/_patterns/02-molecules/promo/promo.twig
  styleguide/source/_patterns/02-molecules/promo/promo~as-homepage.json
  styleguide/source/_patterns/02-molecules/promo/promo~as-inline.json
  styleguide/source/_patterns/02-molecules/promo/promo~with-border.json
  styleguide/source/_patterns/02-molecules/promo/promo~with-cta.json
  styleguide/source/_patterns/02-molecules/promo/promo~with-image.json
  styleguide/source/assets/scss/02-molecules/_promo.scss
Labels: in review

#348 removes ready selectors causing Travis to fail on backstop tests
  styleguide/backstop.json
Labels: in review, priority

#342 EWL-5439: Create category nav organism
  styleguide/backstop.json
  styleguide/source/_patterns/03-organisms/category-nav.json
  styleguide/source/_patterns/03-organisms/category-nav.md
  styleguide/source/_patterns/03-organisms/category-nav.twig
  styleguide/source/_patterns/05-pages/homepage.json
  styleguide/source/_patterns/05-pages/homepage.twig
  styleguide/source/assets/scss/03-organisms/_category-nav.scss
Labels: ok to merge, priority

#343 EWL-5440: Create "Org Nav" Organism
  styleguide/backstop.json
  styleguide/source/_patterns/03-organisms/org-nav.json
  styleguide/source/_patterns/03-organisms/org-nav.md
  styleguide/source/_patterns/03-organisms/org-nav.twig
  styleguide/source/_patterns/05-pages/homepage.json
  styleguide/source/_patterns/05-pages/homepage.twig
  styleguide/source/assets/scss/03-organisms/_category-nav.scss
  styleguide/source/assets/scss/03-organisms/_org-nav.scss
  styleguide/source/assets/scss/05-pages/_homepage.scss
Labels: ok to merge

#334 EWL-5444: Create alert
  styleguide/backstop.json
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-homepage-alert.twig
  styleguide/source/_patterns/02-molecules/alert.json
  styleguide/source/_patterns/02-molecules/alert.md
  styleguide/source/_patterns/02-molecules/alert.twig
  styleguide/source/_patterns/05-pages/homepage.json
  styleguide/source/_patterns/05-pages/homepage.twig
  styleguide/source/assets/icons/svg/icon-homepage-alert.svg
  styleguide/source/assets/js/alert.js
  styleguide/source/assets/scss/02-molecules/_alert.scss
Labels: ok to merge

#347 EWl-5463: Create products molecule and Your Products Organism
  styleguide/backstop.json
  styleguide/source/_patterns/01-atoms/section-title.twig
  styleguide/source/_patterns/02-molecules/product.json
  styleguide/source/_patterns/02-molecules/product.md
  styleguide/source/_patterns/02-molecules/product.twig
  styleguide/source/_patterns/03-organisms/upcoming-events.json
  styleguide/source/_patterns/03-organisms/upcoming-events.twig
  styleguide/source/_patterns/03-organisms/your-products.json
  styleguide/source/_patterns/03-organisms/your-products.md
  styleguide/source/_patterns/03-organisms/your-products.twig
  styleguide/source/_patterns/05-pages/homepage.json
  styleguide/source/_patterns/05-pages/homepage.twig
  styleguide/source/assets/scss/02-molecules/_product.scss
Labels: ok to merge

#346 [EWL-5442] SG2 | Create "JAMA as Homepage" variant
  styleguide/source/_patterns/02-molecules/jama/jama.json
  styleguide/source/_patterns/02-molecules/jama/jama.twig
  styleguide/source/_patterns/02-molecules/jama/jama~as-homepage.json
  styleguide/source/_patterns/05-pages/homepage.json
  styleguide/source/_patterns/05-pages/homepage.twig
  styleguide/source/assets/scss/02-molecules/_jama.scss
Labels: ok to merge, priority

#344 [EWL-5454] SG2 | Create "Member Feature Rail" Molecule
  styleguide/backstop.json
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-triangle.twig
  styleguide/source/_patterns/02-molecules/member-feature-rail.json
  styleguide/source/_patterns/02-molecules/member-feature-rail.md
  styleguide/source/_patterns/02-molecules/member-feature-rail.twig
  styleguide/source/assets/icons/svg/icon-triangle.svg
  styleguide/source/assets/scss/01-atoms/_icons.scss
  styleguide/source/assets/scss/02-molecules/_member-feature-rail.scss
Labels: ok to merge, priority

#345 [EWL-5456] SG2 | Create "Member Feature" Organism
  styleguide/backstop.json
  styleguide/source/_patterns/01-atoms/section-title.json
  styleguide/source/_patterns/03-organisms/member-feature.json
  styleguide/source/_patterns/03-organisms/member-feature.md
  styleguide/source/_patterns/03-organisms/member-feature.twig
  styleguide/source/_patterns/05-pages/homepage.json
  styleguide/source/_patterns/05-pages/homepage.twig
  styleguide/source/assets/scss/03-organisms/_member-feature.scss
Labels: ok to merge, priority

#349 Finalize the homepage for delivery
  styleguide/source/_patterns/03-organisms/member-feature.twig
  styleguide/source/_patterns/05-pages/homepage.json
  styleguide/source/_patterns/05-pages/homepage.twig
  styleguide/source/assets/scss/05-pages/_homepage.scss
Labels: work in progress

#350 EWL-5515 - Fixes tabs on events page
  styleguide/source/_patterns/03-organisms/page-content-tabs.twig
  styleguide/source/_patterns/03-organisms/resource-tabs.twig
  styleguide/source/assets/js/tabs.js
Labels: in review, priority

#353 EWL-5512: Homepage fixes in IE11
  styleguide/source/assets/scss/02-molecules/_product.scss
  styleguide/source/assets/scss/05-pages/_homepage.scss
Labels: ok to merge

#352 [EWL-5306] SG2 | Fix Event Listing Page Templates
  styleguide/source/_patterns/04-templates/two-column-left.twig
Labels: in review

#356 EWL-5525 Updates per Feedback from UX
  styleguide/source/_patterns/02-molecules/people-listing/people-listing~as-card-with-cta.json
  styleguide/source/_patterns/02-molecules/people-listing/people-listing~as-card.json
  styleguide/source/_patterns/05-pages/people-listing.json
Labels: in review

#357 moves the ul list bullets from outside to inside on hub pages
  styleguide/source/assets/scss/02-molecules/hub/_hub-hero.scss
Labels: in review, priority

#355 EWL-5526 people bio feedback
  styleguide/source/_patterns/02-molecules/content-with-label.twig
  styleguide/source/_patterns/03-organisms/bio-image-with-body.json
  styleguide/source/_patterns/05-pages/people-bio.json
  styleguide/source/assets/scss/02-molecules/_content-with-label.scss
Labels: in review

#358 EWL-5589 main navigation stub
  styleguide/source/_patterns/03-organisms/main-navigation.json
  styleguide/source/_patterns/03-organisms/main-navigation.md
  styleguide/source/_patterns/03-organisms/main-navigation.twig
  styleguide/source/assets/scss/03-organisms/_main-navigation.scss
Labels: in review

#360 EWL-4936: add image tool icon to resource tabs
  styleguide/source/_patterns/03-organisms/resource-tabs.json
  styleguide/source/_patterns/03-organisms/resource-tabs.twig
  styleguide/source/_patterns/05-pages/resource.json
Labels: ok to merge

#359 EWL-5582 Create menu icon
  styleguide/source/_patterns/01-atoms/menu-icon.json
  styleguide/source/_patterns/01-atoms/menu-icon.twig
  styleguide/source/_patterns/03-organisms/main-navigation.json
  styleguide/source/_patterns/03-organisms/main-navigation.twig
  styleguide/source/assets/scss/01-atoms/_menu-icon.scss
  styleguide/source/assets/scss/03-organisms/_main-navigation.scss
Labels: in review

#361 EWL-5586 add white site logo
  styleguide/source/_patterns/01-atoms/site-logo/site-logo-as-jama.md
  styleguide/source/_patterns/01-atoms/site-logo/site-logo-as-jama.twig
  styleguide/source/_patterns/01-atoms/site-logo/site-logo.json
  styleguide/source/_patterns/01-atoms/site-logo/site-logo.twig
  styleguide/source/_patterns/01-atoms/site-logo/site-logo~as-jama.json
  styleguide/source/_patterns/01-atoms/site-logo/site-logo~as-white.json
  styleguide/source/_patterns/03-organisms/main-navigation.json
  styleguide/source/_patterns/03-organisms/main-navigation.twig
  styleguide/source/assets/scss/01-atoms/_icons.scss
  styleguide/source/assets/scss/01-atoms/_site_logo.scss
  styleguide/source/assets/scss/03-organisms/_main-navigation.scss
Labels: in review

#354 EWL-5527 homepage feedback
  styleguide/source/_patterns/01-atoms/section-title.twig
  styleguide/source/_patterns/02-molecules/jama/jama.twig
  styleguide/source/_patterns/02-molecules/member-feature-rail.json
  styleguide/source/_patterns/02-molecules/partner-promo.twig
  styleguide/source/_patterns/02-molecules/product.json
  styleguide/source/_patterns/02-molecules/product.twig
  styleguide/source/_patterns/03-organisms/category-nav.json
  styleguide/source/_patterns/03-organisms/four-up-lists.json
  styleguide/source/_patterns/03-organisms/four-up-lists.twig
  styleguide/source/_patterns/03-organisms/org-nav.json
  styleguide/source/_patterns/05-pages/category.json
  styleguide/source/_patterns/05-pages/homepage.json
  styleguide/source/_patterns/05-pages/homepage.twig
  styleguide/source/assets/scss/00-base/__01.mixins/_ama-button-base.scss
  styleguide/source/assets/scss/00-base/__01.mixins/_ama-button.scss
  styleguide/source/assets/scss/00-base/__01.mixins/_font-variables.scss
  styleguide/source/assets/scss/01-atoms/_button.scss
  styleguide/source/assets/scss/01-atoms/_links.scss
  styleguide/source/assets/scss/02-molecules/_alert.scss
  styleguide/source/assets/scss/02-molecules/_jama.scss
  styleguide/source/assets/scss/02-molecules/_link-list.scss
  styleguide/source/assets/scss/02-molecules/_member-feature-rail.scss
  styleguide/source/assets/scss/02-molecules/_product.scss
  styleguide/source/assets/scss/02-molecules/_promo.scss
  styleguide/source/assets/scss/02-molecules/_subscribe-promo.scss
  styleguide/source/assets/scss/02-molecules/_upcoming-event.scss
  styleguide/source/assets/scss/03-organisms/_member-feature.scss
  styleguide/source/assets/scss/03-organisms/_product-nav.scss
  styleguide/source/assets/scss/05-pages/_homepage.scss
Labels: in review

#362 EWL-5587 button as secondary small
  styleguide/source/_patterns/01-atoms/button/button~as-secondary-small.json
  styleguide/source/_patterns/03-organisms/main-navigation.json
  styleguide/source/_patterns/03-organisms/main-navigation.twig
  styleguide/source/assets/scss/00-base/__01.mixins/_ama-button.scss
  styleguide/source/assets/scss/00-base/__01.mixins/_font-variables.scss
  styleguide/source/assets/scss/00-base/_typography.scss
  styleguide/source/assets/scss/01-atoms/_button.scss
  styleguide/source/assets/scss/03-organisms/_main-navigation.scss
Labels: in review

#364 EWL-5595 create article stub as navigation variant
  styleguide/source/_patterns/02-molecules/article-stub/article-stub.md
  styleguide/source/_patterns/02-molecules/article-stub/article-stub.twig
  styleguide/source/_patterns/02-molecules/article-stub/article-stub~as-for-navigation.json
  styleguide/source/assets/scss/02-molecules/_article-stub.scss
Labels: in review, priority

#367 EWL-5598 create explore menu
  styleguide/source/_patterns/02-molecules/explore-menu.json
  styleguide/source/_patterns/02-molecules/explore-menu.md
  styleguide/source/_patterns/02-molecules/explore-menu.twig
  styleguide/source/assets/js/global-search.js
  styleguide/source/assets/scss/02-molecules/_explore-menu.scss
Labels: in review

#363 EWL-5591 global search molecule
  styleguide/source/_patterns/01-atoms/forms/search-field-as-in-body.twig
  styleguide/source/_patterns/02-molecules/global-search.json
  styleguide/source/_patterns/02-molecules/global-search.twig
  styleguide/source/_patterns/03-organisms/main-navigation.json
  styleguide/source/_patterns/03-organisms/main-navigation.twig
  styleguide/source/assets/scss/01-atoms/_menu-icon.scss
  styleguide/source/assets/scss/02-molecules/_global-search.scss
  styleguide/source/assets/scss/03-organisms/_main-navigation.scss
Labels: in review

#368 EWL-5662 Fixes paths for jama logos
  styleguide/source/_patterns/02-molecules/jama/jama.json
  styleguide/source/_patterns/02-molecules/jama/jama.twig
  styleguide/source/_patterns/02-molecules/jama/jama~as-content-bottom.json
  styleguide/source/_patterns/02-molecules/jama/jama~as-homepage.json
  styleguide/source/_patterns/02-molecules/jama/jama~as-three-up.json
  styleguide/source/_patterns/05-pages/category.json
  styleguide/source/_patterns/05-pages/homepage.json
  styleguide/source/_patterns/05-pages/news/news-with-jama-examples.json
Labels: in review, priority

#369 EWL-5664 Fix Article four up teasers margins on various screen sizes
  styleguide/source/_patterns/03-organisms/category-index.json
  styleguide/source/_patterns/03-organisms/subcategory-index.json
  styleguide/source/_patterns/05-pages/subcategory.json
  styleguide/source/assets/scss/02-molecules/_article-stub.scss
  styleguide/source/assets/scss/03-organisms/_four-up-teaser.scss
Labels: in review

#366 EWL-5597 create user dropdown menu
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-usermenu-outline.twig
  styleguide/source/_patterns/02-molecules/sign-in-dropdown.json
  styleguide/source/_patterns/02-molecules/sign-in-dropdown.md
  styleguide/source/_patterns/02-molecules/sign-in-dropdown.twig
  styleguide/source/_patterns/03-organisms/main-navigation.json
  styleguide/source/_patterns/03-organisms/main-navigation.twig
  styleguide/source/assets/icons/svg/icon-usermenu-outline.svg
  styleguide/source/assets/scss/01-atoms/_icons.scss
  styleguide/source/assets/scss/01-atoms/_search-field.scss
  styleguide/source/assets/scss/02-molecules/_global-search.scss
  styleguide/source/assets/scss/02-molecules/_sign-in-dropdown.scss
  styleguide/source/assets/scss/02-molecules/hub/_hub-card-row.scss
  styleguide/source/assets/scss/02-molecules/hub/_hub-card.scss
  styleguide/source/assets/scss/03-organisms/_main-navigation.scss
Labels: ok to merge, priority

#372 EWL-5667: add images to the news article page.
  styleguide/source/_patterns/05-pages/news/news.json
  styleguide/source/assets/scss/01-atoms/_image.scss
Labels: ok to merge
