Repository AmericanMedicalAssociation/ama-style-guide-2, pull requests merged in 2018-03, with the labels that each got.

#124 [EWL-4627] Adjust link class
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_4_bp-xl.png
  styleguide/source/_patterns/05-pages/news.json
Labels: ready for review

#127 [EWL-4628] fix Tools heading size and article stub image/text alignment
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release_0_document_4_bp-xl.png
  styleguide/source/_patterns/03-organisms/tools-block.json
  styleguide/source/_patterns/05-pages/news.json
  styleguide/source/_patterns/05-pages/press-release.json
  styleguide/source/_patterns/05-pages/topic.json
  styleguide/source/assets/scss/02-molecules/_article-stub.scss
Labels: in review, priority

#125 [EWL-4640] - Remove purple background on aside links
  styleguide/source/assets/scss/01-atoms/_links.scss
Labels: ready for review

#134 Add missing link in promo.json file
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-masthead-with-subtitle_0_ama__masthead_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-masthead-with-subtitle_0_ama__masthead_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-masthead-with-subtitle_0_ama__masthead_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-masthead_0_ama__masthead_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-masthead_0_ama__masthead_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-masthead_0_ama__masthead_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_0_document_4_bp-xl.png
  styleguide/source/_patterns/02-molecules/promo.json
Labels: in review, ready for review

#133 [EWL-4647] Add proper BEM classes to Ribbon elements
  styleguide/source/_patterns/02-molecules/ribbon-dropdown.twig
  styleguide/source/_patterns/02-molecules/ribbon-user-menu.twig
  styleguide/source/_patterns/03-organisms/ribbon.twig
  styleguide/source/assets/js/nav.js
  styleguide/source/assets/scss/02-molecules/_ribbon-dropdown.scss
  styleguide/source/assets/scss/02-molecules/_ribbon-user-menu.scss
  styleguide/source/assets/scss/03-organisms/_ribbon.scss
Labels: ready for review

#126 [EWL-4570] Update variant options so that they work on github.io
  styleguide/source/_patterns/02-molecules/info-card.md
  styleguide/source/_patterns/02-molecules/partner-info.md
  styleguide/source/_patterns/02-molecules/promo-with-border.md
  styleguide/source/_patterns/02-molecules/promo-with-cta.md
  styleguide/source/_patterns/02-molecules/promo-with-image.md
  styleguide/source/_patterns/02-molecules/promo.md
  styleguide/source/_patterns/02-molecules/ribbon-dropdown.md
  styleguide/source/_patterns/02-molecules/ribbon-user-menu.md
  styleguide/source/_patterns/03-organisms/masthead.md
  styleguide/source/_patterns/03-organisms/membership-with-cta.md
  styleguide/source/_patterns/03-organisms/membership.md
Labels: ready for review

#128 EWL-4656: Fix SVG icons appear as 404 in the D8 theme
  styleguide/source/assets/scss/02-molecules/_social-share.scss
Labels: ready for review

#132 EWL-4654 SG2 | Refactor spacing of page elements
  styleguide/source/_patterns/03-organisms/footer.twig
  styleguide/source/assets/scss/00-base/__01.mixins/_gutter_mixin.scss
  styleguide/source/assets/scss/00-base/_deprecated.scss
  styleguide/source/assets/scss/02-molecules/_article-stub.scss
  styleguide/source/assets/scss/02-molecules/_lead-news.scss
  styleguide/source/assets/scss/02-molecules/_promo.scss
  styleguide/source/assets/scss/02-molecules/_tools-learn-more.scss
  styleguide/source/assets/scss/03-organisms/_footer.scss
  styleguide/source/assets/scss/03-organisms/_membership.scss
  styleguide/source/assets/scss/03-organisms/_tools-block.scss
  styleguide/source/assets/scss/04-templates/_three_column.scss
  styleguide/source/assets/scss/04-templates/_two_column-right.scss
Labels: in review

#135 EWL-4642: Add wayfinder and ribbon to topics page
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-promo-with-border_0_ama__promo_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-promo-with-border_0_ama__promo_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-promo-with-border_0_ama__promo_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-promo-with-border_0_ama__promo_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-promo-with-border_0_ama__promo_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-promo-with-cta_0_ama__promo_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-promo-with-cta_0_ama__promo_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-promo-with-cta_0_ama__promo_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-promo-with-cta_0_ama__promo_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-promo-with-cta_0_ama__promo_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-promo_0_ama__promo_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-promo_0_ama__promo_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-promo_0_ama__promo_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-promo_0_ama__promo_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-promo_0_ama__promo_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_0_document_4_bp-xl.png
  styleguide/source/_patterns/05-pages/topic.json
  styleguide/source/_patterns/05-pages/topic.twig
Labels: ready for review

#129 EWL-4657: footer menu link class
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_0_document_2_bp-med.png
  styleguide/source/_patterns/03-organisms/footer.json
  styleguide/source/_patterns/03-organisms/footer.twig
  styleguide/source/_patterns/05-pages/topic.json
  styleguide/source/_patterns/05-pages/topic.twig
Labels: has D8 dependency, in review

#131 EWL-4650: Center wayfinder logo
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-masthead-with-subtitle_0_ama__masthead_1_bp-small.png
  styleguide/source/assets/scss/03-organisms/_wayfinder.scss
Labels: in review

#138 [EWL-4682] TOPICs | Remove unnecessary <div> around Membership Block
  styleguide/source/_patterns/03-organisms/membership.json
  styleguide/source/_patterns/03-organisms/membership.twig
  styleguide/source/_patterns/03-organisms/membership~with-cta.json
  styleguide/source/_patterns/05-pages/news.json
  styleguide/source/assets/scss/03-organisms/_membership.scss
Labels: has D8 dependency, ok to merge

#136 EWL-4643: Remove wayfinder and ribbon from news page
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_0_document_0_bp-xs.png
  styleguide/source/_patterns/05-pages/news.json
  styleguide/source/_patterns/05-pages/news.twig
Labels: in review

#142 [EWL-4724] SG2/D8 | Fix heading text for the Footer to work in D8
  styleguide/source/_patterns/03-organisms/footer.json
  styleguide/source/_patterns/03-organisms/footer.twig
Labels: in review, priority

#140 [EWL-4699] Fix linked titles in Article Stubs in Lead News Block
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_1_bp-small.png
  styleguide/source/_patterns/02-molecules/article-stub.json
  styleguide/source/_patterns/02-molecules/article-stub.twig
  styleguide/source/_patterns/05-pages/topic.json
Labels: has D8 dependency, in review, merge conflict

#139 [EWL-4660] TOPICS | Use a <hr> to visually separate multiple Article stub patterns
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-article-stub-title-only_0_ama__article-stub_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-article-stub-title-only_0_ama__article-stub_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-article-stub-title-only_0_ama__article-stub_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-article-stub-title-only_0_ama__article-stub_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-article-stub-title-only_0_ama__article-stub_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-lead-news_0_ama__lead-news_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-lead-news_0_ama__lead-news_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-lead-news_0_ama__lead-news_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-lead-news_0_ama__lead-news_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-lead-news_0_ama__lead-news_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_0_document_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_5_ama__lead-news_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_5_ama__lead-news_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_5_ama__lead-news_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_5_ama__lead-news_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_5_ama__lead-news_4_bp-xl.png
  styleguide/source/_patterns/02-molecules/article-stub.twig
  styleguide/source/_patterns/05-pages/topic.json
  styleguide/source/assets/scss/02-molecules/_article-stub.scss
  styleguide/source/assets/scss/02-molecules/_lead-news.scss
  styleguide/source/assets/scss/03-organisms/_column-teaser.scss
Labels: in review

#147 [EWL-4389] SG2 | Create Sidebar Articles pattern
  styleguide/backstop.json
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-sidebar-articles_0_ama__sidebar-articles_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-sidebar-articles_0_ama__sidebar-articles_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-sidebar-articles_0_ama__sidebar-articles_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-sidebar-articles_0_ama__sidebar-articles_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-sidebar-articles_0_ama__sidebar-articles_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_6_ama__sidebar-articles_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_6_ama__sidebar-articles_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_6_ama__sidebar-articles_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_6_ama__sidebar-articles_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_6_ama__sidebar-articles_4_bp-xl.png
  styleguide/source/_patterns/03-organisms/sidebar-articles.json
  styleguide/source/_patterns/03-organisms/sidebar-articles.md
  styleguide/source/_patterns/03-organisms/sidebar-articles.twig
  styleguide/source/_patterns/05-pages/topic.json
  styleguide/source/_patterns/05-pages/topic.twig
  styleguide/source/assets/scss/03-organisms/_sidebar-articles.scss
Labels: priority, ready for review

#141 [EWL-4633] SG2 | Hide IPE from the SG2 menu
  styleguide/source/_patterns/00-base/_in-place-editor.md
  styleguide/source/_patterns/00-base/_in-place-editor.twig
  styleguide/source/assets/scss/00-base/_in-place-editor.scss
Labels: in review

#144 EWL-4655: Add secondary button variation
  styleguide/source/_patterns/01-atoms/button~as-secondary.json
Labels: in review

#130 [EWL-4645] Update SG2 with Drupal implementation of userMenu
  styleguide/source/_patterns/02-molecules/ribbon-user-menu.json
  styleguide/source/_patterns/03-organisms/ribbon.json
  styleguide/source/_patterns/03-organisms/ribbon.twig
  styleguide/source/_patterns/05-pages/news.json
Labels: has D8 dependency, in review

#143 EWL-4644: Fix ribbon dropdown menu and link styles
  styleguide/source/_patterns/02-molecules/ribbon-user-menu.json
  styleguide/source/_patterns/03-organisms/ribbon.json
  styleguide/source/_patterns/03-organisms/ribbon.twig
  styleguide/source/assets/scss/02-molecules/_ribbon-dropdown.scss
  styleguide/source/assets/scss/02-molecules/_ribbon-user-menu.scss
Labels: in review

#149 EWL-4713: move membership from organism to molecule
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-membership-with-cta_0_ama__membership_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-membership-with-cta_0_ama__membership_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-membership-with-cta_0_ama__membership_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-membership-with-cta_0_ama__membership_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-membership-with-cta_0_ama__membership_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-membership_0_ama__membership_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-membership_0_ama__membership_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-membership_0_ama__membership_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-membership_0_ama__membership_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-membership_0_ama__membership_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_7_ama__footer_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_7_ama__footer_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_7_ama__footer_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_7_ama__footer_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_7_ama__footer_4_bp-xl.png
  styleguide/source/_patterns/02-molecules/membership-with-cta.md
  styleguide/source/_patterns/02-molecules/membership.json
  styleguide/source/_patterns/02-molecules/membership.md
  styleguide/source/_patterns/02-molecules/membership.twig
  styleguide/source/_patterns/02-molecules/membership~with-cta.json
  styleguide/source/_patterns/05-pages/news.twig
  styleguide/source/_patterns/05-pages/press-release.twig
  styleguide/source/_patterns/05-pages/topic.twig
Labels: has D8 dependency, in review

#151 [EWL-4700] Fix linked titles in Article Stubs in Sidebar block
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-sidebar-articles_0_ama__sidebar-articles_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-sidebar-articles_0_ama__sidebar-articles_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-sidebar-articles_0_ama__sidebar-articles_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-sidebar-articles_0_ama__sidebar-articles_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-sidebar-articles_0_ama__sidebar-articles_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_6_ama__sidebar-articles_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_6_ama__sidebar-articles_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_6_ama__sidebar-articles_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_6_ama__sidebar-articles_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_6_ama__sidebar-articles_4_bp-xl.png
  styleguide/source/_patterns/03-organisms/sidebar-articles.twig
  styleguide/source/assets/scss/03-organisms/_sidebar-articles.scss
Labels: has D8 dependency, in review

#146 EWL-4525: Remove underline for links in the learn more section of the tools block
  styleguide/source/_patterns/02-molecules/tools-learn-more.json
  styleguide/source/_patterns/02-molecules/tools-learn-more.twig
  styleguide/source/_patterns/03-organisms/tools-block.twig
  styleguide/source/assets/scss/02-molecules/_tools-learn-more.scss
Labels: ready for review

#148 EWL-4721: Fix wayfinder referrer pattern
  styleguide/source/_patterns/03-organisms/wayfinder.json
  styleguide/source/_patterns/03-organisms/wayfinder.twig
  styleguide/source/assets/js/wayfinder.js
  styleguide/source/assets/scss/03-organisms/_wayfinder.scss
Labels: priority, ready for review

#150 [EWL-4676] Re-wire tools
  styleguide/source/_patterns/02-molecules/tools-learn-more.json
  styleguide/source/_patterns/02-molecules/tools-learn-more.twig
  styleguide/source/_patterns/02-molecules/tools-list.twig
  styleguide/source/_patterns/03-organisms/tools-block.twig
  styleguide/source/_patterns/03-organisms/tools.json
  styleguide/source/_patterns/03-organisms/tools.md
  styleguide/source/_patterns/03-organisms/tools.twig
  styleguide/source/_patterns/05-pages/news.json
  styleguide/source/_patterns/05-pages/news.twig
  styleguide/source/_patterns/05-pages/press-release.json
  styleguide/source/_patterns/05-pages/press-release.twig
  styleguide/source/_patterns/05-pages/topic.json
  styleguide/source/_patterns/05-pages/topic.twig
  styleguide/source/assets/scss/02-molecules/_tool.scss
  styleguide/source/assets/scss/02-molecules/_tools-learn-more.scss
  styleguide/source/assets/scss/02-molecules/_tools-list.scss
  styleguide/source/assets/scss/03-organisms/_tools-block.scss
  styleguide/source/assets/scss/03-organisms/_tools.scss
Labels: in review, priority

#154 EWL-4658: Update ribbon.md with proper urls for variants
  styleguide/source/_patterns/03-organisms/ribbon.md
Labels: ready for review

#153 EWL-4663 Set configurable headings to be not configurable
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-tools-block_0_ama__tools-block_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-tools-block_0_ama__tools-block_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-tools-block_0_ama__tools-block_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-tools-block_0_ama__tools-block_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_2_ama__tools-block_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_2_ama__tools-block_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_2_ama__tools-block_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_2_ama__tools-block_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_2_ama__tools-block_4_bp-xl.png
  styleguide/source/_patterns/01-atoms/headings.twig
  styleguide/source/_patterns/02-molecules/article-stub-as-inline.json
  styleguide/source/_patterns/02-molecules/article-stub-as-inline.twig
  styleguide/source/_patterns/02-molecules/info-card.twig
  styleguide/source/_patterns/02-molecules/info-card~as-media-contact.json
  styleguide/source/_patterns/02-molecules/inline-bio.json
  styleguide/source/_patterns/02-molecules/inline-bio.twig
  styleguide/source/_patterns/02-molecules/inline-block-copy.json
  styleguide/source/_patterns/02-molecules/inline-block-copy.twig
  styleguide/source/_patterns/02-molecules/membership.json
  styleguide/source/_patterns/02-molecules/membership.twig
  styleguide/source/_patterns/02-molecules/membership~with-cta.json
  styleguide/source/_patterns/02-molecules/partner-info.json
  styleguide/source/_patterns/02-molecules/partner-info.twig
  styleguide/source/_patterns/02-molecules/promo.json
  styleguide/source/_patterns/02-molecules/promo.twig
  styleguide/source/_patterns/02-molecules/promo~with-border.json
  styleguide/source/_patterns/02-molecules/promo~with-cta.json
  styleguide/source/_patterns/02-molecules/promo~with-image.json
  styleguide/source/_patterns/02-molecules/tools-learn-more.json
  styleguide/source/_patterns/02-molecules/tools-learn-more.twig
  styleguide/source/_patterns/03-organisms/masthead.json
  styleguide/source/_patterns/03-organisms/masthead.twig
  styleguide/source/_patterns/03-organisms/masthead~as-indented.json
  styleguide/source/_patterns/03-organisms/masthead~with-subtitle-as-indented.json
  styleguide/source/_patterns/03-organisms/masthead~with-subtitle.json
  styleguide/source/_patterns/03-organisms/partner-list.json
  styleguide/source/_patterns/03-organisms/tools.json
  styleguide/source/_patterns/03-organisms/tools.twig
  styleguide/source/_patterns/05-pages/news.json
  styleguide/source/_patterns/05-pages/news.twig
  styleguide/source/_patterns/05-pages/press-release.json
  styleguide/source/_patterns/05-pages/topic.json
Labels: has D8 dependency, ok to merge

#155 Update backstop tool ref image
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-tools-block_0_ama__tools-block_0_bp-xs.png
Labels: ready for review

#158 EWL-4525: Tool title hover state does not have an underline
  styleguide/source/assets/scss/02-molecules/_tool.scss
Labels: in review

#156 EWL-4742: Fix article stub image position when in mobile
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-article-as-video_0_ama__article-stub--small_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-article-as-video_0_ama__article-stub--small_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-article-as-video_0_ama__article-stub--small_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-article-as-video_0_ama__article-stub--small_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-article-as-video_0_ama__article-stub--small_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-article-stub-as-related_0_ama__article-stub--related_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-article-stub-as-related_0_ama__article-stub--related_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-article-stub-as-related_0_ama__article-stub--related_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-article-stub-as-related_0_ama__article-stub--related_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-article-stub-as-related_0_ama__article-stub--related_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-article-stub-as-small-image_0_ama__article-stub--small_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-article-stub-as-small-image_0_ama__article-stub--small_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-article-stub-as-small-image_0_ama__article-stub--small_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-article-stub-as-small-image_0_ama__article-stub--small_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-article-stub-as-small-image_0_ama__article-stub--small_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-lead-news_0_ama__lead-news_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-lead-news_0_ama__lead-news_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-lead-news_0_ama__lead-news_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-lead-news_0_ama__lead-news_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-lead-news_0_ama__lead-news_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-sidebar-articles_0_ama__sidebar-articles_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-sidebar-articles_0_ama__sidebar-articles_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-sidebar-articles_0_ama__sidebar-articles_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-sidebar-articles_0_ama__sidebar-articles_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-sidebar-articles_0_ama__sidebar-articles_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_5_ama__lead-news_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_5_ama__lead-news_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_5_ama__lead-news_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_5_ama__lead-news_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_6_ama__sidebar-articles_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_6_ama__sidebar-articles_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_6_ama__sidebar-articles_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_6_ama__sidebar-articles_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_6_ama__sidebar-articles_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_7_ama__footer_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_7_ama__footer_2_bp-med.png
  styleguide/source/_patterns/02-molecules/article-stub.twig
  styleguide/source/assets/scss/02-molecules/_article-stub.scss
Labels: in review

#161 [EWL-4770] QA/EWL- 4512 SG2 | Replace "Inline Block copy" pattern with "Promo as Inline" variant
  styleguide/source/_patterns/02-molecules/inline-block-copy.json
  styleguide/source/_patterns/02-molecules/inline-block-copy.twig
  styleguide/source/_patterns/02-molecules/promo.json
  styleguide/source/_patterns/02-molecules/promo.twig
  styleguide/source/_patterns/02-molecules/promo~with-border.json
  styleguide/source/_patterns/02-molecules/promo~with-cta.json
  styleguide/source/_patterns/02-molecules/promo~with-image.json
  styleguide/source/assets/scss/02-molecules/_promo.scss
Labels: in review

#157 EWL-4678 - Initialize annotations
  styleguide/source/_annotations/article-stub-as-inline.md
  styleguide/source/_annotations/column-teaser.md
  styleguide/source/_annotations/inline-bio.md
  styleguide/source/_annotations/masthead.md
  styleguide/source/_annotations/membership.md
  styleguide/source/_annotations/news.md
  styleguide/source/_annotations/press-release.md
  styleguide/source/_annotations/tools-block.md
Labels: in review
