Repository AmericanMedicalAssociation/ama-style-guide-2, pull requests merged in 2018-06, with the labels that each got.

#277 [EWL-4926] Add temp masthead grid classes
  styleguide/source/assets/scss/03-organisms/_masthead.scss
Labels: has D8 dependency, in review, priority

#278 EWL-4657 - fix footer links
  styleguide/backstop_data/bitmaps_reference/backstop_default_event-page_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_event-page_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_event-page_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_event-page_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_event-page_0_document_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_event_listing_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_event_listing_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_event_listing_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_event_listing_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_event_listing_0_document_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-article-as-video_0_ama__article-stub--small_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-article-as-video_0_ama__article-stub--small_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news-with-jama-examples-page_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news-with-jama-examples-page_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news-with-jama-examples-page_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news-with-jama-examples-page_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news-with-jama-examples-page_0_document_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-footer_0_ama__footer_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-footer_0_ama__footer_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-footer_0_ama__footer_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-footer_0_ama__footer_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-footer_0_ama__footer_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release_0_document_0_bp-xs.png
  styleguide/source/assets/scss/03-organisms/_footer.scss
Labels: ok to merge

#280 EWL-5257 mobile filter button
  styleguide/backstop_data/bitmaps_reference/backstop_default_applied-filters_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_applied-filters_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_applied-filters_0_document_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_event_listing_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_event_listing_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-filter_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-filter_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-filter_0_document_4_bp-xl.png
  styleguide/source/_patterns/03-organisms/filter.twig
  styleguide/source/assets/js/form-items.js
Labels: in review

#279 EWL-5169 Fix checklist js error
  styleguide/build.config.json
Labels: has D8 dependency, question

#285 [EWL-5267] SG2 | Create "Category Page Hero" molecule
  styleguide/backstop.json
  styleguide/backstop_data/bitmaps_reference/backstop_default_category_hero_0_ama__category-hero_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_category_hero_0_ama__category-hero_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_category_hero_0_ama__category-hero_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_category_hero_0_ama__category-hero_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_category_hero_0_ama__category-hero_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-category-hero_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-category-hero_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-category-hero_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-category-hero_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-category-hero_0_document_4_bp-xl.png
  styleguide/source/_patterns/02-molecules/category-hero.json
  styleguide/source/_patterns/02-molecules/category-hero.twig
  styleguide/source/assets/scss/02-molecules/_category-hero.scss
  styleguide/source/assets/scss/02-molecules/category-hero.md
Labels: in review, priority

#281 [EWL-5045] Fix mobile load issue on Resources page
  styleguide/backstop_data/bitmaps_reference/backstop_default_resource_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_resource_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_resource_0_document_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_resource_tabs_0_ama__resource-tabs_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_resource_tabs_0_ama__resource-tabs_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_resource_tabs_0_ama__resource-tabs_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_resource_tabs_0_ama__resource-tabs_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_resource_tabs_0_ama__resource-tabs_4_bp-xl.png
  styleguide/source/_patterns/03-organisms/resource-tabs.twig
  styleguide/source/assets/scss/03-organisms/_resource-tabs.scss
Labels: ready for review

#288 EWL-5293 masthead with subtitle only
  styleguide/backstop_data/bitmaps_reference/backstop_default_event_listing_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_event_listing_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_event_listing_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_event_listing_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_event_listing_0_document_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_masthead_as_indented_0_ama__masthead_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_masthead_as_indented_0_ama__masthead_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_masthead_as_indented_0_ama__masthead_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_masthead_as_indented_0_ama__masthead_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_masthead_as_simplified_0_ama__masthead_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_masthead_as_simplified_0_ama__masthead_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_masthead_as_simplified_0_ama__masthead_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_masthead_as_simplified_0_ama__masthead_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_masthead_as_simplified_0_ama__masthead_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_masthead_default_0_ama__masthead_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_masthead_default_0_ama__masthead_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_masthead_default_0_ama__masthead_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_masthead_default_0_ama__masthead_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_masthead_with_subtitle_0_ama__masthead_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_masthead_with_subtitle_0_ama__masthead_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_masthead_with_subtitle_0_ama__masthead_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_masthead_with_subtitle_0_ama__masthead_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_masthead_with_subtitle_as_indented_0_ama__masthead_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_masthead_with_subtitle_as_indented_0_ama__masthead_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_masthead_with_subtitle_as_indented_0_ama__masthead_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_masthead_with_subtitle_as_indented_0_ama__masthead_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press_release_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press_release_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press_release_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press_release_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press_release_0_document_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_resource_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_resource_0_document_2_bp-med.png
  styleguide/source/_patterns/01-atoms/page-title.md
  styleguide/source/_patterns/03-organisms/masthead/masthead.md
  styleguide/source/_patterns/03-organisms/masthead/masthead.twig
  styleguide/source/_patterns/03-organisms/masthead/masthead~as-title-only.json
  styleguide/source/assets/scss/03-organisms/_masthead.scss
Labels: in review

#298 Add h4 purple, blue, white header and h5 purple header
  styleguide/source/assets/scss/00-base/_typography.scss
Labels: ready for review

#299 EWL-5273 article stub as large for category page
  styleguide/backstop.json
  styleguide/backstop_data/bitmaps_reference/backstop_default_article_stub_as_category_page_0_ama__article-stub_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_article_stub_as_category_page_0_ama__article-stub_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_article_stub_as_category_page_0_ama__article-stub_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_article_stub_as_category_page_0_ama__article-stub_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_article_stub_as_category_page_0_ama__article-stub_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_article_stub_as_category_page_Title_0_ama__article-stub_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_article_stub_as_category_page_Title_0_ama__article-stub_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_article_stub_as_category_page_Title_0_ama__article-stub_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_article_stub_as_category_page_Title_0_ama__article-stub_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_article_stub_as_category_page_Title_0_ama__article-stub_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_article_stub_as_category_page_with_Image_0_ama__article-stub_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_article_stub_as_category_page_with_Image_0_ama__article-stub_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_article_stub_as_category_page_with_Image_0_ama__article-stub_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_article_stub_as_category_page_with_Image_0_ama__article-stub_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_article_stub_as_category_page_with_Image_0_ama__article-stub_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_article_stub_for_category_page_0_ama__article-stub_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_article_stub_for_category_page_0_ama__article-stub_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_article_stub_for_category_page_0_ama__article-stub_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_article_stub_for_category_page_0_ama__article-stub_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_article_stub_for_category_page_0_ama__article-stub_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_article_stub_for_category_page_Title_0_ama__article-stub_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_article_stub_for_category_page_Title_0_ama__article-stub_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_article_stub_for_category_page_Title_0_ama__article-stub_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_article_stub_for_category_page_Title_0_ama__article-stub_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_article_stub_for_category_page_Title_0_ama__article-stub_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_article_stub_for_category_page_with_Image_0_ama__article-stub_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_article_stub_for_category_page_with_Image_0_ama__article-stub_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_article_stub_for_category_page_with_Image_0_ama__article-stub_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_article_stub_for_category_page_with_Image_0_ama__article-stub_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_article_stub_for_category_page_with_Image_0_ama__article-stub_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_visual_subcategory_exploration_with_images_0_ama__subcategory-exploration_1_bp-small.png
  styleguide/source/_patterns/02-molecules/article-stub/article-stub.twig
  styleguide/source/_patterns/02-molecules/article-stub/article-stub~for-category-page-title.json
  styleguide/source/_patterns/02-molecules/article-stub/article-stub~for-category-page-with-image.json
  styleguide/source/_patterns/02-molecules/article-stub/article-stub~for-category-page.json
  styleguide/source/assets/scss/02-molecules/_article-stub.scss
Labels: ready for review

#290 [EWL-5301] SG2 | Create "Subscribe Promo" Molecule (Cat/Subcat)
  styleguide/backstop.json
  styleguide/backstop_data/bitmaps_reference/backstop_default_subscribe_promo_0_ama__subscribe-promo_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_subscribe_promo_0_ama__subscribe-promo_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_subscribe_promo_0_ama__subscribe-promo_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_subscribe_promo_0_ama__subscribe-promo_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_subscribe_promo_0_ama__subscribe-promo_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_visual_subcategory_exploration_with_images_0_ama__subcategory-exploration_1_bp-small.png
  styleguide/source/_patterns/02-molecules/subscribe-promo.json
  styleguide/source/_patterns/02-molecules/subscribe-promo.md
  styleguide/source/_patterns/02-molecules/subscribe-promo.twig
  styleguide/source/assets/scss/02-molecules/_subscribe-promo.scss
Labels: in review, priority

#295 [EWL-5312] SG2 | Create "In-Body Search" molecule
  styleguide/backstop_data/bitmaps_reference/backstop_default_atoms_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_atoms_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_atoms_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_atoms_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_atoms_0_document_4_bp-xl.png
  styleguide/source/_patterns/01-atoms/forms/search-field-as-in-body.json
  styleguide/source/_patterns/01-atoms/forms/search-field-as-in-body.md
  styleguide/source/_patterns/01-atoms/forms/search-field-as-in-body.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-search-white.twig
  styleguide/source/assets/scss/01-atoms/_search-field.scss
Labels: in review, priority

#294 EWL-5303 subcategory exploration organism & EWL-5304 Create "Visual Subcategory" molecule
  styleguide/backstop_data/bitmaps_reference/backstop_default_visual_subcategory_0_ama__subcategory-exploration__subcategory_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_visual_subcategory_0_ama__subcategory-exploration__subcategory_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_visual_subcategory_0_ama__subcategory-exploration__subcategory_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_visual_subcategory_0_ama__subcategory-exploration__subcategory_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_visual_subcategory_exploration_with_images_0_ama__subcategory-exploration_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_visual_subcategory_exploration_with_images_0_ama__subcategory-exploration_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_visual_subcategory_exploration_with_images_0_ama__subcategory-exploration_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_visual_subcategory_exploration_with_images_0_ama__subcategory-exploration_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_visual_subcategory_exploration_with_images_0_ama__subcategory-exploration_4_bp-xl.png
  styleguide/source/_patterns/03-organisms/subcategory-exploration-as-with-images.json
  styleguide/source/_patterns/03-organisms/subcategory-exploration-as-with-images.twig
  styleguide/source/assets/js/subcategory.js
  styleguide/source/assets/scss/02-molecules/_visual-subcategory.scss
  styleguide/source/assets/scss/03-organisms/_subcategory-exploration-as-with-images.scss
Labels: in review

#302 [EWL-5311] SG2 | Create "Subcategory Page Hero Article" molecule
  styleguide/backstop.json
  styleguide/backstop_data/bitmaps_reference/backstop_default_subcategory_page_hero_0_ama__subcategory-hero_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_subcategory_page_hero_0_ama__subcategory-hero_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_subcategory_page_hero_0_ama__subcategory-hero_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_subcategory_page_hero_0_ama__subcategory-hero_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_subcategory_page_hero_0_ama__subcategory-hero_4_bp-xl.png
  styleguide/source/_patterns/02-molecules/subcategory-hero.json
  styleguide/source/_patterns/02-molecules/subcategory-hero.md
  styleguide/source/_patterns/02-molecules/subcategory-hero.twig
  styleguide/source/assets/scss/02-molecules/_subcategory-hero.scss
Labels: in review, priority

#304 [EWL-5302] SG2 | Create "Category Page Index" Organism
  styleguide/backstop.json
  styleguide/backstop_data/bitmaps_reference/backstop_default_category_index_0_ama__category-index_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_category_index_0_ama__category-index_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_category_index_0_ama__category-index_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_category_index_0_ama__category-index_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_category_index_0_ama__category-index_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_subcategory_page_article_stub_0_ama__subcategory-page-article-stub_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_subcategory_page_article_stub_0_ama__subcategory-page-article-stub_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_subcategory_page_article_stub_0_ama__subcategory-page-article-stub_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_subcategory_page_article_stub_0_ama__subcategory-page-article-stub_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_subcategory_page_article_stub_0_ama__subcategory-page-article-stub_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_subscribe_promo_0_ama__subscribe-promo_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_subscribe_promo_0_ama__subscribe-promo_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_subscribe_promo_0_ama__subscribe-promo_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_subscribe_promo_0_ama__subscribe-promo_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_subscribe_promo_0_ama__subscribe-promo_4_bp-xl.png
  styleguide/source/_patterns/03-organisms/category-index.json
  styleguide/source/_patterns/03-organisms/category-index.md
  styleguide/source/_patterns/03-organisms/category-index.twig
  styleguide/source/_patterns/04-templates/two-column-right-75-25.twig
  styleguide/source/assets/scss/00-base/_typography.scss
  styleguide/source/assets/scss/02-molecules/_subcategory-page-article-stub.scss
  styleguide/source/assets/scss/02-molecules/_subscribe-promo.scss
  styleguide/source/assets/scss/03-organisms/_category-index.scss
  styleguide/source/assets/scss/04-templates/_two-column-right--75-25.scss
Labels: in review, priority

#286 [EWL-5265] SG2 | Create "Subcategory Exploration" Organism
  styleguide/backstop.json
  styleguide/backstop_data/bitmaps_reference/backstop_default_subcategory_exploration_0_ama__subcategory-exploration_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_subcategory_exploration_0_ama__subcategory-exploration_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_subcategory_exploration_0_ama__subcategory-exploration_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_subcategory_exploration_0_ama__subcategory-exploration_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_subcategory_exploration_0_ama__subcategory-exploration_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_visual_subcategory_exploration_with_images_0_ama__subcategory-exploration-with-images_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_visual_subcategory_exploration_with_images_0_ama__subcategory-exploration-with-images_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_visual_subcategory_exploration_with_images_0_ama__subcategory-exploration-with-images_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_visual_subcategory_exploration_with_images_0_ama__subcategory-exploration-with-images_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_visual_subcategory_exploration_with_images_0_ama__subcategory-exploration-with-images_4_bp-xl.png
  styleguide/source/_patterns/03-organisms/subcategory-exploration-as-with-images.json
  styleguide/source/_patterns/03-organisms/subcategory-exploration-as-with-images.twig
  styleguide/source/_patterns/03-organisms/subcategory-exploration.json
  styleguide/source/_patterns/03-organisms/subcategory-exploration.md
  styleguide/source/_patterns/03-organisms/subcategory-exploration.twig
  styleguide/source/assets/js/subcategory-exploration.js
  styleguide/source/assets/scss/03-organisms/_subcategory-exploration-as-with-images.scss
  styleguide/source/assets/scss/03-organisms/_subcategory-exploration.scss
Labels: in review, priority

#305 [EWL-5285] SG2 | Create "Subcategory Featured Content" Organism
  styleguide/backstop.json
  styleguide/backstop_data/bitmaps_reference/backstop_default_error-page_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_error-page_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_error-page_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_error-page_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_error-page_0_document_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_promo_group_0_ama__promo-group_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_promo_group_0_ama__promo-group_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_promo_group_0_ama__promo-group_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_promo_group_0_ama__promo-group_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_promo_group_0_ama__promo-group_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_subcategory_featured_content_0_ama__subcategory-featured-content_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_subcategory_featured_content_0_ama__subcategory-featured-content_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_subcategory_featured_content_0_ama__subcategory-featured-content_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_subcategory_featured_content_0_ama__subcategory-featured-content_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_subcategory_featured_content_0_ama__subcategory-featured-content_4_bp-xl.png
  styleguide/source/_patterns/03-organisms/subcategory-featured-content.json
  styleguide/source/_patterns/03-organisms/subcategory-featured-content.md
  styleguide/source/_patterns/03-organisms/subcategory-featured-content.twig
  styleguide/source/assets/scss/00-base/__01.mixins/_layout_mixin.scss
  styleguide/source/assets/scss/03-organisms/_subcatecory-featured-content.scss
Labels: in review

#308 EWL-5369 Category article stub should not carousel
  styleguide/backstop_data/bitmaps_reference/backstop_default_category_page_article_stub_0_ama__category-page-article-stub_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_category_page_article_stub_0_ama__category-page-article-stub_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_category_page_article_stub_0_ama__category-page-article-stub_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_category_page_article_stub_0_ama__category-page-article-stub_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_category_page_article_stub_0_ama__category-page-article-stub_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_subcategory_featured_content_as_carousel_0_ama__subcategory-featured-content-as-carousel_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_subcategory_featured_content_as_carousel_0_ama__subcategory-featured-content-as-carousel_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_subcategory_featured_content_as_carousel_0_ama__subcategory-featured-content-as-carousel_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_subcategory_featured_content_as_carousel_0_ama__subcategory-featured-content-as-carousel_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_subcategory_featured_content_as_carousel_0_ama__subcategory-featured-content-as-carousel_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_visual_subcategory_exploration_with_images_0_ama__subcategory-exploration-with-images_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_visual_subcategory_exploration_with_images_0_ama__subcategory-exploration-with-images_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_visual_subcategory_exploration_with_images_0_ama__subcategory-exploration-with-images_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_visual_subcategory_exploration_with_images_0_ama__subcategory-exploration-with-images_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_visual_subcategory_exploration_with_images_0_ama__subcategory-exploration-with-images_4_bp-xl.png
  styleguide/source/_patterns/03-organisms/subcategory-featured-content-as-carousel.json
  styleguide/source/assets/js/category-carousel.js
  styleguide/source/assets/scss/03-organisms/_category-page-article-stub.scss
  styleguide/source/assets/scss/03-organisms/_subcategory-exploration-as-with-images.scss
  styleguide/source/assets/scss/vendor/_slick-carousel.scss
Labels: in review

#309 EWL-5371 make the prev and next arrow standalone
  styleguide/backstop_data/bitmaps_reference/backstop_default_subcategory_featured_content_as_carousel_0_ama__subcategory-featured-content-as-carousel_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_subcategory_featured_content_as_carousel_0_ama__subcategory-featured-content-as-carousel_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_subcategory_featured_content_as_carousel_0_ama__subcategory-featured-content-as-carousel_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_subcategory_featured_content_as_carousel_0_ama__subcategory-featured-content-as-carousel_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_subcategory_featured_content_as_carousel_0_ama__subcategory-featured-content-as-carousel_4_bp-xl.png
  styleguide/source/assets/js/category-carousel.js
  styleguide/source/assets/scss/vendor/_slick-carousel.scss
Labels: ready for review

#310 [EWL-5319] SG2 | Create "Subcategory" Page
  styleguide/source/_patterns/03-organisms/subcategory-index.json
  styleguide/source/_patterns/03-organisms/subcategory-index.twig
  styleguide/source/_patterns/05-pages/subcategory.json
  styleguide/source/_patterns/05-pages/subcategory.md
  styleguide/source/_patterns/05-pages/subcategory.twig
  styleguide/source/assets/scss/03-organisms/_subcategory-index.scss
Labels: ok to merge, priority

#306 [EWL-5310] SG2 | Create "Category Page" pattern
  styleguide/backstop.json
  styleguide/backstop_data/bitmaps_reference/backstop_default_category_hero_0_ama__category-hero_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_category_hero_0_ama__category-hero_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_category_hero_0_ama__category-hero_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_category_hero_0_ama__category-hero_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_category_hero_0_ama__category-hero_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_category_page_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_category_page_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_category_page_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_category_page_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_category_page_0_document_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_subcategory_featured_content_0_ama__subcategory-featured-content_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_visual_subcategory_exploration_with_images_0_ama__subcategory-exploration-with-images_1_bp-small.png
  styleguide/source/_patterns/02-molecules/category-hero.json
  styleguide/source/_patterns/02-molecules/jama/jama~as-content-bottom.json
  styleguide/source/_patterns/03-organisms/_category-article-three-up-jama.twig
  styleguide/source/_patterns/03-organisms/_category-article-two-up.twig
  styleguide/source/_patterns/03-organisms/_category-hero-tools.twig
  styleguide/source/_patterns/03-organisms/_category-jama-article-stub-as-large.twig
  styleguide/source/_patterns/05-pages/category.json
  styleguide/source/_patterns/05-pages/category.md
  styleguide/source/_patterns/05-pages/category.twig
  styleguide/source/assets/scss/03-organisms/_subcategory-exploration.scss
  styleguide/source/assets/scss/05-pages/_category.scss
Labels: in review, priority
