Repository AmericanMedicalAssociation/ama-style-guide-2, pull requests merged in 2018-05, with the labels that each got.

#190 [EWL-4630] - Add use cases
  styleguide/source/_patterns/02-molecules/article-stub-as-inline.md
  styleguide/source/_patterns/02-molecules/article-stub-metadata.md
  styleguide/source/_patterns/02-molecules/article-stub.md
  styleguide/source/_patterns/02-molecules/info-card.md
  styleguide/source/_patterns/02-molecules/inline-bio.md
  styleguide/source/_patterns/02-molecules/membership-with-cta.md
  styleguide/source/_patterns/02-molecules/membership.md
  styleguide/source/_patterns/02-molecules/partner-info.md
  styleguide/source/_patterns/02-molecules/press-release-logos.md
  styleguide/source/_patterns/02-molecules/promo.md
  styleguide/source/_patterns/02-molecules/ribbon-dropdown.md
  styleguide/source/_patterns/02-molecules/ribbon-user-menu.md
  styleguide/source/_patterns/02-molecules/social-share.md
  styleguide/source/_patterns/02-molecules/tags.md
  styleguide/source/_patterns/02-molecules/tool.md
  styleguide/source/_patterns/02-molecules/tools-learn-more.md
  styleguide/source/_patterns/02-molecules/tools-list.md
  styleguide/source/_patterns/03-organisms/column-teaser.md
  styleguide/source/_patterns/03-organisms/footer.md
  styleguide/source/_patterns/03-organisms/four-up-teaser.md
  styleguide/source/_patterns/03-organisms/lead-news.md
  styleguide/source/_patterns/03-organisms/masthead.md
  styleguide/source/_patterns/03-organisms/partner-list.md
  styleguide/source/_patterns/03-organisms/ribbon.md
  styleguide/source/_patterns/03-organisms/sidebar-articles.md
  styleguide/source/_patterns/03-organisms/tools.md
  styleguide/source/_patterns/03-organisms/wayfinder.md
Labels: in review

#212 [EWL-4928] - Add Table Atom
  styleguide/source/_patterns/01-atoms/table.json
  styleguide/source/_patterns/01-atoms/table.md
  styleguide/source/_patterns/01-atoms/table.twig
  styleguide/source/assets/js/tables.js
  styleguide/source/assets/scss/01-atoms/_table.scss
Labels: priority, ready for review

#217 [EWL-4934] SG2 | Correct tag detault and hover states
  styleguide/source/assets/scss/02-molecules/_tags.scss
Labels: in review

#215 switch out cat video
  styleguide/backstop_data/bitmaps_reference/backstop_default_resource_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_resource_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_resource_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_resource_0_document_4_bp-xl.png
  styleguide/source/_patterns/01-atoms/video.json
  styleguide/source/_patterns/05-pages/resource.json
Labels: priority, work in progress

#216 [EWL-4888] - Add gate to news
  styleguide/source/_patterns/01-atoms/gate.twig
  styleguide/source/_patterns/05-pages/news-as-gated.json
  styleguide/source/_patterns/05-pages/news-as-gated.twig
  styleguide/source/assets/js/gate.js
  styleguide/source/assets/scss/01-atoms/_gate.scss
  styleguide/source/assets/scss/04-templates/_two_column-right.scss
Labels: in review

#218 [EWL-4768] - Edit metadata for divider
  styleguide/source/_patterns/02-molecules/article-stub-metadata.twig
Labels: in review

#220 [EWL-4543] - Clean up footer
  styleguide/source/_patterns/03-organisms/footer.twig
  styleguide/source/assets/scss/01-atoms/_copyright.scss
  styleguide/source/assets/scss/03-organisms/_footer.scss
Labels: in review

#219 EWL-4995 hub cards and hub heros
  styleguide/backstop.json
  styleguide/backstop_data/bitmaps_reference/backstop_default_atoms-form-elements_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_atoms-form-elements_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_atoms-form-elements_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_atoms-form-elements_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_atoms-form-elements_0_document_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-form_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-form_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-hub-cards_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-hub-cards_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-hub-cards_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-hub-cards_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-hub-cards_0_document_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-tools-block_0_ama__tools_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-tools-block_0_ama__tools_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-tools-block_0_ama__tools_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-tools-block_0_ama__tools_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-tools-block_0_ama__tools_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_templates-split_0_ama__layout--split_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_templates-split_0_ama__layout--split_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_templates-split_0_ama__layout--split_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_templates-split_0_ama__layout--split_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_2_ama__tools_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_2_ama__tools_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_2_ama__tools_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_2_ama__tools_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_2_ama__tools_4_bp-xl.png
  styleguide/source/_patterns/01-atoms/button.json
  styleguide/source/_patterns/02-molecules/hub/hub-card.json
  styleguide/source/_patterns/02-molecules/hub/hub-card.md
  styleguide/source/_patterns/02-molecules/hub/hub-card.twig
  styleguide/source/_patterns/02-molecules/hub/hub-card~as-portrait.json
  styleguide/source/_patterns/02-molecules/hub/hub-card~with-no-image.json
  styleguide/source/_patterns/02-molecules/hub/hub-card~with-select.json
  styleguide/source/_patterns/02-molecules/hub/hub-hero.json
  styleguide/source/_patterns/02-molecules/hub/hub-hero.md
  styleguide/source/_patterns/02-molecules/hub/hub-hero.twig
  styleguide/source/_patterns/02-molecules/hub/hub-hero~as-cta-only.json
  styleguide/source/_patterns/02-molecules/hub/hub-hero~as-fifty-fifty-left.json
  styleguide/source/_patterns/02-molecules/hub/hub-hero~as-fifty-fifty-video.json
  styleguide/source/_patterns/02-molecules/hub/hub-hero~as-fifty-fifty.json
  styleguide/source/_patterns/02-molecules/hub/hub-hero~as-hero-side.json
  styleguide/source/_patterns/02-molecules/hub/hub-hero~as-side-right.json
  styleguide/source/_patterns/02-molecules/hub/hub-hero~as-split-no-overlay.json
  styleguide/source/_patterns/02-molecules/hub/hub-hero~as-split.json
  styleguide/source/_patterns/03-organisms/hub-cards.json
  styleguide/source/_patterns/03-organisms/hub-cards.twig
  styleguide/source/_patterns/05-pages/hub.json
  styleguide/source/_patterns/05-pages/hub.twig
  styleguide/source/assets/scss/02-molecules/_hub-card.scss
  styleguide/source/assets/scss/02-molecules/_hub-hero.scss
Labels: ready for review

#223 EWL-4866 SG2 | Correct Markup for Tools Block on Topic Page
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-tools-block_0_ama__tools_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-tools-block_0_ama__tools_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-tools-block_0_ama__tools_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-tools-block_0_ama__tools_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-tools-block_0_ama__tools_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_2_ama__tools_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_2_ama__tools_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_2_ama__tools_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_2_ama__tools_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_2_ama__tools_4_bp-xl.png
  styleguide/source/_patterns/03-organisms/tools.json
  styleguide/source/_patterns/05-pages/topic.json
Labels: in review

#222 EWL-5004: Remove generic svg style breaking layout builder icons
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-footer_0_ama__footer_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-footer_0_ama__footer_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-footer_0_ama__footer_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-footer_0_ama__footer_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-footer_0_ama__footer_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_7_ama__footer_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_7_ama__footer_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_7_ama__footer_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_7_ama__footer_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_7_ama__footer_4_bp-xl.png
  styleguide/source/_patterns/01-atoms/unordered-list.json
  styleguide/source/assets/scss/01-atoms/_links.scss
  styleguide/source/assets/scss/01-atoms/_multiselect.scss
  styleguide/source/assets/scss/01-atoms/_unordered-list.scss
  styleguide/source/assets/scss/02-molecules/_inline-bio.scss
Labels: ready for review

#221 EWL-4879 hub pages
  styleguide/backstop.json
  styleguide/backstop_data/bitmaps_reference/backstop_default_atoms-form-elements_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_atoms-form-elements_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_atoms-form-elements_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_atoms-form-elements_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_atoms-form-elements_0_document_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_hub-page_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_hub-page_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_hub-page_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_hub-page_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_hub-page_0_document_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-hub-cards_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-hub-cards_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-hub-cards_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-hub-cards_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-hub-cards_0_document_4_bp-xl.png
  styleguide/source/_patterns/02-molecules/hub/hub-section-header.json
  styleguide/source/_patterns/02-molecules/hub/hub-section-header.md
  styleguide/source/_patterns/02-molecules/hub/hub-section-header.twig
  styleguide/source/_patterns/03-organisms/hub-cards.json
  styleguide/source/_patterns/03-organisms/hub-cards.twig
  styleguide/source/_patterns/03-organisms/hub-heroes.json
  styleguide/source/_patterns/03-organisms/hub-heroes.twig
  styleguide/source/_patterns/05-pages/hub.json
  styleguide/source/_patterns/05-pages/hub.md
  styleguide/source/_patterns/05-pages/hub.twig
  styleguide/source/assets/scss/02-molecules/_hub-card.scss
  styleguide/source/assets/scss/02-molecules/hub/_hub-card-row.scss
  styleguide/source/assets/scss/02-molecules/hub/_hub-card.scss
  styleguide/source/assets/scss/02-molecules/hub/_hub-hero-row.scss
  styleguide/source/assets/scss/02-molecules/hub/_hub-hero.scss
  styleguide/source/assets/scss/02-molecules/hub/_hub-section-header.scss
  styleguide/source/assets/scss/03-organisms/_hub-row.scss
Labels: ready for review

#226 [EWL-4936] Resource page cleanups
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-facebook-gray-hover.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-facebook-gray.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-googleplus-gray-hover.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-googleplus-gray.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-linkedin-gray-hover.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-linkedin-gray.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-twitter-gray-hover.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-twitter-gray.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-youtube-gray-hover.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-youtube-gray.twig
  styleguide/source/_patterns/03-organisms/resource-tabs.twig
  styleguide/source/_patterns/05-pages/resource.json
  styleguide/source/_patterns/05-pages/resource.twig
  styleguide/source/assets/icons/svg/icon-facebook-gray-hover.svg
  styleguide/source/assets/icons/svg/icon-facebook-gray.svg
  styleguide/source/assets/icons/svg/icon-googleplus-gray-hover.svg
  styleguide/source/assets/icons/svg/icon-googleplus-gray.svg
  styleguide/source/assets/icons/svg/icon-linkedin-gray-hover.svg
  styleguide/source/assets/icons/svg/icon-linkedin-gray.svg
  styleguide/source/assets/icons/svg/icon-twitter-gray-hover.svg
  styleguide/source/assets/icons/svg/icon-twitter-gray.svg
  styleguide/source/assets/icons/svg/icon-youtube-gray-hover.svg
  styleguide/source/assets/icons/svg/icon-youtube-gray.svg
  styleguide/source/assets/scss/02-molecules/_resource-link-as-inline.scss
  styleguide/source/assets/scss/02-molecules/_social-share.scss
  styleguide/source/assets/scss/03-organisms/_resource-tabs.scss
  styleguide/source/assets/scss/04-templates/_split.scss
Labels: merge conflict, priority

#232 [EWL-5047] -- Fix visual regressions
  styleguide/source/_patterns/05-pages/news.json
  styleguide/source/_patterns/05-pages/topic.json
  styleguide/source/assets/scss/02-molecules/_article-stub.scss
  styleguide/source/assets/scss/02-molecules/_tool.scss
  styleguide/source/assets/scss/02-molecules/_tools-learn-more.scss
  styleguide/source/assets/scss/03-organisms/_membership.scss
Labels: ready for review

#228 EWL-5011 node security vulnerabilities patch
  package-lock.json
  styleguide/package-lock.json
  styleguide/package.json
Labels: ready for review

#235 [EWL-4612] SG2 | Create Information Card as Speaker variant
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-info-card-as-event-speaker_0_ama__info-card_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-info-card-as-event-speaker_0_ama__info-card_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-info-card-as-event-speaker_0_ama__info-card_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-info-card-as-event-speaker_0_ama__info-card_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-info-card-as-event-speaker_0_ama__info-card_4_bp-xl.png
  styleguide/source/_patterns/02-molecules/info-card-as-event-speaker.md
  styleguide/source/_patterns/02-molecules/info-card.twig
  styleguide/source/_patterns/02-molecules/info-card~as-event-speaker.json
  styleguide/source/assets/scss/02-molecules/_info-card.scss
Labels: in review, priority

#236 [EWL-5062] SG2 | Correct Article Stub Metadata
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release_0_document_1_bp-small.png
  styleguide/source/_patterns/02-molecules/article-stub.json
  styleguide/source/_patterns/02-molecules/article-stub.md
  styleguide/source/_patterns/02-molecules/article-stub.twig
  styleguide/source/_patterns/03-organisms/four-up-teaser.json
Labels: in review, priority

#237 [EWL-4613] SG2 | Create Information Card as Location variant
  styleguide/backstop.json
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-info-card-as-location_0_ama__info-card_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-info-card-as-location_0_ama__info-card_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-info-card-as-location_0_ama__info-card_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-info-card-as-location_0_ama__info-card_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-info-card-as-location_0_ama__info-card_4_bp-xl.png
  styleguide/source/_patterns/01-atoms/map.json
  styleguide/source/_patterns/01-atoms/map.md
  styleguide/source/_patterns/01-atoms/map.twig
  styleguide/source/_patterns/02-molecules/info-card-as-location.md
  styleguide/source/_patterns/02-molecules/info-card.twig
  styleguide/source/_patterns/02-molecules/info-card~as-location.json
  styleguide/source/assets/scss/02-molecules/_info-card.scss
Labels: in review, priority

#238 EWL-5077 - Add engine scripts to backstop
  styleguide/backstop.json
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-info-card-as-contact_0_ama__info-card--contact_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-tools-block_0_ama__tools_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-tools-block_0_ama__tools_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-tools-block_0_ama__tools_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-tools-block_0_ama__tools_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-tools-block_0_ama__tools_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release-logos_0_ama__press-release__logos_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_resource_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_resource_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_resource_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_resource_0_document_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_templates-split_0_ama__layout--split_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_templates-split_0_ama__layout--split_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_templates-split_0_ama__layout--split_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_templates-split_0_ama__layout--split_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_0_document_4_bp-xl.png
  styleguide/backstop_data/engine_scripts/casper/clickAndHoverHelper.js
  styleguide/backstop_data/engine_scripts/casper/loadCookies.js
  styleguide/backstop_data/engine_scripts/casper/onBefore.js
  styleguide/backstop_data/engine_scripts/casper/onReady.js
  styleguide/backstop_data/engine_scripts/casper/waitForHelperHelper.js
  styleguide/backstop_data/engine_scripts/chromy/clickAndHoverHelper.js
  styleguide/backstop_data/engine_scripts/chromy/loadCookies.js
  styleguide/backstop_data/engine_scripts/chromy/onBefore.js
  styleguide/backstop_data/engine_scripts/chromy/onReady.js
  styleguide/backstop_data/engine_scripts/cookies.json
  styleguide/backstop_data/engine_scripts/onBefore.js
  styleguide/backstop_data/engine_scripts/onReady.js
  styleguide/package-lock.json
  styleguide/package.json
Labels: in review, priority

#241 [EWL-5031] SG2 | Create site logo as JAMA atom
  styleguide/source/_patterns/01-atoms/site-logo-as-jama.md
  styleguide/source/_patterns/01-atoms/site-logo-as-jama.twig
  styleguide/source/assets/images/brand/logo-jama.svg
Labels: in review, priority

#224 do drupal deploy during release
  styleguide/gulpfile.js
Labels: in review, priority, ready for review

#242 EWL-4595 - Add checkbox filter atom
  styleguide/backstop_data/bitmaps_reference/backstop_default_atoms-form-elements_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_atoms-form-elements_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_atoms-form-elements_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_atoms-form-elements_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_atoms-form-elements_0_document_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_0_document_4_bp-xl.png
  styleguide/source/_patterns/01-atoms/forms/checkbox.twig
  styleguide/source/_patterns/01-atoms/forms/checkbox~as-filter.json
Labels: in review

#245 [EWL-4610] SG2 | Create Agenda Table Molecule
  styleguide/backstop.json
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-agenda-table_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-agenda-table_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-agenda-table_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-agenda-table_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-agenda-table_0_document_4_bp-xl.png
  styleguide/source/_patterns/02-molecules/agenda-table.json
  styleguide/source/_patterns/02-molecules/agenda-table.md
  styleguide/source/_patterns/02-molecules/agenda-table.twig
  styleguide/source/assets/scss/02-molecules/_agenda-table.scss
Labels: in review, priority

#239 [EWL-4600/4601 - Add search header
  styleguide/backstop.json
  styleguide/backstop_data/bitmaps_reference/backstop_default_atoms-search-field_0_ama__search_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_atoms-search-field_0_ama__search_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_atoms-search-field_0_ama__search_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_atoms-search-field_0_ama__search_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_atoms-search-field_0_ama__search_4_bp-xl.png
  styleguide/source/_patterns/01-atoms/forms/search-field.json
  styleguide/source/_patterns/01-atoms/forms/search-field.md
  styleguide/source/_patterns/01-atoms/forms/search-field.twig
  styleguide/source/_patterns/02-molecules/search-header.json
  styleguide/source/_patterns/02-molecules/search-header.md
  styleguide/source/_patterns/02-molecules/search-header.twig
  styleguide/source/assets/scss/00-base/_colors.scss
  styleguide/source/assets/scss/01-atoms/_search-field.scss
  styleguide/source/assets/scss/02-molecules/_search-header.scss
Labels: in review

#249 EWL-4593 create filter list && EWL-4598 create filter list with search
  styleguide/build.config.json
  styleguide/source/_patterns/02-molecules/filter-list-as-search-filter.md
  styleguide/source/_patterns/02-molecules/filter-list-as-search-filter.twig
  styleguide/source/_patterns/02-molecules/filter-list.twig
  styleguide/source/assets/js/form-items.js
  styleguide/source/assets/js/vendor/jquery.ui.checkList.js
  styleguide/source/assets/scss/02-molecules/_filter-list.scss
  styleguide/source/assets/scss/02-molecules/_filters-list-as-search-filter.scss
Labels: in review

#250 [EWL-4603] - Add Pagination
  styleguide/backstop.json
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-pagination_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-pagination_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-pagination_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-pagination_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-pagination_0_document_4_bp-xl.png
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-arrow-left.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-arrow-right.twig
  styleguide/source/_patterns/02-molecules/pagination.json
  styleguide/source/_patterns/02-molecules/pagination.md
  styleguide/source/_patterns/02-molecules/pagination.twig
  styleguide/source/assets/icons/svg/icon-arrow-left.svg
  styleguide/source/assets/icons/svg/icon-arrow-right.svg
  styleguide/source/assets/scss/00-base/__01.mixins/_layout_mixin.scss
  styleguide/source/assets/scss/02-molecules/_pagination.scss
Labels: in review

#248 [EWL-4611] SG2 | Create Agenda Molecule
  styleguide/backstop.json
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-agenda_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-agenda_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-agenda_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-agenda_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-agenda_0_document_4_bp-xl.png
  styleguide/source/_patterns/02-molecules/agenda.json
  styleguide/source/_patterns/02-molecules/agenda.md
  styleguide/source/_patterns/02-molecules/agenda.twig
  styleguide/source/assets/js/tabs.js
  styleguide/source/assets/scss/01-atoms/_agenda-dates.scss
  styleguide/source/assets/scss/01-atoms/_tabs.scss
Labels: in review

#225 EWL-5004: Radio button contains a checkmark
  styleguide/source/assets/scss/01-atoms/_radio-button.scss
Labels: in review

#251 EWL-4577 Create applied filters molecule
  styleguide/backstop.json
  styleguide/backstop_data/bitmaps_reference/backstop_default_applied-filters_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_applied-filters_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_applied-filters_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_applied-filters_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_applied-filters_0_document_4_bp-xl.png
  styleguide/source/_patterns/02-molecules/applied-filters.json
  styleguide/source/_patterns/02-molecules/applied-filters.md
  styleguide/source/_patterns/02-molecules/applied-filters.twig
  styleguide/source/assets/js/form-items.js
  styleguide/source/assets/scss/02-molecules/_applied_filters.scss
Labels: in review

#252 EWL-4594 Create event listing page
  styleguide/backstop.json
  styleguide/backstop_data/bitmaps_reference/backstop_default_event_listing_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_event_listing_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_event_listing_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_event_listing_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_event_listing_0_document_4_bp-xl.png
  styleguide/source/_patterns/05-pages/event-listing.json
  styleguide/source/_patterns/05-pages/event-listing.twig
Labels: in review

#253 [EWL-4602] - Page Event List and Search header
  styleguide/backstop.json
  styleguide/backstop_data/bitmaps_reference/backstop_default_atoms-search-field_0_ama__search__field_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_atoms-search-field_0_ama__search__field_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_atoms-search-field_0_ama__search__field_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_atoms-search-field_0_ama__search__field_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_atoms-search-field_0_ama__search__field_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_event_listing_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_event_listing_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_event_listing_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-search-header_0_ama__search-header_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-search-header_0_ama__search-header_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-search-header_0_ama__search-header_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-search-header_0_ama__search-header_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-search-header_0_ama__search-header_4_bp-xl.png
  styleguide/source/_patterns/01-atoms/forms/search-field.twig
  styleguide/source/_patterns/02-molecules/search-header.json
  styleguide/source/_patterns/02-molecules/search-header.twig
  styleguide/source/_patterns/05-pages/event-listing.json
  styleguide/source/_patterns/05-pages/event-listing.twig
  styleguide/source/assets/scss/01-atoms/_search-field.scss
  styleguide/source/assets/scss/02-molecules/_search-header.scss
Labels: in review

#258 HOTFIX: typo in markup section -- Code review only
  styleguide/source/_patterns/02-molecules/search-header.twig
Labels: priority, ready for review

#257 [EWL-5041] SG2 | Create "JAMA as 3 Up" variant
  styleguide/backstop.json
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-jama-as-three-up_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-jama-as-three-up_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-jama-as-three-up_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-jama-as-three-up_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-jama-as-three-up_0_document_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news-with-jama-examples-page_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news-with-jama-examples-page_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news-with-jama-examples-page_0_document_4_bp-xl.png
  styleguide/source/_patterns/02-molecules/jama-as-content-bottom.md
  styleguide/source/_patterns/02-molecules/jama-as-three-up.md
  styleguide/source/_patterns/02-molecules/jama.md
  styleguide/source/_patterns/02-molecules/jama~as-three-up.json
  styleguide/source/_patterns/05-pages/news-as-gated.twig
  styleguide/source/_patterns/05-pages/news-with-jama-examples.json
  styleguide/source/_patterns/05-pages/news-with-jama-examples.twig
  styleguide/source/_patterns/05-pages/news.twig
  styleguide/source/_patterns/05-pages/press-release.twig
  styleguide/source/assets/scss/02-molecules/_jama.scss
Labels: priority, question

#261 [EWL-5119] SG2 | Resolve Backstop images for masthead
  styleguide/backstop_data/bitmaps_reference/backstop_default_event-page_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_event-page_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_event-page_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_event-page_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_event-page_0_document_4_bp-xl.png
Labels: in review

#260 [EWL-5113] SG2 | Correct info card as speaker alignment
  styleguide/backstop.json
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-info-card-as-event-speaker_0_ama__info-card_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-info-card-as-event-speaker_0_ama__info-card_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-info-card-as-event-speaker_0_ama__info-card_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-info-card-as-event-speaker_0_ama__info-card_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-info-card-as-event-speaker_0_ama__info-card_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-event-speakers_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-event-speakers_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-event-speakers_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-event-speakers_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-event-speakers_0_document_4_bp-xl.png
  styleguide/source/_patterns/03-organisms/event-speakers.json
  styleguide/source/_patterns/03-organisms/event-speakers.twig
  styleguide/source/assets/scss/02-molecules/_info-card.scss
  styleguide/source/assets/scss/03-organisms/_event-speakers.scss
Labels: in review, priority

#259 EWL-4594 Create filter organism
  styleguide/backstop.json
  styleguide/backstop_data/bitmaps_reference/backstop_default_applied-filters_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_applied-filters_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_applied-filters_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_applied-filters_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_applied-filters_0_document_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_expand-list_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_expand-list_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_expand-list_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_expand-list_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_expand-list_0_document_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-filtes_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-filtes_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-filtes_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-filtes_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-filtes_0_document_4_bp-xl.png
  styleguide/source/_patterns/01-atoms/forms/checkbox~as-filter.json
  styleguide/source/_patterns/02-molecules/applied-filters.json
  styleguide/source/_patterns/02-molecules/applied-filters.twig
  styleguide/source/_patterns/03-organisms/filter.json
  styleguide/source/_patterns/03-organisms/filter.md
  styleguide/source/_patterns/03-organisms/filter.twig
  styleguide/source/_patterns/04-templates/two-column-left.twig
  styleguide/source/_patterns/05-pages/event-listing.json
  styleguide/source/_patterns/05-pages/event-listing.twig
  styleguide/source/assets/js/form-items.js
  styleguide/source/assets/scss/01-atoms/_multiselect.scss
  styleguide/source/assets/scss/02-molecules/_applied_filters.scss
  styleguide/source/assets/scss/03-organisms/_filter.scss
  styleguide/source/assets/scss/04-templates/_two_column-left.scss
Labels: in review, priority

#262 SG2 | Update templates dependent on old info card as speaker
  styleguide/source/_patterns/03-organisms/page-content-tabs.json
  styleguide/source/_patterns/03-organisms/page-content-tabs.twig
  styleguide/source/_patterns/05-pages/event.json
Labels: in review

#264 Add pagination to the event listing page.
  styleguide/source/_patterns/05-pages/event-listing.json
  styleguide/source/_patterns/05-pages/event-listing.twig
Labels: ok to merge

#263 [EWL-5115] SG2 | Fix broken Two Col Right Template
  styleguide/backstop_data/bitmaps_reference/backstop_default_news-with-jama-examples-page_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news-with-jama-examples-page_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news-with-jama-examples-page_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news-with-jama-examples-page_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news-with-jama-examples-page_0_document_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release_0_document_4_bp-xl.png
  styleguide/source/_patterns/04-templates/two-column-right.twig
Labels: priority, ready for review

#265 [EWL-5118] SG2 | Review and resolve Backstop Reference and Chromy errors
  styleguide/backstop.json
  styleguide/backstop_data/bitmaps_reference/backstop_default_atoms-form-elements_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_atoms-form-elements_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_atoms-form-elements_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_atoms-form-elements_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_atoms-form-elements_0_document_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_atoms-search-field_0_ama__search__field_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_atoms-search-field_0_ama__search__field_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_atoms-search-field_0_ama__search__field_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_atoms-search-field_0_ama__search__field_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_atoms-search-field_0_ama__search__field_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_event_listing_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_event_listing_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_event_listing_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_event_listing_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_event_listing_0_document_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-promo-with-border_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-promo-with-border_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-promo-with-border_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-promo-with-border_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-promo-with-border_0_document_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-promo-with-cta_0_ama__promo--background_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-promo-with-cta_0_ama__promo--background_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-promo-with-cta_0_ama__promo--background_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-promo-with-cta_0_ama__promo--background_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-promo-with-cta_0_ama__promo--background_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-promo_0_ama__promo--background_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-promo_0_ama__promo--background_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-promo_0_ama__promo--background_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-promo_0_ama__promo--background_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-promo_0_ama__promo--background_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-search-header_0_ama__search-header_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-search-header_0_ama__search-header_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-search-header_0_ama__search-header_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-search-header_0_ama__search-header_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-search-header_0_ama__search-header_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-filter_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-filter_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-filter_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-filter_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-filter_0_document_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release-logos_0_ama__press-release__logos_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_templates-two-column-left_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_templates-two-column-left_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_templates-two-column-left_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_templates-two-column-left_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_templates-two-column-left_0_document_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_templates-two-column-right_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_templates-two-column-right_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_templates-two-column-right_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_templates-two-column-right_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_templates-two-column-right_0_document_4_bp-xl.png
  styleguide/source/assets/scss/01-atoms/_checkbox.scss
Labels: in review, ready for review

#272 EWL-4609 fix agenda date atom border width and tab jumping
  styleguide/backstop_data/bitmaps_reference/backstop_default_atoms-search-field_0_ama__search__field_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_atoms-search-field_0_ama__search__field_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_atoms-search-field_0_ama__search__field_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_atoms-search-field_0_ama__search__field_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_atoms-search-field_0_ama__search__field_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-agenda-table_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-agenda-table_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-agenda-table_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-agenda-table_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-agenda-table_0_document_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-agenda_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-agenda_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-agenda_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-agenda_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-agenda_0_document_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-search-header_0_ama__search-header_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-search-header_0_ama__search-header_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-search-header_0_ama__search-header_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-search-header_0_ama__search-header_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-search-header_0_ama__search-header_4_bp-xl.png
  styleguide/source/assets/js/tabs.js
  styleguide/source/assets/scss/02-molecules/_agenda-table.scss
Labels: ready for review

#267 [EWL-5126] SG2 | Correct pagination link color and add padding
  styleguide/backstop_data/bitmaps_reference/backstop_default_event_listing_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_event_listing_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_event_listing_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_event_listing_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_event_listing_0_document_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-pagination_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-pagination_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-pagination_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-pagination_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-pagination_0_document_4_bp-xl.png
  styleguide/source/assets/scss/02-molecules/_pagination.scss
Labels: in review

#274 [EWL-5039, EWL-5040, EWL-5041] SG2 | Changes to JAMA components
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-jama-as-content-bottom_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-jama-as-content-bottom_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-jama-as-content-bottom_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-jama-as-content-bottom_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-jama-as-content-bottom_0_document_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-jama-as-three-up_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-jama-as-three-up_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-jama-as-three-up_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-jama-as-three-up_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-jama-as-three-up_0_document_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-jama_0_ama__jama_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-jama_0_ama__jama_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-jama_0_ama__jama_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-jama_0_ama__jama_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-jama_0_ama__jama_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news-with-jama-examples-page_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news-with-jama-examples-page_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news-with-jama-examples-page_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news-with-jama-examples-page_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news-with-jama-examples-page_0_document_4_bp-xl.png
  styleguide/source/_patterns/01-atoms/image.twig
  styleguide/source/_patterns/01-atoms/image~href-with-text.json
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-podcast-black.twig
  styleguide/source/_patterns/01-atoms/site-logo-as-jama.twig
  styleguide/source/_patterns/02-molecules/jama.json
  styleguide/source/_patterns/02-molecules/jama.md
  styleguide/source/_patterns/02-molecules/jama.twig
  styleguide/source/_patterns/05-pages/news-with-jama-examples.json
  styleguide/source/assets/icons/svg/icon-podcast-black.svg
  styleguide/source/assets/scss/01-atoms/_icons.scss
  styleguide/source/assets/scss/01-atoms/_links.scss
  styleguide/source/assets/scss/02-molecules/_jama.scss
Labels: in review, priority

#276 EWL-4593 remove applied filters
  styleguide/backstop_data/bitmaps_reference/backstop_default_event_listing_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_event_listing_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_event_listing_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_event_listing_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_event_listing_0_document_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-article-as-video_0_ama__article-stub--small_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-filter_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-filter_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-filter_0_document_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-footer_0_ama__footer_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-footer_0_ama__footer_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-footer_0_ama__footer_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-footer_0_ama__footer_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-footer_0_ama__footer_4_bp-xl.png
  styleguide/source/_patterns/03-organisms/filter.twig
Labels: ready for review

#268 EWL-5147 - add purple and blue h4
  styleguide/source/_patterns/03-organisms/lead-news.json
  styleguide/source/assets/scss/00-base/__01.mixins/_font-variables.scss
  styleguide/source/assets/scss/02-molecules/_article-stub.scss
  styleguide/source/assets/scss/02-molecules/_lead-news.scss
Labels: ready for review

#275 EWL-4600 search filter
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-article-as-video_0_ama__article-stub--small_4_bp-xl.png
  styleguide/source/_patterns/01-atoms/forms/search-field.json
  styleguide/source/_patterns/01-atoms/forms/search-field.twig
  styleguide/source/_patterns/02-molecules/expand-list.json
  styleguide/source/_patterns/02-molecules/expand-list.twig
  styleguide/source/_patterns/02-molecules/search-header.json
  styleguide/source/_patterns/03-organisms/filter.json
  styleguide/source/_patterns/03-organisms/filter.twig
  styleguide/source/_patterns/05-pages/event-listing.json
  styleguide/source/assets/js/form-items.js
  styleguide/source/assets/scss/01-atoms/_search-field.scss
  styleguide/source/assets/scss/02-molecules/_applied_filters.scss
  styleguide/source/assets/scss/02-molecules/_expand-list.scss
Labels: ready for review
