Repository AmericanMedicalAssociation/ama-style-guide-2, pull requests merged in 2018-02, with the labels that each got.

#87 EWL-4466: Topics page creation in Patternlab
  styleguide/backstop.json
  styleguide/backstop_data/bitmaps_reference/backstop_default_atoms-button_0_ama__button_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_atoms-button_0_ama__button_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_atoms-button_0_ama__button_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_atoms-button_0_ama__button_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_atoms-button_0_ama__button_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_atoms-button_0_sg-viewport_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_atoms-button_0_sg-viewport_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_atoms-button_0_sg-viewport_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_atoms-button_0_sg-viewport_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_atoms-button_0_sg-viewport_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_atoms-subtitle_0_ama__subtitle_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_atoms-subtitle_0_ama__subtitle_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_atoms-subtitle_0_ama__subtitle_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_atoms-subtitle_0_ama__subtitle_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_atoms-subtitle_0_ama__subtitle_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_atoms-subtitle_0_sg-viewport_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_atoms-subtitle_0_sg-viewport_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_atoms-subtitle_0_sg-viewport_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_atoms-subtitle_0_sg-viewport_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_atoms-subtitle_0_sg-viewport_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release-logos_0_press-release-logos_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release-logos_0_press-release-logos_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release-logos_0_press-release-logos_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release-logos_0_press-release-logos_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release-logos_0_press-release-logos_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_0_document_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_0_sg-viewport_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_0_sg-viewport_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_0_sg-viewport_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_0_sg-viewport_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_0_sg-viewport_4_bp-xl.png
  styleguide/source/_patterns/05-pages/topic.json
  styleguide/source/_patterns/05-pages/topic.twig
  styleguide/source/assets/scss/04-templates/_three_column.scss
Labels: in review

#90 EWL-4537: Create and Populate contentTop region on the Topics page and update Three column layout template
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_0_document_4_bp-xl.png
  styleguide/source/_patterns/04-templates/three-column.twig
  styleguide/source/_patterns/04-templates/two-column-right.twig
  styleguide/source/_patterns/05-pages/topic.json
  styleguide/source/_patterns/05-pages/topic.twig
  styleguide/source/assets/scss/04-templates/_three_column.scss
  styleguide/source/assets/scss/04-templates/_two_column-right.scss
Labels: ready for review

#83 EWL-4504: SG2 | Reuse components for Press Release
  styleguide/backstop.json
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release-page_0_sg-viewport_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release-page_0_sg-viewport_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release-page_0_sg-viewport_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release-page_0_sg-viewport_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release-page_0_sg-viewport_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release_0_document_4_bp-xl.png
  styleguide/source/_patterns/05-pages/press-release.json
  styleguide/source/_patterns/05-pages/press-release.twig
Labels: question

#93 EWL-4525: Tools organism padding and text styles tweaks
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release_0_document_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_0_document_4_bp-xl.png
  styleguide/source/_patterns/02-molecules/tools-learn-more.json
  styleguide/source/assets/scss/02-molecules/_tool.scss
Labels: in review

#86 [EWL-4485] SG2 | Update "Masthead" Organism and Add "with Subtitle" variant
  styleguide/backstop.json
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-masthead-with-subtitle_0_ama__masthead_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-masthead-with-subtitle_0_ama__masthead_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-masthead-with-subtitle_0_ama__masthead_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-masthead-with-subtitle_0_ama__masthead_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-masthead-with-subtitle_0_ama__masthead_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-masthead-with-subtitle_0_sg-viewport_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-masthead-with-subtitle_0_sg-viewport_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-masthead-with-subtitle_0_sg-viewport_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-masthead-with-subtitle_0_sg-viewport_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-masthead-with-subtitle_0_sg-viewport_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-masthead_0_ama__masthead_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-masthead_0_ama__masthead_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-masthead_0_ama__masthead_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-masthead_0_ama__masthead_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-masthead_0_ama__masthead_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-masthead_0_sg-viewport_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-masthead_0_sg-viewport_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-masthead_0_sg-viewport_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-masthead_0_sg-viewport_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-masthead_0_sg-viewport_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release_0_document_4_bp-xl.png
  styleguide/source/_patterns/01-atoms/subtitle.json
  styleguide/source/_patterns/01-atoms/subtitle.twig
  styleguide/source/_patterns/03-organisms/article-header.md
  styleguide/source/_patterns/03-organisms/article-header.twig
  styleguide/source/_patterns/03-organisms/masthead-with-subtitle.md
  styleguide/source/_patterns/03-organisms/masthead.json
  styleguide/source/_patterns/03-organisms/masthead.md
  styleguide/source/_patterns/03-organisms/masthead.twig
  styleguide/source/_patterns/03-organisms/masthead~with-subtitle.json
  styleguide/source/_patterns/05-pages/news.json
  styleguide/source/_patterns/05-pages/news.twig
  styleguide/source/_patterns/05-pages/press-release.json
  styleguide/source/_patterns/05-pages/press-release.twig
  styleguide/source/assets/scss/02-molecules/_inline-bio.scss
  styleguide/source/assets/scss/03-organisms/_masthead.scss
Labels: ok to merge, priority

#96 EWL-4539: Fix ribbon contentTop not being in the right place on the page
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_0_document_4_bp-xl.png
  styleguide/source/_patterns/05-pages/topic.twig
  styleguide/source/assets/scss/04-templates/_three_column.scss
Labels: in review

#97 EWL-4540: Add logo group to press release
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release_0_document_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_templates-two-column-right_0_ama__layout--two-column_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_templates-two-column-right_0_ama__layout--two-column_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_templates-two-column-right_0_ama__layout--two-column_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_templates-two-column-right_0_ama__layout--two-column_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_templates-two-column-right_0_ama__layout--two-column_4_bp-xl.png
  styleguide/source/_patterns/05-pages/press-release.json
  styleguide/source/_patterns/05-pages/press-release.twig
  styleguide/source/assets/scss/04-templates/_two_column-right.scss
Labels: ok to merge

#91 [EWL-4520] Add H4 style/tag to ama__article-header__link
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-masthead-with-subtitle_0_ama__masthead_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-masthead-with-subtitle_0_ama__masthead_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-masthead-with-subtitle_0_ama__masthead_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-masthead-with-subtitle_0_ama__masthead_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-masthead-with-subtitle_0_ama__masthead_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-masthead_0_ama__masthead_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-masthead_0_ama__masthead_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-masthead_0_ama__masthead_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-masthead_0_ama__masthead_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-masthead_0_ama__masthead_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release_0_document_4_bp-xl.png
  styleguide/source/_patterns/03-organisms/article-header.twig
  styleguide/source/assets/scss/03-organisms/_masthead.scss
Labels: in review

#94 EWL-4524: Change inline-bio text to h3
  styleguide/backstop.json
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-inline-bio_0_ama__inline-bio_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-inline-bio_0_ama__inline-bio_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-inline-bio_0_ama__inline-bio_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-inline-bio_0_ama__inline-bio_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-inline-bio_0_ama__inline-bio_4_bp-xl.png
  styleguide/source/assets/scss/02-molecules/_inline-bio.scss
Labels: in review

#95 EWL-4526: Date and social share icons needs to line up on the news article page
  styleguide/backstop.json
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-masthead-with-subtitle_0_ama__masthead_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-masthead-with-subtitle_0_ama__masthead_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-masthead-with-subtitle_0_ama__masthead_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-masthead-with-subtitle_0_ama__masthead_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-masthead-with-subtitle_0_ama__masthead_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-masthead_0_ama__masthead_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-masthead_0_ama__masthead_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-masthead_0_ama__masthead_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-masthead_0_ama__masthead_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-masthead_0_ama__masthead_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release_0_document_4_bp-xl.png
  styleguide/source/_patterns/03-organisms/masthead.twig
  styleguide/source/assets/scss/01-atoms/_date-block.scss
  styleguide/source/assets/scss/03-organisms/_masthead.scss
Labels: in review

#98 EWL-4527: Add margin to the article-inline-stub
  styleguide/source/assets/scss/02-molecules/_article-stub.scss
Labels: in review

#99 Adds margin and bottom border to related article stub in the right sidebar
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_0_document_4_bp-xl.png
  styleguide/source/_patterns/02-molecules/article-stub.twig
  styleguide/source/assets/scss/02-molecules/_article-stub.scss
Labels: in review

#100 EWL-4467: Adds new image svg icons to assets
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-image-gold.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-image-purple.twig
  styleguide/source/assets/icons/svg/icon-image-gold.svg
  styleguide/source/assets/icons/svg/icon-image-purple.svg
  styleguide/source/assets/scss/01-atoms/_icons.scss
Labels: ok to merge

#92 [EWL-4521] Add grid when image is present
  styleguide/backstop.json
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-inline-bio_0_ama__inline-bio_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-inline-bio_0_ama__inline-bio_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-inline-bio_0_ama__inline-bio_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-inline-bio_0_ama__inline-bio_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-inline-bio_0_ama__inline-bio_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_4_bp-xl.png
  styleguide/source/assets/scss/02-molecules/_inline-bio.scss
Labels: in review

#102 [EWL-4523] Resize social icons
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-masthead-with-subtitle_0_ama__masthead_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-masthead-with-subtitle_0_ama__masthead_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-masthead-with-subtitle_0_ama__masthead_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-masthead-with-subtitle_0_ama__masthead_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-masthead_0_ama__masthead_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-masthead_0_ama__masthead_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-masthead_0_ama__masthead_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-masthead_0_ama__masthead_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release_0_document_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_0_document_0_bp-xs.png
  styleguide/source/assets/scss/02-molecules/_social-share.scss
Labels: ok to merge

#101 [EWL-4522] Update default link hover color to purple
  styleguide/source/assets/scss/01-atoms/_links.scss
Labels: ok to merge

#103 EWL-4337: Adds SCSS info tab to patternlab pattern info
  styleguide/composer.json
  styleguide/composer.lock
  styleguide/config/config.yml
  styleguide/patches/core-builder-scss-files.patch
Labels: in review

#106 [4509/4519] Move Promo to Molecules and add class ama__link--black to links
  styleguide/source/_patterns/02-molecules/promo.json
  styleguide/source/_patterns/02-molecules/promo.md
  styleguide/source/_patterns/02-molecules/promo.twig
  styleguide/source/_patterns/02-molecules/promo~email-subscription.json
  styleguide/source/_patterns/02-molecules/promo~image-without-CTA-description.json
  styleguide/source/_patterns/02-molecules/promo~logo-with-white-background.json
  styleguide/source/_patterns/02-molecules/promo~with-border.json
  styleguide/source/_patterns/02-molecules/promo~with-cta.json
  styleguide/source/_patterns/02-molecules/promo~with-image.json
Labels: in review

#110 [EWL-4510] Add ama__link--black class to link
  styleguide/source/_patterns/03-organisms/membership.twig
Labels: ok to merge

#112 [EWL-4511] Fix Tools Learn more
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release_0_document_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_0_document_4_bp-xl.png
  styleguide/source/_patterns/03-organisms/tools-block.twig
  styleguide/source/_patterns/05-pages/news.twig
  styleguide/source/_patterns/05-pages/press-release.twig
Labels: ok to merge

#107 EWL-4426: Visual clean up of topic, press release and news page from UX collab session
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release_0_document_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_templates-two-column-right_0_ama__layout--two-column_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_templates-two-column-right_0_ama__layout--two-column_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_templates-two-column-right_0_ama__layout--two-column_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_0_document_4_bp-xl.png
  styleguide/source/_patterns/02-molecules/article-metadata.twig
  styleguide/source/_patterns/02-molecules/article-stub-metadata.json
  styleguide/source/_patterns/02-molecules/article-stub-metadata.md
  styleguide/source/_patterns/02-molecules/article-stub-metadata.twig
  styleguide/source/_patterns/02-molecules/article-stub.twig
  styleguide/source/_patterns/05-pages/news.json
  styleguide/source/_patterns/05-pages/topic.json
  styleguide/source/assets/scss/01-atoms/_page-title.scss
  styleguide/source/assets/scss/02-molecules/_article-stub-metadata.scss
  styleguide/source/assets/scss/02-molecules/_article-stub.scss
  styleguide/source/assets/scss/02-molecules/_inline-bio.scss
  styleguide/source/assets/scss/03-organisms/_membership.scss
  styleguide/source/assets/scss/04-templates/_two_column-right.scss
Labels: ready for review

#89 [NO TICKET] Update standards doc based on FED meeting conversations (2/6-2/8/2018)
  .github/CONTRIBUTING.md
  .github/PULL_REQUEST_TEMPLATE.md
  docs/standards.md
Labels: in review

#118 [EWL-4513] SG2 | Remove Duplicate Promo Patterns
  styleguide/source/_patterns/02-molecules/promo~email-subscription.json
  styleguide/source/_patterns/02-molecules/promo~image-without-CTA-description.json
  styleguide/source/_patterns/02-molecules/promo~logo-with-white-background.json
Labels: ok to merge

#109 EWL-4426: Update typography - add default margins to h tags, remove bold on date, update hoverPurple color and update link hover state
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-partner-info_0_ama__partner_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-partner-info_0_ama__partner_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-partner-info_0_ama__partner_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-partner-info_0_ama__partner_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-partner-info_0_ama__partner_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-masthead-with-subtitle_0_ama__masthead_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-masthead-with-subtitle_0_ama__masthead_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-masthead-with-subtitle_0_ama__masthead_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-masthead-with-subtitle_0_ama__masthead_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-masthead-with-subtitle_0_ama__masthead_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-masthead_0_ama__masthead_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-masthead_0_ama__masthead_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-masthead_0_ama__masthead_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-masthead_0_ama__masthead_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-masthead_0_ama__masthead_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release_0_document_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_0_document_4_bp-xl.png
  styleguide/source/_patterns/00-base/colors.json
  styleguide/source/assets/scss/00-base/_colors.scss
  styleguide/source/assets/scss/00-base/_typography.scss
  styleguide/source/assets/scss/01-atoms/_date-block.scss
  styleguide/source/assets/scss/01-atoms/_links.scss
Labels: ready for review

#117 EWL-4561: Update gulpfile to prevent app.js from not getting generated on load
  styleguide/gulpfile.js
Labels: ready for review

#111 EWL-4548: Update masthead to use CSS grid to match indentation of body copy
  .gitignore
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_news_0_document_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-masthead-with-subtitle_0_ama__masthead_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-masthead-with-subtitle_0_ama__masthead_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-masthead-with-subtitle_0_ama__masthead_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-masthead-with-subtitle_0_ama__masthead_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-masthead-with-subtitle_0_ama__masthead_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-masthead_0_ama__masthead_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-masthead_0_ama__masthead_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-masthead_0_ama__masthead_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-masthead_0_ama__masthead_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-masthead_0_ama__masthead_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release_0_document_4_bp-xl.png
  styleguide/gulpfile.js
  styleguide/package.json
  styleguide/source/_patterns/03-organisms/masthead.json
  styleguide/source/_patterns/03-organisms/masthead.twig
  styleguide/source/_patterns/05-pages/press-release.json
  styleguide/source/assets/scss/03-organisms/_masthead.scss
Labels: ready for review

#115 EWL-4558: rename press-release-logos to ama__press-release__logos
  styleguide/backstop.json
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release-logos_0_ama__press-release__logos_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release-logos_0_ama__press-release__logos_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release-logos_0_ama__press-release__logos_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release-logos_0_ama__press-release__logos_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_press-release-logos_0_ama__press-release__logos_4_bp-xl.png
  styleguide/source/_patterns/02-molecules/press-release-logos.twig
  styleguide/source/assets/scss/02-molecules/_press-release-logos.scss
Labels: question

#113 [EWL-4514] SG2 | Fix Visual Regressions in Promo pattern variants and add Pattern Info
  styleguide/backstop.json
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-promo-with-border_0_ama__promo_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-promo-with-border_0_ama__promo_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-promo-with-border_0_ama__promo_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-promo-with-border_0_ama__promo_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-promo-with-border_0_ama__promo_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-promo-with-cta_0_ama__promo_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-promo-with-cta_0_ama__promo_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-promo-with-cta_0_ama__promo_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-promo-with-cta_0_ama__promo_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-promo-with-cta_0_ama__promo_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-promo_0_ama__promo_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-promo_0_ama__promo_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-promo_0_ama__promo_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-promo_0_ama__promo_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_molecules-promo_0_ama__promo_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_0_document_0_bp-xs.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_0_document_1_bp-small.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_0_document_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_0_document_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_0_document_4_bp-xl.png
  styleguide/source/_patterns/02-molecules/promo-with-border.md
  styleguide/source/_patterns/02-molecules/promo-with-cta.md
  styleguide/source/_patterns/02-molecules/promo-with-image.md
  styleguide/source/_patterns/02-molecules/promo.json
  styleguide/source/_patterns/02-molecules/promo.md
  styleguide/source/_patterns/02-molecules/promo.twig
  styleguide/source/_patterns/02-molecules/promo~with-border.json
  styleguide/source/_patterns/02-molecules/promo~with-cta.json
  styleguide/source/_patterns/02-molecules/promo~with-image.json
  styleguide/source/_patterns/05-pages/topic.json
  styleguide/source/_patterns/05-pages/topic.twig
  styleguide/source/assets/scss/02-molecules/_promo.scss
Labels: in review, priority, question

#114 Updates template css file by removing the vendor specific prefixes and uses autoprefixer insteader
  styleguide/backstop_data/bitmaps_reference/backstop_default_topics-page_0_document_1_bp-small.png
  styleguide/gulpfile.js
  styleguide/source/assets/scss/04-templates/_three_column.scss
  styleguide/source/assets/scss/04-templates/_two_column-right.scss
Labels: ready for review

#116 EWL-4557: Fix icons filling the screen by setting max widths and default widths…
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-arrow.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-audio.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-cme.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-external-site.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-image-gold.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-image-purple.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-internal-site.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-pdf.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-usermenu.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-video.twig
  styleguide/source/assets/icons/svg/icon-arrow.svg
  styleguide/source/assets/icons/svg/icon-audio.svg
  styleguide/source/assets/icons/svg/icon-cme.svg
  styleguide/source/assets/icons/svg/icon-external-site.svg
  styleguide/source/assets/icons/svg/icon-image-gold.svg
  styleguide/source/assets/icons/svg/icon-image-purple.svg
  styleguide/source/assets/icons/svg/icon-internal-site.svg
  styleguide/source/assets/icons/svg/icon-pdf.svg
  styleguide/source/assets/icons/svg/icon-usermenu.svg
  styleguide/source/assets/icons/svg/icon-video.svg
  styleguide/source/assets/scss/01-atoms/_icons.scss
  styleguide/source/assets/scss/02-molecules/_ribbon-dropdown.scss
Labels: question

#119 EWL-4616: Adds masthead indented variation
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-masthead-with-subtitle_0_ama__masthead_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-masthead-with-subtitle_0_ama__masthead_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-masthead-with-subtitle_0_ama__masthead_4_bp-xl.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-masthead_0_ama__masthead_2_bp-med.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-masthead_0_ama__masthead_3_bp-large.png
  styleguide/backstop_data/bitmaps_reference/backstop_default_organisms-masthead_0_ama__masthead_4_bp-xl.png
  styleguide/source/_patterns/03-organisms/masthead.twig
  styleguide/source/_patterns/03-organisms/masthead~as-indented.json
  styleguide/source/_patterns/03-organisms/masthead~with-subtitle-as-indented.json
  styleguide/source/_patterns/05-pages/press-release.json
  styleguide/source/assets/scss/03-organisms/_masthead.scss
Labels: ready for review

#120 EWL-4617: Fix social share hover state
  styleguide/source/assets/scss/02-molecules/_social-share.scss
Labels: in review
