Repository AmericanMedicalAssociation/ama-style-guide-2, pull requests merged in 2018-08, with the labels that each got.

#371 EWL-5608: footer organism
  styleguide/backstop.json
  styleguide/source/_data/data.json
  styleguide/source/_patterns/03-organisms/footer.twig
  styleguide/source/_patterns/03-organisms/footer/footer.json
  styleguide/source/_patterns/03-organisms/footer/footer.md
  styleguide/source/_patterns/03-organisms/footer/footer.twig
  styleguide/source/_patterns/03-organisms/footer/footer~as-universal.json
  styleguide/source/_patterns/04-templates/one-column.twig
  styleguide/source/_patterns/04-templates/split.twig
  styleguide/source/_patterns/04-templates/three-column.twig
  styleguide/source/_patterns/04-templates/two-column-left.twig
  styleguide/source/_patterns/04-templates/two-column-right.twig
  styleguide/source/assets/scss/00-base/__01.mixins/_font-variables.scss
  styleguide/source/assets/scss/01-atoms/_copyright.scss
  styleguide/source/assets/scss/01-atoms/_site_logo.scss
  styleguide/source/assets/scss/03-organisms/_footer.scss
Labels: ok to merge

#374 hotfix: product nav should be 20/20
  styleguide/source/assets/scss/03-organisms/_footer.scss
Labels: ok to merge

#376 [Hotfix] Add jQueryUI Accordion Library to D8
  styleguide/build.config.json
Labels: has D8 dependency, ok to merge, priority, ready for review

#377 Adjust hub cards and hub heroes to work in D8
  styleguide/source/_patterns/02-molecules/hub/hub-card.twig
  styleguide/source/assets/scss/02-molecules/hub/_hub-card-row.scss
  styleguide/source/assets/scss/02-molecules/hub/_hub-card.scss
  styleguide/source/assets/scss/02-molecules/hub/_hub-hero.scss
Labels: has D8 dependency, ready for review

#379 EWL-5589 Updates main navigation based on feedback from UX
  styleguide/source/_patterns/03-organisms/category-navigation-menu.twig
  styleguide/source/_patterns/03-organisms/main-navigation.json
  styleguide/source/_patterns/03-organisms/main-navigation.twig
  styleguide/source/_patterns/03-organisms/main-navigation~as-off-AMAOne.json
  styleguide/source/assets/js/category-menu.js
  styleguide/source/assets/scss/00-base/__01.mixins/_ama-button.scss
  styleguide/source/assets/scss/01-atoms/_button.scss
  styleguide/source/assets/scss/01-atoms/_search-field.scss
  styleguide/source/assets/scss/02-molecules/_global-search.scss
  styleguide/source/assets/scss/02-molecules/_sign-in-dropdown.scss
  styleguide/source/assets/scss/03-organisms/_category-navigation-menu.scss
  styleguide/source/assets/scss/03-organisms/_main-navigation.scss
Labels: in review

#382 Fixes image sizes for hub cards
  styleguide/source/_patterns/02-molecules/hub/hub-card.twig
  styleguide/source/assets/scss/02-molecules/hub/_hub-card.scss
  styleguide/source/assets/scss/02-molecules/hub/_hub-hero.scss
Labels: has D8 dependency, ready for review

#383 EWL-5367 SG2 | Correct News as Gated Styling
  styleguide/source/_patterns/05-pages/news/news-as-gated.json
  styleguide/source/assets/js/gate.js
Labels: ready for review

#385 HOTFIX: removes internal padding for description block
  styleguide/source/assets/scss/02-molecules/hub/_hub-hero.scss
Labels: priority, ready for review

#384 Update Clear Filter Styles for D8
  styleguide/source/assets/scss/00-base/_forms.scss
Labels: has D8 dependency, ok to merge, priority

#386 EWL-5184: form tweaks
  styleguide/source/assets/scss/01-atoms/_form-step.scss
Labels: has D8 dependency, ok to merge, priority

#390 EWL-5796: Create search results stub
  styleguide/source/_patterns/03-organisms/filter.json
  styleguide/source/_patterns/05-pages/event-listing.json
  styleguide/source/_patterns/05-pages/search-results.json
  styleguide/source/_patterns/05-pages/search-results.md
  styleguide/source/_patterns/05-pages/search-results.twig
Labels: ready for review

#394 Release 2.24.2
  styleguide/package-lock.json
  styleguide/package.json
Labels: ok to merge

#393 EWL-5803: search list organism
  styleguide/source/_patterns/03-organisms/search-result-list.json
  styleguide/source/_patterns/03-organisms/search-result-list.md
  styleguide/source/_patterns/03-organisms/search-result-list.twig
  styleguide/source/_patterns/05-pages/search-results.json
  styleguide/source/_patterns/05-pages/search-results.twig
  styleguide/source/assets/scss/02-molecules/search-result/_search-result.scss
  styleguide/source/assets/scss/03-organisms/_filter.scss
  styleguide/source/assets/scss/04-templates/_two_column-left.scss
  styleguide/source/assets/scss/05-pages/_search-results.scss
Labels: ready for review

#396 EWL-5808: search header as results
  styleguide/backstop.json
  styleguide/source/_patterns/01-atoms/forms/search-field.twig
  styleguide/source/_patterns/02-molecules/search-header.twig
  styleguide/source/_patterns/02-molecules/search-header~for-results.json
  styleguide/source/_patterns/05-pages/search-results.json
  styleguide/source/_patterns/05-pages/search-results.twig
  styleguide/source/assets/scss/02-molecules/_search-header.scss
Labels: ok to merge

#395 [Release] Style Guide v2.24.3
  styleguide/package-lock.json
  styleguide/package.json
Labels: ok to merge
