Repository AmericanMedicalAssociation/ama-style-guide-2, pull requests merged in 2018-10, with the labels that each got.

#424 EWL-5183: Contact us tweak
  styleguide/source/assets/scss/00-base/_webforms.scss
Labels: ok to merge

#428 EWL-5651 Fixes partner promo button
  styleguide/source/assets/scss/02-molecules/_partner-promo.scss
  styleguide/source/assets/scss/05-pages/_category.scss
Labels: has D8 dependency, in review

#427 EWL-5184 - Theme contact us form
  styleguide/source/assets/js/category-menu.js
  styleguide/source/assets/js/form-items.js
  styleguide/source/assets/scss/00-base/_forms.scss
  styleguide/source/assets/scss/00-base/_webforms.scss
  styleguide/source/assets/scss/01-atoms/_radio-button.scss
  styleguide/source/assets/scss/01-atoms/_select-menu.scss
  styleguide/source/assets/scss/03-organisms/_contact-us-webform.scss
Labels: ready for review

#430 EWL-5189: Bugfix Increase Scroll Window size
  styleguide/source/assets/scss/00-base/__01.mixins/_layout_mixin.scss
  styleguide/source/assets/scss/00-base/_webforms.scss
Labels: ready for review

#414 EWL-5769: A1 | Resource inline promo linking
  styleguide/source/_patterns/03-organisms/resource-tabs.json
  styleguide/source/_patterns/03-organisms/resource-tabs.twig
  styleguide/source/_patterns/05-pages/resource.json
  styleguide/source/assets/js/tabs.js
  styleguide/source/assets/scss/03-organisms/_resource-tabs.scss
Labels: has D8 dependency, ok to merge

#432 [EWL-5928] Correct Resource Tab Scroll To Interaction
  styleguide/source/assets/js/tabs.js
Labels: in review

#431 EWL-5816 - Updates footer subscription portion to accommodate extra D8 divs
  styleguide/source/_patterns/03-organisms/footer/footer.twig
  styleguide/source/assets/scss/02-molecules/_subscribe-promo.scss
  styleguide/source/assets/scss/03-organisms/_footer.scss
Labels: has D8 dependency, ready for review

#429 [EWL-5811] Member Feature Tweaks
  styleguide/source/assets/scss/03-organisms/_member-feature.scss
Labels: has D8 dependency, ready for review

#434 [Release] Style Guide v2.25.2
  styleguide/package-lock.json
  styleguide/package.json
Labels: ok to merge

#436 HOTFIX: Fixes global usermenu links being unclickable
  styleguide/source/assets/js/sign-in-dropdown.js
Labels: ok to merge, priority

#437 [Release] v2.25.3
  styleguide/package-lock.json
  styleguide/package.json
Labels: ok to merge, priority

#438 Rewrite annotations focused on Category and Subcategory pages
  styleguide/source/_annotations/02_subcategory-exploration.md
  styleguide/source/_annotations/03_category-hero.md
  styleguide/source/_annotations/03_subcategory-hero.md
  styleguide/source/_annotations/04_search__field--in-body.md
  styleguide/source/_annotations/05_display-switch-menu.md
  styleguide/source/_annotations/06_article-stub.md
  styleguide/source/_annotations/07_article-stub-list.md
  styleguide/source/_annotations/08_subcategory-featured-content-container.md
  styleguide/source/_annotations/09_subcategory-featured-content-as-carousel.md
  styleguide/source/_annotations/10_category__article-stub-three-up.md
  styleguide/source/_annotations/11_category__article-stub-two-up.md
  styleguide/source/_annotations/12_category-index.md
  styleguide/source/_annotations/12_subcategory-index__stubs.md
  styleguide/source/_annotations/13_partner-promo.md
  styleguide/source/_annotations/13_subscribe-promo.md
  styleguide/source/_patterns/05-pages/category.md
Labels: in review

#441 [EWL-5769] Resource inline promo linking
  styleguide/source/assets/js/tabs.js
Labels: has D8 dependency, in review, ready for review

#435 Fixes webform footer
  styleguide/source/assets/scss/03-organisms/_footer.scss
Labels: has D8 dependency, in review, priority

#446 EWL-6025 tags wrapping and EWL-6090 Tags are being hidden behind content
  styleguide/source/assets/scss/02-molecules/_tags.scss
  styleguide/source/assets/scss/02-molecules/hub/_hub-card.scss
Labels: in review, question, ready for review

#445 EWL-5602 - Add theming to text only cta hub card
  styleguide/source/assets/scss/02-molecules/hub/_hub-card.scss
Labels: has D8 dependency, ready for review

#451 EWL-6244 footer links
  styleguide/source/assets/scss/03-organisms/_bio-image-with-body.scss
  styleguide/source/assets/scss/03-organisms/_footer.scss
Labels: has D8 dependency, ready for review

#449 EWL-6227 Fix Board of trustees image size being too big
  styleguide/source/assets/scss/03-organisms/_footer.scss
Labels: ready for review

#447 Fix IE Category page layout issue
  styleguide/source/assets/scss/04-templates/_two-column-right--75-25.scss
Labels: ready for review

#417 EWL-6000 theme confirmation page
  styleguide/source/assets/scss/00-base/_webform_confirmation.scss
Labels: has D8 dependency, ready for review

#453 EWL-6231 Fix subcategories links not showing beyond two rows
  styleguide/build.config.json
  styleguide/source/_patterns/03-organisms/subcategory-exploration.twig
  styleguide/source/assets/js/subcategory-exploration.js
  styleguide/source/assets/scss/03-organisms/_subcategory-exploration.scss
Labels: has D8 dependency, in review, ready for review

#455 EWL-6251 Adds max-height to image container and hides overflow of large images
  styleguide/source/assets/scss/02-molecules/hub/_hub-card.scss
Labels: in review, priority, ready for review

#454 EWL-6249 Fix hub hero height
  styleguide/source/assets/scss/02-molecules/hub/_hub-hero.scss
Labels: in review, priority, ready for review

#443 Fixes layout for IE11
  styleguide/source/_patterns/05-pages/news/news.json
  styleguide/source/assets/scss/01-atoms/_image.scss
  styleguide/source/assets/scss/02-molecules/_article-stub.scss
  styleguide/source/assets/scss/03-organisms/_masthead.scss
  styleguide/source/assets/scss/04-templates/_two_column-right.scss
Labels: has D8 dependency, in review, ready for review

#450 [EWL-6171] People Bio Affiliation Padding
  styleguide/source/assets/scss/02-molecules/_content-with-label.scss
Labels: has D8 dependency, in review, priority, ready for review

#459 [Homepage] Organization Nav 2x2
  styleguide/source/assets/scss/03-organisms/_category-nav.scss
  styleguide/source/assets/scss/03-organisms/_org-nav.scss
Labels: has D8 dependency, in review, ok to merge, priority, ready for review

#460 [Homepage] Promos and Hero
  styleguide/source/assets/scss/02-molecules/_partner-promo.scss
  styleguide/source/assets/scss/05-pages/_homepage.scss
Labels: has D8 dependency, in review, ok to merge, priority, ready for review

#442 EWL-5810 global header (merge before PR #439 and #440)
  styleguide/source/assets/js/sign-in-dropdown.js
Labels: has D8 dependency, ok to merge, ready for review

#444 EWL-6122: Resource page promo button color.
  styleguide/source/assets/scss/03-organisms/_resource-tabs.scss
Labels: has D8 dependency, ready for review

#448 EWL-6207 Fix bullet position and style
  styleguide/source/assets/scss/01-atoms/_social-icons.scss
  styleguide/source/assets/scss/01-atoms/_unordered-list.scss
  styleguide/source/assets/scss/02-molecules/_jama.scss
  styleguide/source/assets/scss/02-molecules/_social-share.scss
  styleguide/source/assets/scss/02-molecules/_tags.scss
  styleguide/source/assets/scss/03-organisms/_category-nav.scss
Labels: in review, ready for review

#463 EWL-6281 homepage email subscription
  styleguide/source/_patterns/02-molecules/subscribe-promo.twig
  styleguide/source/_patterns/05-pages/homepage.json
  styleguide/source/assets/scss/02-molecules/_subscribe-promo.scss
Labels: has D8 dependency, in review, ready for review

#439 EWL-5814 Themes global search
  styleguide/source/_patterns/02-molecules/global-search.twig
  styleguide/source/assets/js/global-search.js
  styleguide/source/assets/scss/02-molecules/_global-search.scss
Labels: has D8 dependency, in review, priority, question, ready for review

#452 EWL-5866: Jama component enhancement
  styleguide/backstop.json
  styleguide/source/_patterns/02-molecules/jama-stub/jama-stub.json
  styleguide/source/_patterns/02-molecules/jama-stub/jama-stub.md
  styleguide/source/_patterns/02-molecules/jama-stub/jama-stub.twig
  styleguide/source/_patterns/02-molecules/jama-stub/jama-stub~as-homepage.json
  styleguide/source/_patterns/02-molecules/jama-stub/jama-stub~as-horizontal.json
  styleguide/source/_patterns/02-molecules/jama-stub/jama-stub~as-vertical-with-image.json
  styleguide/source/_patterns/02-molecules/jama/jama-as-content-bottom.md
  styleguide/source/_patterns/02-molecules/jama/jama-as-three-up.md
  styleguide/source/_patterns/02-molecules/jama/jama.json
  styleguide/source/_patterns/02-molecules/jama/jama.md
  styleguide/source/_patterns/02-molecules/jama/jama.twig
  styleguide/source/_patterns/02-molecules/jama/jama~as-homepage.json
  styleguide/source/_patterns/02-molecules/jama/jama~as-horizontal.json
  styleguide/source/_patterns/02-molecules/jama/jama~as-vertical-with-images.json
  styleguide/source/_patterns/03-organisms/_category-article-three-up-jama.twig
  styleguide/source/_patterns/03-organisms/_category-jama-article-stub-as-large.twig
  styleguide/source/_patterns/05-pages/category.json
  styleguide/source/_patterns/05-pages/homepage.json
  styleguide/source/_patterns/05-pages/news/news-with-jama-examples.json
  styleguide/source/_patterns/05-pages/news/news-with-jama-examples.twig
  styleguide/source/assets/scss/00-base/_colors.scss
  styleguide/source/assets/scss/02-molecules/_jama.scss
Labels: in review, priority

#465 [Release] Style guide v2.26.2
  styleguide/package-lock.json
  styleguide/package.json
Labels: ok to merge, ready for review

#472 Add search filter text box js
  styleguide/build.config.json
  styleguide/source/assets/js/form-items.js
  styleguide/source/assets/js/search-checkbox.js
  styleguide/source/assets/scss/00-base/_forms.scss
  styleguide/source/assets/scss/01-atoms/_checkbox.scss
  styleguide/source/assets/scss/01-atoms/_search-field.scss
  styleguide/source/assets/scss/02-molecules/_applied_filters.scss
  styleguide/source/assets/scss/02-molecules/_global-search.scss
  styleguide/source/assets/scss/02-molecules/_search-header.scss
  styleguide/source/assets/scss/02-molecules/search-result/_search-result.scss
Labels: has D8 dependency, in review, priority

#470 EWL-6340 Fix CTA button to always be at the bottom of cards
  styleguide/source/_patterns/02-molecules/people-listing/people-listing.twig
  styleguide/source/_patterns/05-pages/people-listing.json
  styleguide/source/assets/scss/02-molecules/_people-listing.scss
  styleguide/source/assets/scss/05-pages/_people-listing.scss
Labels: has D8 dependency, ok to merge

#473 EWL-6374 max width of best bets image
  styleguide/source/_patterns/02-molecules/search-result/search-result.twig
  styleguide/source/assets/scss/02-molecules/search-result/_search-result.scss
Labels: has D8 dependency, ready for review

#475 [EWL-6355] Correct Page Mastheads
  styleguide/source/assets/scss/02-molecules/_social-share.scss
  styleguide/source/assets/scss/03-organisms/_masthead.scss
  styleguide/source/assets/scss/04-templates/_two_column-right.scss
  styleguide/source/assets/scss/05-pages/_category.scss
Labels: has D8 dependency, ready for review

#468 EWL-6207 Fix bullet position and style (original PR #448)
  styleguide/source/assets/scss/01-atoms/_social-icons.scss
  styleguide/source/assets/scss/01-atoms/_unordered-list.scss
  styleguide/source/assets/scss/02-molecules/_jama.scss
  styleguide/source/assets/scss/02-molecules/_social-share.scss
  styleguide/source/assets/scss/02-molecules/_tags.scss
  styleguide/source/assets/scss/03-organisms/_category-nav.scss
Labels: has D8 dependency, ok to merge

#476 EWl-6336 Fix sign in link not going anywhere
  styleguide/source/assets/js/sign-in-dropdown.js
  styleguide/source/assets/scss/02-molecules/_sign-in-dropdown.scss
Labels: has D8 dependency, in review

#469 EWL-6292 - Fix category page hero padding
  styleguide/source/_patterns/05-pages/category.twig
  styleguide/source/assets/scss/02-molecules/_category-hero.scss
  styleguide/source/assets/scss/05-pages/_category.scss
Labels: has D8 dependency, ok to merge

#464 Rewrite annotations focused on Home page
  styleguide/source/_annotations/01_alert-wrap.md
  styleguide/source/_annotations/01_product-nav.md
  styleguide/source/_annotations/02_homepage-navs.md
  styleguide/source/_annotations/14_home-member-feature.md
  styleguide/source/_annotations/15_home-four-up-links.md
  styleguide/source/_annotations/16_upcoming-events.md
  styleguide/source/_annotations/17_products.md
  styleguide/source/_annotations/18_homepage-mission-header.md
Labels: ready for review

#471 EWl-5835 Fix news article no author byline
  styleguide/source/_patterns/05-pages/news/news.twig
  styleguide/source/assets/scss/02-molecules/_inline-bio.scss
  styleguide/source/assets/scss/03-organisms/_masthead.scss
  styleguide/source/assets/scss/04-templates/_two_column-right.scss
Labels: has D8 dependency, ok to merge

#467 EWL-6339 Fix news article gated overlay
  styleguide/source/assets/scss/01-atoms/_gate.scss
  styleguide/source/assets/scss/04-templates/_two_column-right.scss
Labels: has D8 dependency, ok to merge

#480 Update SG2 version to v2.26.4
  styleguide/package-lock.json
  styleguide/package.json
Labels: ready for review

#483 EWL-6429 Fix multi CTA card
  styleguide/source/assets/scss/02-molecules/hub/_hub-hero.scss
Labels: has D8 dependency, in review, ready for review

#479 Quick fix: Filter reset on search page doesn't clear checkboxes
  styleguide/source/assets/js/form-items.js
  styleguide/source/assets/js/search-checkbox.js
Labels: has D8 dependency, in review, ready for review

#484 EWL-6453 removes bullets in the related links tab on resource page
  styleguide/source/assets/scss/03-organisms/_resource-tabs.scss
Labels: in review, priority, ready for review

#482 EWL-6421 Fix email subscription in the footer
  styleguide/source/assets/js/webforms.js
  styleguide/source/assets/scss/00-base/_forms.scss
Labels: has D8 dependency, ready for review

#486 Updates release to v2.26.5
  styleguide/package-lock.json
  styleguide/package.json
Labels: ok to merge
