Repository AmericanMedicalAssociation/ama-style-guide-2, pull requests merged in 2019-01, with the labels that each got.

#564 EWL-6648: Center subscribe button mobile
  styleguide/source/assets/scss/02-molecules/_subscribe-promo.scss
Labels: question, ready for review

#562 EWL-6643: Style footer social links differently on small screens.
  styleguide/source/assets/scss/02-molecules/_social-share.scss
  styleguide/source/assets/scss/03-organisms/_footer.scss
Labels: ready for review, review standards

#556 EWL-6641: Align category links in mega menu.
  styleguide/source/assets/scss/03-organisms/_category-navigation-menu.scss
Labels: Needs second review, ready for review

#553 EWL-6632: Address overlapping when expanding / contracting.
  styleguide/source/assets/scss/02-molecules/_expand-list.scss
Labels: Needs second review, ready for review

#555 EWL-6638 Updates global submenu to center within the viewport
  styleguide/source/_patterns/03-organisms/category-navigation-menu.twig
  styleguide/source/assets/js/category-menu.js
  styleguide/source/assets/scss/03-organisms/_category-navigation-menu.scss
Labels: has D8 dependency, ready for review

#571 EWL-6659 Updates mobile click event to open filter panel.
  styleguide/source/_patterns/03-organisms/filter.twig
  styleguide/source/assets/js/form-items.js
  styleguide/source/assets/scss/02-molecules/_applied_filters.scss
Labels: ok to merge

#572 Version 2.28.2
  styleguide/package-lock.json
  styleguide/package.json
Labels: ok to merge

#574 EWL-6781: A1 – Video support for homepage article stubs
  styleguide/source/assets/scss/01-atoms/_videos.scss
  styleguide/source/assets/scss/02-molecules/_article-stub.scss
  styleguide/source/assets/scss/02-molecules/hub/_hub-hero.scss
  styleguide/source/assets/scss/03-organisms/_member-feature.scss
Labels: has D8 dependency

#576 EWL-6654: adds padding to the list elements of the horizontal jama co…
  styleguide/source/assets/scss/02-molecules/_jama.scss
Labels: ok to merge

#577 EWL-6881 BP Calculator
  styleguide/build.config.json
  styleguide/source/_patterns/03-organisms/bp-calculator/bp-table.twig
  styleguide/source/_patterns/05-pages/bp-calculator.json
  styleguide/source/_patterns/05-pages/bp-calculator.md
  styleguide/source/_patterns/05-pages/bp-calculator.twig
  styleguide/source/assets/js/bp-calculator.js
  styleguide/source/assets/js/tables.js
  styleguide/source/assets/scss/00-base/__01.mixins/_ama-button.scss
  styleguide/source/assets/scss/01-atoms/_button.scss
  styleguide/source/assets/scss/03-organisms/_bp-table.scss
Labels: ok to merge, priority

#580 Updates version to 2.28.3
  styleguide/package-lock.json
  styleguide/package.json
Labels: ok to merge
