Repository AmericanMedicalAssociation/ama-style-guide-2, pull requests merged in 2019-06, with the labels that each got.

#640 EWL-7269: Evergreen Pages | Embedded image caption does not wrap
  styleguide/source/assets/scss/01-atoms/_image.scss
Labels: ready for review

#642 EWL-7271: Evergreen Pages | Flex cards do not span full width if only 3 cards
  styleguide/source/assets/scss/02-molecules/_article-stub.scss
Labels: has D8 dependency, ok to merge

#644 EWL-7280: Social Icons Color Needs to be Purple
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-email-purple.twig
  styleguide/source/assets/icons/svg/icon-email-purple.svg
  styleguide/source/assets/scss/02-molecules/_social-share.scss
Labels: in review

#643 Release v2.34.3
  styleguide/package-lock.json
  styleguide/package.json
Labels: ready for review

#648 EWL-7303 social icons not appearing in footer
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-email-purple.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-facebook-white-purple.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-googleplus-white-purple.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-instagram-white-purple.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-instagram-white-white.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-linkedin-white-purple.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-twitter-white-purple.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-youtube-white-purple.twig
  styleguide/source/_patterns/03-organisms/footer/footer~as-universal.json
  styleguide/source/assets/icons/svg/icon-facebook-white-purple.svg
  styleguide/source/assets/icons/svg/icon-googleplus-white-purple.svg
  styleguide/source/assets/icons/svg/icon-instagram-white-purple.svg
  styleguide/source/assets/icons/svg/icon-linkedin-white-purple.svg
  styleguide/source/assets/icons/svg/icon-twitter-white-purple.svg
  styleguide/source/assets/icons/svg/icon-youtube-white-purple.svg
Labels: ready for review

#645 EWL-7283: Mobile Evergreen Page Padding
  styleguide/source/assets/scss/04-templates/_two_column-right.scss
Labels: ready for review

#641 EWL-7199: SG2 | Create hero organism for Evergreen Page
  styleguide/source/_patterns/02-molecules/hero-evergreen/hero-evergreen.json
  styleguide/source/_patterns/02-molecules/hero-evergreen/hero-evergreen.md
  styleguide/source/_patterns/02-molecules/hero-evergreen/hero-evergreen.twig
  styleguide/source/_patterns/02-molecules/hero-evergreen/hero-evergreen~as-double-button.json
  styleguide/source/_patterns/02-molecules/hero-evergreen/hero-evergreen~as-full.json
  styleguide/source/_patterns/02-molecules/hero-evergreen/hero-evergreen~as-single-button.json
  styleguide/source/_patterns/02-molecules/hero-evergreen/hero-evergreen~as-stacked-button.json
  styleguide/source/assets/scss/00-base/__01.mixins/_gutter_mixin.scss
  styleguide/source/assets/scss/02-molecules/_hero-evergreen.scss
Labels: ready for review

#649 EWL-7287: IE | Footer on Gated pages without right rail content hiding login
  styleguide/source/assets/scss/04-templates/_two_column-right.scss
Labels: ready for review

#650 updates to v2.35.0
  styleguide/package-lock.json
  styleguide/package.json
Labels: ok to merge

#652 EWL-7358: Fixes to Evergreen Hero Organism
  styleguide/source/assets/scss/02-molecules/_hero-evergreen.scss
Labels: ready for review

#653 EWL-7287: Footer on Gated Pages and email subscribe in footer region
  styleguide/source/assets/scss/01-atoms/_gate.scss
  styleguide/source/assets/scss/02-molecules/_subscribe-promo.scss
Labels: ready for review

#651 EWL-7353: Embedded Video Spacing on EP
  styleguide/source/assets/scss/01-atoms/_image.scss
Labels: ready for review

#654 EWL-7083: People listing word break fix
  styleguide/source/assets/scss/02-molecules/_people-listing.scss
Labels: ready for review

#656 release 2.35.1
  styleguide/package-lock.json
  styleguide/package.json
Labels: ready for review
