Repository AmericanMedicalAssociation/ama-style-guide-2, pull requests merged in 2019-08, with the labels that each got.

#662 EWL-7409: iPhone XS Max: Profile text is rendering improperly on people bio index pages
  styleguide/source/assets/js/people-listing.js
  styleguide/source/assets/scss/02-molecules/_people-listing.scss
  styleguide/source/assets/scss/05-pages/_people-listing.scss
Labels: ready for review

#663 EWL-7477: Fix Rule to display icons all the time in all devices.
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-email-purple.twig
  styleguide/source/assets/scss/02-molecules/_social-share.scss
Labels: ready for review

#664 release v2.37.0
  styleguide/package-lock.json
  styleguide/package.json
Labels: ok to merge

#665 EWL-7501: Social Sharing Icons - People Bio Template
  styleguide/source/assets/scss/03-organisms/_masthead.scss
Labels: question

#666 Release v2.37.1
  styleguide/package-lock.json
  styleguide/package.json
Labels: ready for review

#667 EWL-7527: Social share icons not appearing on News Article template
  styleguide/source/assets/scss/03-organisms/_masthead.scss
Labels: ready for review

#668 Release v2.38.0
  styleguide/package-lock.json
  styleguide/package.json
Labels: ok to merge, ready for review

#670 [Release] Style Guide v2.38.1
  styleguide/package-lock.json
  styleguide/package.json
Labels: ready for review

#669 Remove 'atom' and 'molecule' VRTs
  styleguide/backstop.json
Labels: ready for review

#672 EWL-7451: Solving Issue with Image Floated on IE11.
  styleguide/source/assets/scss/01-atoms/_image.scss
Labels: ready for review

#671 Build Nested List in the styleguide to be implemented in the CKeditor.
  styleguide/source/_patterns/01-atoms/lists/listicle.json
  styleguide/source/_patterns/01-atoms/lists/listicle.md
  styleguide/source/_patterns/01-atoms/lists/listicle.twig
  styleguide/source/assets/scss/01-atoms/_listicle.scss
Labels: in review, ready for review
