Repository AmericanMedicalAssociation/ama-style-guide-2, pull requests merged in 2019-03, with the labels that each got.

#579 EWL-6805: Align Article Stub Title and Image
  styleguide/source/assets/scss/02-molecules/_article-stub.scss
  styleguide/source/assets/scss/03-organisms/_category-page-article-stub.scss
Labels: ready for review, review in ama_one

#586 EWL-6731 Fixes people listing page with uneven number cards
  styleguide/build.config.json
  styleguide/source/_patterns/05-pages/people-listing.json
  styleguide/source/assets/js/people-listing.js
  styleguide/source/assets/scss/02-molecules/_people-listing.scss
  styleguide/source/assets/scss/05-pages/_people-listing.scss
Labels: ready for review

#600 EWL-7011: Fix Policy Finder
  styleguide/source/assets/scss/00-base/_webforms.scss
Labels: has D8 dependency, ok to merge

#603 [Release] Style guide v2.31.0
  styleguide/package-lock.json
  styleguide/package.json
Labels: ready for review

#602 EWL-7009 - Resource page links ghost box
  styleguide/source/assets/scss/03-organisms/_resource-tabs.scss
Labels: ok to merge, review in ama_one

#605 [Release] Style guide v2.31.1
  styleguide/package-lock.json
  styleguide/package.json
Labels: ready for review

#606 EWL-7013: Added submit event button and Ama event banner
  styleguide/source/_patterns/02-molecules/event-stub/event-stub.json
  styleguide/source/_patterns/02-molecules/event-stub/event-stub.twig
  styleguide/source/_patterns/03-organisms/event-list.json
  styleguide/source/_patterns/03-organisms/masthead/masthead.twig
  styleguide/source/_patterns/05-pages/event-listing.json
  styleguide/source/assets/scss/02-molecules/_event-stub.scss
  styleguide/source/assets/scss/03-organisms/_masthead.scss
Labels: ready for review

#607 [EWL-7009] Bugfix: Resource page links ghost box
  styleguide/source/assets/scss/03-organisms/_resource-tabs.scss
Labels: ready for review

#604 EWL-7026: Existing links on Resource pages are not highlighted purple
  styleguide/source/_patterns/05-pages/resource.json
  styleguide/source/assets/js/tabs.js
Labels: in review

#588 EWL-6949: A1 | Image alignment for JAMA component
  styleguide/source/assets/scss/02-molecules/_jama.scss
  styleguide/source/assets/scss/03-organisms/_category-page-article-stub.scss
Labels: ready for review

#609 EWL-7092 SG2 | Create simple header organism for SLP
  styleguide/source/_patterns/03-organisms/sales-landing-page-header.json
  styleguide/source/_patterns/03-organisms/sales-landing-page-header.twig
  styleguide/source/assets/scss/03-organisms/_sales-landing-page-header.scss
Labels: ok to merge

#610 EWL-7098 SG2 | Create SLP Hero Organism
  styleguide/source/_patterns/03-organisms/sales-landing-page-hero.json
  styleguide/source/_patterns/03-organisms/sales-landing-page-hero.twig
  styleguide/source/assets/scss/03-organisms/_sales-landing-page-hero.scss
Labels: ok to merge
