Repository AmericanMedicalAssociation/ama-style-guide-2, pull requests merged in 2019-10, with the labels that each got.

#681 SC-12: Theme Search Connector
  styleguide/source/_patterns/02-molecules/search-result/search-connector.json
  styleguide/source/_patterns/02-molecules/search-result/search-connector.md
  styleguide/source/_patterns/02-molecules/search-result/search-connector.twig
  styleguide/source/_patterns/04-templates/two-column-left.twig
  styleguide/source/_patterns/05-pages/search-results.json
  styleguide/source/_patterns/05-pages/search-results.twig
  styleguide/source/assets/scss/02-molecules/search-result/_search-connector.scss
  styleguide/source/assets/scss/04-templates/_two_column-left.scss
Labels: has D8 dependency, ok to merge

#686 EWL-6782: Adding New Component for Blockquotes.
  styleguide/source/_patterns/01-atoms/block-quote/block-quote.json
  styleguide/source/_patterns/01-atoms/block-quote/block-quote.md
  styleguide/source/_patterns/01-atoms/block-quote/block-quote.twig
  styleguide/source/assets/scss/01-atoms/_block-quote.scss
Labels: ok to merge

#687 EWL-6852 changed styles to display full image at all breakpoints
  styleguide/source/assets/scss/02-molecules/hub/_hub-card.scss
Labels: ready for review

#683 EWL-6893 removed rule overriding backgrounds size rules.
  styleguide/source/assets/scss/02-molecules/hub/_hub-hero.scss
Labels: ready for review

#693 EWL-6782: Formatting blockquotes
  styleguide/source/assets/scss/01-atoms/_block-quote.scss
Labels: ready for review
