Repository AmericanMedicalAssociation/ama-style-guide-2, pull requests merged in 2019-05, with the labels that each got.

#621 EWL-6949: EWL-6949: A1 | Image alignment for JAMA component
  styleguide/source/assets/scss/02-molecules/_jama.scss
Labels: ready for review

#625 EWL-7175: Contact Us Form - Enhancement
  styleguide/source/assets/js/webforms.js
  styleguide/source/assets/scss/03-organisms/_contact-us-webform.scss
Labels: ok to merge

#626 EWL-7076: Menu doesn't expand on people listing pages
  styleguide/source/assets/scss/03-organisms/_main-navigation.scss
  styleguide/source/assets/scss/05-pages/_people-listing.scss
Labels: ok to merge

#624 EWL-6775 Social Sharing Icons - sticky
  styleguide/source/assets/js/main-navigation.js
  styleguide/source/assets/scss/03-organisms/_masthead.scss
Labels: ready for review

#627 EWL-7176 Remove Menu Expansion Scroll Bars
  styleguide/build.config.json
  styleguide/source/_patterns/03-organisms/category-navigation-menu.twig
  styleguide/source/assets/js/main-navigation.js
  styleguide/source/assets/js/vendor/jquery.mousewheel.js
  styleguide/source/assets/scss/03-organisms/_category-navigation-menu.scss
  styleguide/source/assets/scss/03-organisms/_main-navigation.scss
Labels: ready for review

#630 Release 2.33.2
  styleguide/package-lock.json
  styleguide/package.json
Labels: ready for review

#631 EWL-7191 Tablet Menu scroll and expansion does not work correctly
  styleguide/source/assets/js/main-navigation.js
  styleguide/source/assets/js/nav.js
  styleguide/source/assets/scss/03-organisms/_category-navigation-menu.scss
  styleguide/source/assets/scss/03-organisms/_main-navigation.scss
Labels: ready for review

#622 EWL-7082: Adjust the mobile designs for "Submit Event" button
  styleguide/source/assets/scss/03-organisms/_masthead.scss
Labels: ready for review

#632 EWL-7158: SLP Auto Crop Images (IE bugfix)
  styleguide/source/assets/scss/03-organisms/_sales-landing-page-hero.scss
Labels: ready for review

#633 Release 2.34.0
  styleguide/package-lock.json
  styleguide/package.json
Labels: ready for review

#634 EWL-7242 Sticky Navigation Testing Issues
  styleguide/build.config.json
  styleguide/source/_patterns/03-organisms/category-navigation-menu.json
  styleguide/source/_patterns/03-organisms/category-navigation-menu.twig
  styleguide/source/_patterns/03-organisms/main-navigation/main-navigation.twig
  styleguide/source/_patterns/05-pages/bp-calculator.json
  styleguide/source/_patterns/05-pages/category.json
  styleguide/source/_patterns/05-pages/error.json
  styleguide/source/_patterns/05-pages/event-listing.json
  styleguide/source/_patterns/05-pages/event.json
  styleguide/source/_patterns/05-pages/homepage.json
  styleguide/source/_patterns/05-pages/hub.json
  styleguide/source/_patterns/05-pages/people-bio.json
  styleguide/source/_patterns/05-pages/people-listing.json
  styleguide/source/_patterns/05-pages/press-release.json
  styleguide/source/_patterns/05-pages/resource.json
  styleguide/source/_patterns/05-pages/search-results.json
  styleguide/source/_patterns/05-pages/subcategory.json
  styleguide/source/_patterns/05-pages/topic.json
  styleguide/source/assets/js/main-navigation.js
  styleguide/source/assets/js/vendor/bodyScrollLock.min.js
  styleguide/source/assets/js/vendor/jquery.mousewheel.js
  styleguide/source/assets/scss/02-molecules/_global-search.scss
  styleguide/source/assets/scss/03-organisms/_category-navigation-menu.scss
  styleguide/source/assets/scss/03-organisms/_main-navigation.scss
Labels: has D8 dependency, priority, ready for review

#635 EWL-7175: Contact Us Form - Enhancement - Testing site fix
  styleguide/source/assets/js/webforms.js
Labels: ready for review

#629 EWL-6774: Modify Join/Renew link on mobile
  styleguide/source/assets/scss/03-organisms/_main-navigation.scss
Labels: ready for review

#636 Release 2.34.1
  styleguide/package-lock.json
  styleguide/package.json
Labels: ready for review

#637 EWL-7250 Main Navigation Testing Issues
  styleguide/source/assets/js/main-navigation.js
  styleguide/source/assets/scss/03-organisms/_category-navigation-menu.scss
  styleguide/source/assets/scss/03-organisms/_main-navigation.scss
Labels: ready for review

#638 Release 2.34.2
  styleguide/package-lock.json
  styleguide/package.json
Labels: ready for review

#639 EWL-7222: Evergreen Page | Add page title and subtitle to SG
  styleguide/source/_patterns/03-organisms/masthead/masthead.md
  styleguide/source/_patterns/03-organisms/masthead/masthead.twig
  styleguide/source/_patterns/03-organisms/masthead/masthead~with-subtitle-as-centered.json
  styleguide/source/assets/scss/03-organisms/_masthead.scss
Labels: ready for review
