Repository AmericanMedicalAssociation/ama-style-guide-2, pull requests merged in 2019-02, with the labels that each got.

#584 EWL-6738 View all link fix
  styleguide/source/assets/js/subcategory-exploration.js
Labels: ok to merge

#585 EWL-6809 individual panel scrolling
  styleguide/build.config.json
  styleguide/source/_patterns/03-organisms/footer/footer.json
  styleguide/source/_patterns/03-organisms/footer/footer.twig
  styleguide/source/_patterns/03-organisms/resource-tabs.twig
  styleguide/source/_patterns/04-templates/split.twig
  styleguide/source/_patterns/05-pages/resource.json
  styleguide/source/assets/js/resource.js
  styleguide/source/assets/js/tables.js
  styleguide/source/assets/scss/03-organisms/_footer.scss
  styleguide/source/assets/scss/03-organisms/_resource-tabs.scss
  styleguide/source/assets/scss/04-templates/_split.scss
  styleguide/source/assets/scss/04-templates/_two_column-right.scss
  styleguide/source/assets/scss/05-pages/_resource.scss
Labels: ready for review

#581 EWL-6662: adjust form-items js in order to fix the filters + and - icons
  styleguide/source/assets/js/form-items.js
Labels: ok to merge

#583 EWL-6730 Prevent text from flowing outside of container
  styleguide/source/assets/scss/02-molecules/_people-listing.scss
Labels: ok to merge

#582 [EWL-6314] Layout builder - block title check box
  styleguide/source/assets/js/form-items.js
Labels: ok to merge

#578 EWL-6633: adds rules in order to fix search icon on IE
  styleguide/source/assets/scss/01-atoms/_search-field.scss
Labels: ok to merge

#592 EWL-6979: A1 | Scroll resource tab content instead of page
  styleguide/source/assets/js/tabs.js
  styleguide/source/assets/scss/04-templates/_split.scss
Labels: has D8 dependency, ok to merge, ready for review

#593 EWL-6975: A1 | Resource Page Resource Link Enhancement
  styleguide/source/_patterns/03-organisms/resource-tabs.twig
  styleguide/source/_patterns/05-pages/resource.json
  styleguide/source/assets/js/tabs.js
  styleguide/source/assets/scss/03-organisms/_resource-tabs.scss
Labels: has D8 dependency, ok to merge, priority

#587 EWL-6771 homepage announcement banner
  styleguide/build.config.json
  styleguide/source/assets/js/alert.js
Labels: ok to merge, priority, review in ama_one

#594 EWL-6738: Category - View All Subcategories Bug
  styleguide/source/assets/js/subcategory-exploration.js
Labels: ok to merge
