Repository AmericanMedicalAssociation/ama-style-guide-2, pull requests merged in 2020-12, with the labels that each got.

#940 EWL-8371: Adding Missing padding for Tools & Resources according specs
  styleguide/source/assets/scss/02-molecules/_tool.scss
Labels: ready for review

#965 EWL-8382: Styling to fix tablet padding issue for Stub Lists on Subca…
  styleguide/source/assets/scss/03-organisms/_category-page-article-stub.scss
Labels: ready for review

#966 bumped SG to 2.56.0
  styleguide/package-lock.json
  styleguide/package.json
Labels: ready for review

#967 EWL-8454: Padding Missing from Explore Topics in Subcategory
  styleguide/source/assets/scss/03-organisms/_subcategory-explore-topics.scss
Labels: in review, ready for review

#968 EWL-8446: Drupal 8.9 / “9” | People Bio image size decreased, and is centering against content
  styleguide/source/assets/scss/03-organisms/_bio-image-with-body.scss
Labels: ok to merge

#969 bumped SG to 2.56.1
  styleguide/package-lock.json
  styleguide/package.json
Labels: ready for review
