Repository AmericanMedicalAssociation/ama-style-guide-2, pull requests merged in 2020-05, with the labels that each got.

#803 converted gray-50 to accessibility compliant color. Switched date dis…
  styleguide/source/assets/scss/00-base/_colors.scss
  styleguide/source/assets/scss/02-molecules/_article-stub-metadata.scss
  styleguide/source/assets/scss/02-molecules/_forum-comments.scss
  styleguide/source/assets/scss/02-molecules/_forum-topic.scss
  styleguide/source/assets/scss/02-molecules/_subcategory-page-article-stub.scss
Labels: in review, ready for review

#804 EWL-7981: Change SERP Interaction to the Entire Swim Lane
  styleguide/source/_patterns/02-molecules/search-result/search-result.twig
  styleguide/source/assets/scss/02-molecules/search-result/_search-result.scss
  styleguide/source/assets/scss/05-pages/_search-results.scss
Labels: has D8 dependency, ok to merge

#805 Updates SG2 to v2.48.0
  styleguide/package-lock.json
  styleguide/package.json
Labels: ready for review

#806 EWL-7981: Change SERP Interaction to the Entire Swim Lane
  styleguide/source/assets/scss/02-molecules/search-result/_search-result.scss
  styleguide/source/assets/scss/04-templates/_two_column-left.scss
Labels: ready for review
