Repository AmericanMedicalAssociation/ama-style-guide-2, pull requests merged in 2020-07, with the labels that each got.

#841 EWL-8090: removed block style
  styleguide/source/assets/scss/02-molecules/_promo.scss
Labels: ok to merge, sprint 50

#844 EWL-8091: Mofiying icons for essentials tools and resources size
  styleguide/source/assets/scss/01-atoms/_icons.scss
Labels: ok to merge, sprint 50

#845 EWL-811: Removing Extra Space in Featured Stories to match Zepling Designs
  styleguide/source/assets/scss/02-molecules/_article-stub.scss
Labels: ok to merge

#842 EWL-8058: Global Change to margins of blockquote.
  styleguide/source/assets/scss/02-molecules/_block-quote.scss
Labels: ready for review, sprint 50

#850 bumped SG to 2.50.0
  styleguide/package-lock.json
  styleguide/package.json
Labels: ready for review

#851 EWL-8109: Article Page Redesign Membership Custom Block - Mobile /Tablet Vertical Spacing
  styleguide/source/assets/scss/00-base/__01.mixins/_gutter_mixin.scss
  styleguide/source/assets/scss/03-organisms/_footer.scss
Labels: ok to merge

#849 EWL-8015: Bugfix - Forcing width on modal images
  styleguide/source/assets/images/close.svg
  styleguide/source/assets/images/expand.svg
  styleguide/source/assets/js/modal.js
  styleguide/source/assets/scss/02-molecules/_modal.scss
Labels: has D8 dependency, ok to merge, sprint 50

#846 EWL-8108: Fixing Extra space topic terms and tools and resources.
  styleguide/source/assets/scss/02-molecules/_tags.scss
Labels: ready for review, sprint 50

#848 EWL-8102: added styles to inline promo blocks. + EWL-8102
  styleguide/source/assets/scss/02-molecules/_promo.scss
  styleguide/source/assets/scss/03-organisms/_membership.scss
Labels: ready for review, sprint 50

#847 EWL-8110: Article Page Redesign - Related Content
  styleguide/source/assets/scss/03-organisms/_column-teaser.scss
Labels: ready for review, sprint 50

#853 bumped SG to 2.50.1
  styleguide/package-lock.json
  styleguide/package.json
Labels: ready for review

#854 removed closeIcon var that was throwing GulpUglify error.
  styleguide/source/assets/js/modal.js
Labels: ready for review

#852 EWL-7931: Add upvote functionality to Article pages
  styleguide/source/assets/images/thumbs-active.svg
  styleguide/source/assets/images/thumbs.svg
  styleguide/source/assets/scss/02-molecules/_tags.scss
  styleguide/source/assets/scss/02-molecules/_upvote.scss
Labels: ok to merge, sprint 50

#855 bumped SG to 2.50.2
  styleguide/package-lock.json
  styleguide/package.json
Labels: ready for review

#843 EWL-7790: implement simplified ordered lists
  styleguide/source/assets/scss/00-base/__01.mixins/_lists.scss
  styleguide/source/assets/scss/01-atoms/_ordered-list.scss
  styleguide/source/assets/scss/01-atoms/_unordered-list.scss
  styleguide/source/assets/scss/02-molecules/_partner-promo.scss
  styleguide/source/assets/scss/02-molecules/_product.scss
  styleguide/source/assets/scss/02-molecules/_promo.scss
  styleguide/source/assets/scss/02-molecules/_subscribe-promo.scss
  styleguide/source/assets/scss/02-molecules/hub/_hub-hero.scss
  styleguide/source/assets/scss/03-organisms/_membership.scss
  styleguide/source/assets/scss/04-templates/_one_column.scss
  styleguide/source/assets/scss/05-pages/_category.scss
Labels: in review, ready for review, sprint 50

#856 EWL-8015: Modal Implementation
  styleguide/source/assets/js/modal.js
  styleguide/source/assets/scss/02-molecules/_modal.scss
  styleguide/source/assets/scss/03-organisms/_category-index.scss
  styleguide/source/assets/scss/03-organisms/_subcategory-index.scss
  styleguide/source/assets/scss/04-templates/_two-column-right--75-25.scss
  styleguide/source/assets/scss/05-pages/_category.scss
Labels: ready for review

#857 bumped SG to 2.50.3
  styleguide/package-lock.json
  styleguide/package.json
Labels: ready for review
