Repository AmericanMedicalAssociation/ama-style-guide-2, pull requests merged in 2020-10, with the labels that each got.

#905 EWL-8288: Removed max-width for application content.
  styleguide/source/assets/scss/05-pages/_application.scss
Labels: ready for review

#907 bumped SG to 2.53.1
  styleguide/package-lock.json
  styleguide/package.json
Labels: ready for review

#906 EWL-8259: subcat tools resource block styling
  styleguide/source/assets/scss/02-molecules/_tool.scss
  styleguide/source/assets/scss/03-organisms/_tools.scss
Labels: ready for review

#912 EWL-8256: subcat video card
  styleguide/source/assets/scss/02-molecules/_video-block.scss
Labels: in review, ready for review

#904 EWL-8254: Explore topic section styling on sub-category pages
  styleguide/package-lock.json
  styleguide/source/assets/scss/03-organisms/_subcategory-index.scss
Labels: ready for review

#913 EWL-8284: Add styling to account for on-page anchor link offset when opening in…
  styleguide/source/assets/scss/02-molecules/_table-of-contents.scss
Labels: ready for review

#911 EWL-8253: subcat read more
  styleguide/source/assets/scss/00-base/_colors.scss
  styleguide/source/assets/scss/05-pages/_subcategory.scss
  styleguide/source/assets/scss/05-pages/_topic-index.scss
Labels: question

#914 bumped SG to 2.54.0
  styleguide/package-lock.json
  styleguide/package.json
Labels: ready for review

#910 EWL-8258: Add styling for article stub list header including layout builder.
  styleguide/source/assets/scss/01-atoms/_content-grouping-header.scss
Labels: ready for review

#918 EWL-8352: subcat mobile page overflow fix
  styleguide/source/assets/scss/01-atoms/_display-switch.scss
Labels: ready for review

#917 EWL-8263: Display images above text content for subcat search entries on mobile.
  styleguide/source/assets/scss/02-molecules/_subcategory-page-article-stub.scss
Labels: ready for review

#920 EWL-8265: Subcat | Include Explore Topics Module in Default State of Subcategory Pages
  styleguide/source/_patterns/03-organisms/subcategory-explore-topics.json
  styleguide/source/_patterns/03-organisms/subcategory-explore-topics.twig
  styleguide/source/_patterns/05-pages/subcategory.json
  styleguide/source/_patterns/05-pages/subcategory.twig
  styleguide/source/assets/scss/03-organisms/_subcategory-explore-topics.scss
Labels: ready for review

#919 EWL-8143: Adjust styling for people bio.
  styleguide/source/assets/scss/03-organisms/_bio-image-with-body.scss
  styleguide/source/assets/scss/05-pages/_people_bio.scss
Labels: ready for review

#921 bumped SG to 2.54.1
  styleguide/package-lock.json
  styleguide/package.json
Labels: ready for review

#927 EWL-8257: Adjusted styling for membership blocks to fit with new slim…
  styleguide/source/assets/scss/03-organisms/_membership.scss
Labels: ready for review

#916 EWL-8254: Additional mobile styling
  styleguide/source/assets/scss/03-organisms/_subcategory-index.scss
Labels: ready for review

#928 EWL-8253: Read more bug - restricting width with span
  styleguide/source/assets/scss/05-pages/_topic-index.scss
Labels: ready for review

#922 EWL-8284: Add workarounds for IE, opening an internal link externally…
  styleguide/source/assets/scss/02-molecules/_table-of-contents.scss
  styleguide/source/assets/scss/03-organisms/_main-navigation.scss
Labels: ready for review

#930 Change CSS so it passes gulp without error
  styleguide/source/assets/scss/02-molecules/_table-of-contents.scss
Labels: in review
