Repository AmericanMedicalAssociation/ama-style-guide-2, pull requests merged in 2020-06, with the labels that each got.

#808 EWL-7877: limited layout builder rows to 100% width
  styleguide/source/assets/scss/05-pages/_category.scss
Labels: ready for review

#810 EWL-7955: changed additional date colors to gray-50.
  styleguide/source/assets/scss/02-molecules/_event-stub.scss
  styleguide/source/assets/scss/03-organisms/_masthead.scss
Labels: ok to merge

#811 bumped SG to 2.48.3
  styleguide/package-lock.json
  styleguide/package.json
Labels: ready for review

#814 EWL-8028: icons essential tools resources component
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-audio-yellow.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-cme-yellow.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-external-site-yellow.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-internal-site-yellow.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-pdf-yellow.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-podcast-yellow.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-video-yellow.twig
  styleguide/source/_patterns/02-molecules/tool/tool-as-gated.json
  styleguide/source/_patterns/02-molecules/tool/tool.json
  styleguide/source/_patterns/02-molecules/tools-list.json
  styleguide/source/_patterns/03-organisms/tools.json
  styleguide/source/_patterns/05-pages/category.json
  styleguide/source/_patterns/05-pages/event.json
  styleguide/source/_patterns/05-pages/news/news-as-gated.json
  styleguide/source/_patterns/05-pages/news/news-with-jama-examples.json
  styleguide/source/_patterns/05-pages/people-bio.json
  styleguide/source/_patterns/05-pages/press-release.json
  styleguide/source/_patterns/05-pages/topic.json
  styleguide/source/assets/icons/svg/icon-audio-yellow.svg
  styleguide/source/assets/icons/svg/icon-cme-yellow.svg
  styleguide/source/assets/icons/svg/icon-external-site-yellow.svg
  styleguide/source/assets/icons/svg/icon-internal-site-yellow.svg
  styleguide/source/assets/icons/svg/icon-pdf-yellow.svg
  styleguide/source/assets/icons/svg/icon-podcast-yellow.svg
  styleguide/source/assets/icons/svg/icon-video-yellow.svg
  styleguide/source/assets/scss/01-atoms/_icons.scss
Labels: ready for review

#813 EWL-8012
  styleguide/source/_patterns/03-organisms/footer/footer.json
  styleguide/source/assets/scss/00-base/__01.mixins/_ama-button.scss
  styleguide/source/assets/scss/00-base/_colors.scss
  styleguide/source/assets/scss/01-atoms/_button.scss
  styleguide/source/assets/scss/03-organisms/_footer.scss
Labels: in review, ready for review

#817 EWL-8007: Redesign topic terms
  styleguide/source/_patterns/02-molecules/tags.json
  styleguide/source/_patterns/02-molecules/tags.twig
  styleguide/source/_patterns/05-pages/event.json
  styleguide/source/_patterns/05-pages/news/news-as-gated.json
  styleguide/source/_patterns/05-pages/news/news-with-jama-examples.json
  styleguide/source/_patterns/05-pages/news/news.json
  styleguide/source/_patterns/05-pages/people-bio.json
  styleguide/source/_patterns/05-pages/press-release.json
  styleguide/source/_patterns/05-pages/resource.json
  styleguide/source/assets/scss/00-base/_colors.scss
  styleguide/source/assets/scss/02-molecules/_tags.scss
Labels: in review, ready for review

#816 hr styling changes.
  styleguide/source/assets/scss/00-base/_colors.scss
  styleguide/source/assets/scss/05-pages/_news.scss
Labels: ready for review

#818 EWL-8008: Article Page Redesign Essential Tools and Services
  styleguide/source/assets/scss/02-molecules/_tool.scss
  styleguide/source/assets/scss/03-organisms/_tools.scss
Labels: has D8 dependency, ok to merge

#822 EWL-8062: Right align images
  styleguide/source/assets/scss/00-base/__01.mixins/_lists.scss
  styleguide/source/assets/scss/01-atoms/_image.scss
Labels: ready for review

#820 EWL-8005: article headline bio
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-email-brand-hover.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-email-brand.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-facebook-brand-hover.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-facebook-brand.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-linkedin-brand-hover.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-linkedin-brand.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-twitter-blue.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-twitter-brand-hover.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-twitter-brand.twig
  styleguide/source/_patterns/03-organisms/news_header/news_header.json
  styleguide/source/_patterns/03-organisms/news_header/news_header.md
  styleguide/source/_patterns/03-organisms/news_header/news_header.twig
  styleguide/source/assets/icons/svg/icon-email-brand-hover.svg
  styleguide/source/assets/icons/svg/icon-email-brand.svg
  styleguide/source/assets/icons/svg/icon-facebook-brand-hover.svg
  styleguide/source/assets/icons/svg/icon-facebook-brand.svg
  styleguide/source/assets/icons/svg/icon-linkedin-brand-hover.svg
  styleguide/source/assets/icons/svg/icon-linkedin-brand.svg
  styleguide/source/assets/icons/svg/icon-twitter-brand-hover.svg
  styleguide/source/assets/icons/svg/icon-twitter-brand.svg
  styleguide/source/assets/scss/02-molecules/_inline-bio.scss
  styleguide/source/assets/scss/02-molecules/_social-share.scss
  styleguide/source/assets/scss/04-templates/_two_column-right.scss
  styleguide/source/assets/scss/05-pages/_news.scss
Labels: ready for review

#827 bumped SG to 2.49.3
  styleguide/package-lock.json
  styleguide/package.json
Labels: ready for review

#830 EWL-8006: Article Page Redesign - Body of Page Hierarchy (TOC)
  styleguide/build.config.json
  styleguide/source/assets/js/toc.js
  styleguide/source/assets/scss/02-molecules/_table-of-contents.scss
Labels: has D8 dependency, ready for review

#831 EWL-8012: Removing All caps from subscribe footer button.
  styleguide/source/assets/scss/03-organisms/_footer.scss
Labels: in review

#821 EWL-8010: Adding Styles per Redesign for article stub specifics for featured stories
  styleguide/source/assets/scss/02-molecules/_article-stub.scss
  styleguide/source/assets/scss/03-organisms/_column-teaser.scss
Labels: ready for review

#828 EWL-8015: Article Page Redesign_Modal Dialog Feature for Chart Images
  styleguide/build.config.json
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-modal-close.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-modal-expand.twig
  styleguide/source/_patterns/02-molecules/modal.json
  styleguide/source/_patterns/02-molecules/modal.md
  styleguide/source/_patterns/02-molecules/modal.twig
  styleguide/source/_patterns/05-pages/news/news.json
  styleguide/source/_patterns/05-pages/news/news.twig
  styleguide/source/assets/images/icon-modal-close.svg
  styleguide/source/assets/js/modal.js
  styleguide/source/assets/scss/01-atoms/_image.scss
  styleguide/source/assets/scss/02-molecules/_modal.scss
Labels: ok to merge

#829 EWL-7951: convert promo as inline
  styleguide/source/assets/scss/00-base/_colors.scss
  styleguide/source/assets/scss/02-molecules/_promo.scss
  styleguide/source/assets/scss/05-pages/_news.scss
Labels: has D8 dependency, ready for review

#832 EWL-8008: Article Page Redesign Essential Tools and Services
  styleguide/source/assets/scss/03-organisms/_tools.scss
  styleguide/source/assets/scss/04-templates/_two_column-right.scss
Labels: question

#835 News Redesign QA feedback
  styleguide/source/assets/scss/02-molecules/_inline-bio.scss
  styleguide/source/assets/scss/02-molecules/_promo.scss
  styleguide/source/assets/scss/02-molecules/_social-share.scss
  styleguide/source/assets/scss/05-pages/_news.scss
Labels: in review, ready for review

#836 EWL-8010 Featured stories fix per QA Mobile
  styleguide/source/assets/scss/02-molecules/_article-stub.scss
Labels: ready for review

#839 set all 'none' set images to float right. Addressed some margin issues.
  styleguide/source/assets/scss/01-atoms/_image.scss
  styleguide/source/assets/scss/02-molecules/_social-share.scss
  styleguide/source/assets/scss/03-organisms/_masthead.scss
  styleguide/source/assets/scss/04-templates/_two-column-right--full-width.scss
Labels: ok to merge
