Repository AmericanMedicalAssociation/ama-style-guide-2, pull requests merged in 2020-03, with the labels that each got.

#774 EWL-7866: create molecule and variation of comments
  styleguide/build.config.json
  styleguide/package-lock.json
  styleguide/package.json
  styleguide/source/_patterns/01-atoms/date-block.twig
  styleguide/source/_patterns/01-atoms/date-block~as-inline.json
  styleguide/source/_patterns/02-molecules/forum-comments/forum-comments.json
  styleguide/source/_patterns/02-molecules/forum-comments/forum-comments.twig
  styleguide/source/_patterns/02-molecules/forum-comments/forum-comments~as-thread.json
  styleguide/source/assets/scss/02-molecules/_forum-comments.scss
Labels: ready for review

#773 changed blockquote layout to use flexbox.
  styleguide/source/assets/scss/01-atoms/_block-quote.scss
Labels: ready for review

#775 bumped SG to 2.45.0
  styleguide/package-lock.json
  styleguide/package.json
Labels: ready for review

#779 EWL-7866: Create molecule and variation of comments in SG2
  styleguide/source/assets/scss/02-molecules/_forum-comments.scss
Labels: ok to merge

#776 EWL-7866: Create molecule and variation of comments in SG2 - mobile
  styleguide/source/assets/scss/02-molecules/_forum-comments.scss
Labels: ok to merge

#777 EWL-7896: Create block quote styling within forum comments
  styleguide/source/_patterns/01-atoms/block-quote/block-quote.json
  styleguide/source/_patterns/01-atoms/block-quote/block-quote.twig
  styleguide/source/_patterns/01-atoms/paragraph.twig
  styleguide/source/_patterns/02-molecules/block-quote/block-quote.json
  styleguide/source/_patterns/02-molecules/block-quote/block-quote.md
  styleguide/source/_patterns/02-molecules/block-quote/block-quote.twig
  styleguide/source/_patterns/02-molecules/block-quote/block-quote~as-forum-comment.json
  styleguide/source/assets/scss/00-base/__01.mixins/_font-variables.scss
  styleguide/source/assets/scss/02-molecules/_block-quote.scss
Labels: ok to merge

#778 EWL-7884: Forums listing element in SG2
  styleguide/source/_patterns/02-molecules/forum-listing/forum-listing.json
  styleguide/source/_patterns/02-molecules/forum-listing/forum-listing.twig
  styleguide/source/_patterns/03-organisms/forum-list/forum-list.json
  styleguide/source/_patterns/03-organisms/forum-list/forum-list.twig
  styleguide/source/assets/scss/02-molecules/_forum-list.scss
  styleguide/source/assets/scss/02-molecules/_forum-listing.scss
Labels: forums, question

#780 Feature/ewl 7869 forum topic templates
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-print.twig
  styleguide/source/_patterns/02-molecules/Forum-topic/forum-topic.json
  styleguide/source/_patterns/02-molecules/Forum-topic/forum-topic.md
  styleguide/source/_patterns/02-molecules/Forum-topic/forum-topic.twig
  styleguide/source/assets/icons/svg/icon-print.svg
  styleguide/source/assets/scss/02-molecules/_forum-topic.scss
Labels: forums, ok to merge

#782 bumped SG to 2.45.1
  styleguide/package-lock.json
  styleguide/package.json
Labels: ready for review

#785 Feature/ewl 7890 new forum topic page
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-question.twig
  styleguide/source/assets/icons/svg/icon-question.svg
  styleguide/source/assets/scss/02-molecules/_forum-add-topic-form.scss
Labels: forums, ok to merge

#784 EWL-7891: Comment title is only for responses to original topic post
  styleguide/source/assets/scss/02-molecules/_forum-comments.scss
Labels: forums, has D8 dependency, ok to merge

#787 bumped SG to 2.45.2
  styleguide/package-lock.json
  styleguide/package.json
Labels: ready for review

#786 EWL-7885: Attach the new Forum listing style to Drupal
  styleguide/source/assets/scss/02-molecules/_forum-listing.scss
Labels: forums, ready for review

#789 EWL-7885: Attach the new Forum listing style to Drupal
  styleguide/source/assets/scss/02-molecules/_forum-listing.scss
Labels: ready for review

#790 Removed margin on first link of the edit links on a comment
  styleguide/source/assets/scss/02-molecules/_forum-comments.scss
Labels: ready for review

#791 bumped SG to 2.45.4
  styleguide/package-lock.json
  styleguide/package.json
Labels: ready for review

#793 EWL-7598: Author Article Index Page
  styleguide/source/_patterns/03-organisms/bio-image-with-body.md
  styleguide/source/_patterns/03-organisms/bio-image-with-body.twig
  styleguide/source/_patterns/03-organisms/bio-section.twig
  styleguide/source/_patterns/03-organisms/masthead/masthead.twig
  styleguide/source/_patterns/03-organisms/masthead/masthead~as-no-title.json
  styleguide/source/_patterns/03-organisms/user-article-listing.json
  styleguide/source/_patterns/03-organisms/user-article-listing.twig
  styleguide/source/_patterns/05-pages/people-bio.json
  styleguide/source/_patterns/05-pages/people-bio.twig
  styleguide/source/assets/scss/02-molecules/_inline-bio.scss
  styleguide/source/assets/scss/03-organisms/_bio-image-with-body.scss
  styleguide/source/assets/scss/03-organisms/_bio-section.scss
  styleguide/source/assets/scss/03-organisms/_masthead.scss
  styleguide/source/assets/scss/03-organisms/_user-article-listing.scss
  styleguide/source/assets/scss/05-pages/_people_bio.scss
Labels: has D8 dependency, ok to merge, ready for review

#794 bumped SG to 2.46.0
  styleguide/package-lock.json
  styleguide/package.json
Labels: ready for review

#792 bugfix/EWL-7934: added right margin to left aligned embedded entity.
  styleguide/source/assets/scss/01-atoms/_image.scss
Labels: ready for review

#795 EWL-7598: Author Article Index Page
  styleguide/source/assets/scss/02-molecules/_inline-bio.scss
  styleguide/source/assets/scss/03-organisms/_masthead.scss
Labels: ready for review
