Repository AmericanMedicalAssociation/ama-style-guide-2, pull requests merged in 2020-09, with the labels that each got.

#890 EWL-8273: updated font weight variables to have 600 as default, to force simpua…
  styleguide/source/assets/scss/00-base/__01.mixins/_font-variables.scss
  styleguide/source/assets/scss/05-pages/_topic-index.scss
Labels: in review, priority, ready for review

#891 bumped SG to 2.52.0
  styleguide/package-lock.json
  styleguide/package.json
Labels: ready for review

#889 Fixes vertical bottom padding for social share in index pages
  styleguide/source/assets/scss/05-pages/_category.scss
Labels: in review, priority, ready for review

#894 Creates style and js functionality for application header nav
  styleguide/build.config.json
  styleguide/source/assets/js/application-dropdown.js
  styleguide/source/assets/scss/03-organisms/_application-nav.scss
Labels: ready for review

#901 EWL-8145: Add rule to hide mobile toc if add toc field is not checked
  styleguide/source/assets/scss/05-pages/_news.scss
Labels: ready for review

#896 Application page styling
  styleguide/source/assets/scss/05-pages/_application.scss
Labels: ready for review

#900 EWL-8277: Adjust styling of border line below social icons on index pages
  styleguide/source/assets/scss/05-pages/_category.scss
  styleguide/source/assets/scss/05-pages/_topic-index.scss
Labels: ready for review

#899 EWL-8231: Fix icon styling on index page search for mobile
  styleguide/source/assets/scss/01-atoms/_search-field.scss
Labels: ready for review

#898 EWL-8186: Adjusted padding below rule line under featured stories section on ne…
  styleguide/source/assets/scss/02-molecules/_article-stub.scss
Labels: ready for review

#895 EWL-8228: added video sizing and legacy align.
  styleguide/source/assets/scss/01-atoms/_image.scss
Labels: ok to merge

#902 EWL-8140: left justified basic page
  styleguide/source/assets/scss/04-templates/_one_column.scss
Labels: in review, ready for review

#903 bumped sg to 2.53.0
  styleguide/package-lock.json
  styleguide/package.json
Labels: ready for review
