Repository AmericanMedicalAssociation/ama-style-guide-2, pull requests merged in 2020-02, with the labels that each got.

#751 Feature/ewl 7791 sitewide unordered list styling
  styleguide/source/assets/scss/00-base/__01.mixins/_gutter_mixin.scss
  styleguide/source/assets/scss/00-base/__01.mixins/_lists.scss
  styleguide/source/assets/scss/01-atoms/_unordered-list.scss
  styleguide/source/assets/scss/02-molecules/_promo.scss
  styleguide/source/assets/scss/02-molecules/hub/_hub-hero.scss
  styleguide/source/assets/scss/03-organisms/_membership.scss
Labels: in review, ready for review

#749 Set US verification checkbox label to initial capitalization
  styleguide/source/assets/scss/02-molecules/_subscribe-promo.scss
Labels: ready for review

#750 EWL-7782: Videos do not display on the Hub page template in mobile
  styleguide/source/assets/scss/02-molecules/hub/_hub-hero.scss
Labels: ready for review

#752 added unordered list styles to styleguide as pattern.
  styleguide/source/_patterns/01-atoms/lists/unordered-list-presentation.json
  styleguide/source/_patterns/01-atoms/lists/unordered-list-presentation.md
  styleguide/source/_patterns/01-atoms/lists/unordered-list-presentation.twig
  styleguide/source/_patterns/01-atoms/lists/unordered-list.json
  styleguide/source/_patterns/01-atoms/lists/unordered-list.md
  styleguide/source/_patterns/01-atoms/lists/unordered-list.twig
Labels: ready for review

#753 bumped SG release to v2.44.0
  styleguide/package-lock.json
  styleguide/package.json
Labels: ready for review

#754 bumped version in composer.json
  styleguide/package-lock.json
  styleguide/package.json
Labels: ready for review

#756 excluded share list from UL rules.
  styleguide/source/assets/scss/02-molecules/_social-share.scss
Labels: in review, ready for review

#755 set h2 and uls to myriad-pro.
  styleguide/source/assets/scss/00-base/_typography.scss
Labels: ready for review

#759 changed default width of 50/50 text panel
  styleguide/source/assets/scss/02-molecules/hub/_hub-hero.scss
Labels: in review, ready for review

#757 Bugfix/ewl 7855 unsupported list not supported in all custom block types
  styleguide/source/assets/scss/00-base/__01.mixins/_lists.scss
  styleguide/source/assets/scss/02-molecules/_partner-promo.scss
  styleguide/source/assets/scss/02-molecules/_product.scss
  styleguide/source/assets/scss/02-molecules/_promo.scss
  styleguide/source/assets/scss/02-molecules/_subscribe-promo.scss
  styleguide/source/assets/scss/04-templates/_one_column.scss
Labels: in review

#760 bumped SG to 2.44.2
  styleguide/package-lock.json
  styleguide/package.json
Labels: ready for review

#761 Bugfix/ewl 7856 unordered lists only 2 levels
  styleguide/source/assets/scss/00-base/__01.mixins/_lists.scss
  styleguide/source/assets/scss/01-atoms/_tabs.scss
  styleguide/source/assets/scss/01-atoms/_unordered-list.scss
  styleguide/source/assets/scss/02-molecules/_jama.scss
  styleguide/source/assets/scss/02-molecules/_partner-promo.scss
  styleguide/source/assets/scss/02-molecules/_product.scss
  styleguide/source/assets/scss/02-molecules/_promo.scss
  styleguide/source/assets/scss/02-molecules/_social-share.scss
  styleguide/source/assets/scss/02-molecules/_subscribe-promo.scss
  styleguide/source/assets/scss/02-molecules/hub/_hub-hero.scss
  styleguide/source/assets/scss/03-organisms/_footer.scss
  styleguide/source/assets/scss/03-organisms/_membership.scss
  styleguide/source/assets/scss/03-organisms/_product-nav.scss
  styleguide/source/assets/scss/04-templates/_one_column.scss
Labels: ok to merge

#762 bumped SG to 2.44.3
  styleguide/package-lock.json
  styleguide/package.json
Labels: ready for review

#763 fixed regression with lists next to floated elements.
  styleguide/source/assets/scss/00-base/__01.mixins/_lists.scss
  styleguide/source/assets/scss/01-atoms/_unordered-list.scss
Labels: in review, ready for review

#764 bumped SG to 2.44.4
  styleguide/package-lock.json
  styleguide/package.json
Labels: ok to merge

#765 bumped SG to 2.44.5
  styleguide/package-lock.json
  styleguide/package.json
Labels: ready for review

#766 restricted UL styles. Rolled back previous work to deal with regressi…
  styleguide/source/assets/scss/00-base/_typography.scss
  styleguide/source/assets/scss/01-atoms/_tabs.scss
  styleguide/source/assets/scss/01-atoms/_unordered-list.scss
  styleguide/source/assets/scss/02-molecules/_tags.scss
  styleguide/source/assets/scss/03-organisms/_footer.scss
Labels: ok to merge

#767 bumped SG to 2.44.6
  styleguide/package-lock.json
  styleguide/package.json
Labels: ready for review

#768 corrected nested list margin regression.
  styleguide/source/assets/scss/00-base/__01.mixins/_lists.scss
  styleguide/source/assets/scss/00-base/_typography.scss
Labels: ok to merge

#769 bumped SG to 2.44.7
  styleguide/package-lock.json
  styleguide/package.json
Labels: ok to merge

#770 refactored breakpoints for body-copy lists.
  styleguide/source/assets/scss/00-base/__01.mixins/_lists.scss
Labels: ok to merge

#771 bumped SG to 2.44.8
  styleguide/package-lock.json
  styleguide/package.json
Labels: ready for review
