Repository AmericanMedicalAssociation/ama-style-guide-2, pull requests merged in 2020-08, with the labels that each got.

#859 Bugfix/ewl 7792 ordered list fixes
  styleguide/source/assets/scss/01-atoms/_ordered-list.scss
  styleguide/source/assets/scss/05-pages/_news.scss
Labels: ready for review

#860 EWL-8015: bugfixes modal style reworking for centered image with left justified icon, ne…
  styleguide/source/assets/scss/02-molecules/_modal.scss
Labels: ready for review

#863 Feature/ewl 8123 index description copy
  styleguide/build.config.json
  styleguide/source/assets/js/index-page.js
  styleguide/source/assets/scss/00-base/__01.mixins/_font-variables.scss
  styleguide/source/assets/scss/00-base/_forms.scss
  styleguide/source/assets/scss/01-atoms/_content-grouping-header.scss
  styleguide/source/assets/scss/01-atoms/_display-switch.scss
  styleguide/source/assets/scss/01-atoms/_listicle.scss
  styleguide/source/assets/scss/01-atoms/_menu-icon.scss
  styleguide/source/assets/scss/01-atoms/_table.scss
  styleguide/source/assets/scss/01-atoms/_text-field.scss
  styleguide/source/assets/scss/02-molecules/_alert.scss
  styleguide/source/assets/scss/02-molecules/_content-with-label.scss
  styleguide/source/assets/scss/02-molecules/_event-stub.scss
  styleguide/source/assets/scss/02-molecules/_forum-comments.scss
  styleguide/source/assets/scss/02-molecules/_forum-listing.scss
  styleguide/source/assets/scss/02-molecules/_hero-evergreen.scss
  styleguide/source/assets/scss/02-molecules/_inline-bio.scss
  styleguide/source/assets/scss/02-molecules/_link-list.scss
  styleguide/source/assets/scss/02-molecules/_partner-promo.scss
  styleguide/source/assets/scss/02-molecules/_search-header.scss
  styleguide/source/assets/scss/02-molecules/_social-share.scss
  styleguide/source/assets/scss/02-molecules/_subcategory-hero.scss
  styleguide/source/assets/scss/02-molecules/_subcategory-page-article-stub.scss
  styleguide/source/assets/scss/02-molecules/_table-of-contents.scss
  styleguide/source/assets/scss/02-molecules/search-result/_search-result.scss
  styleguide/source/assets/scss/03-organisms/_bp-table.scss
  styleguide/source/assets/scss/03-organisms/_category-index.scss
  styleguide/source/assets/scss/03-organisms/_category-navigation-menu.scss
  styleguide/source/assets/scss/03-organisms/_masthead.scss
  styleguide/source/assets/scss/03-organisms/_org-nav.scss
  styleguide/source/assets/scss/03-organisms/_subcategory-exploration.scss
  styleguide/source/assets/scss/03-organisms/_subcategory-index.scss
  styleguide/source/assets/scss/05-pages/_news.scss
  styleguide/source/assets/scss/05-pages/_topic-index.scss
Labels: in review, ready for review

#862 EWL-8107: Change padding top and bottom per design specifications.
  styleguide/source/assets/scss/02-molecules/_tool.scss
Labels: ready for review

#864 bumped SG to 2.51.0
  styleguide/package-lock.json
  styleguide/package.json
  styleguide/source/assets/scss/05-pages/_category.scss
Labels: ready for review

#865 added semicolons
  styleguide/source/assets/js/index-page.js
Labels: ready for review

#866 bumped SG to 2.51.1
  styleguide/package-lock.json
  styleguide/package.json
Labels: ready for review

#868 Style for topic term search results
  styleguide/source/assets/scss/02-molecules/_subcategory-page-article-stub.scss
Labels: has D8 dependency, ready for review

#867 EWL-8118: related content styles.
  styleguide/source/assets/scss/00-base/_colors.scss
  styleguide/source/assets/scss/05-pages/_topic-index.scss
Labels: ready for review

#869 EWL-8122: Index Page Redesign - Right Rail Promos
  styleguide/source/assets/scss/04-templates/_two-column-right--75-25.scss
Labels: ready for review

#858 EWL-8085: Solve issue on hub cards IE div empty.
  styleguide/source/assets/scss/02-molecules/hub/_hub-card.scss
Labels: ready for review

#873 Bugxif/modal progress
  styleguide/source/assets/scss/02-molecules/_modal.scss
Labels: ready for review

#874 Bugfix/EWL: 8123 index page description iphone
  styleguide/source/assets/js/index-page.js
  styleguide/source/assets/scss/00-base/_colors.scss
  styleguide/source/assets/scss/05-pages/_topic-index.scss
Labels: in review, ready for review

#872 EWL-8118: Index Page Redesign_Related Topics
  styleguide/source/assets/scss/03-organisms/_masthead.scss
  styleguide/source/assets/scss/05-pages/_topic-index.scss
Labels: in review, ready for review

#876 EWL-8194: margin change
  styleguide/source/assets/scss/02-molecules/_tags.scss
Labels: in review, ready for review

#877 Release/v2.51.3
  styleguide/package-lock.json
  styleguide/package.json
Labels: ready for review

#871 EWL-XXX: Solving Issue IE Hub Card IE-11
  styleguide/source/assets/scss/02-molecules/hub/_hub-card.scss
Labels: in review, ready for review

#878 bumped SG to 2.51.4
  styleguide/package-lock.json
  styleguide/package.json
Labels: ready for review

#880 EWL-8123: Index Page Redesign_Description Mobile Fix
  styleguide/source/assets/scss/05-pages/_topic-index.scss
Labels: ready for review

#879 EWL-8118 Address UAT Fail Feedback (Remove extra Related Topics whitespace)
  styleguide/source/assets/scss/05-pages/_topic-index.scss
Labels: ready for review

#882 EWL-8015: Article Page Redesign_Modal Dialog Feature for Chart Images
  styleguide/source/assets/scss/02-molecules/_modal.scss
Labels: has D8 dependency, ok to merge

#884 EWL-8015: Article Page Redesign_Modal Dialog Feature for Chart Images
  styleguide/source/assets/scss/02-molecules/_modal.scss
Labels: ready for review

#885 removed position relative from listicle lis
  styleguide/source/assets/scss/01-atoms/_listicle.scss
Labels: ready for review

#888 Styling for two column left layout
  styleguide/source/assets/scss/04-templates/_two-column-left--75-25.scss
Labels: ready for review

#887 Bugfix/ewl 8015 modal fixes
  styleguide/source/assets/js/index-page.js
  styleguide/source/assets/scss/00-base/_theme-variables.scss
  styleguide/source/assets/scss/01-atoms/_image.scss
  styleguide/source/assets/scss/01-atoms/_listicle.scss
  styleguide/source/assets/scss/01-atoms/_videos.scss
  styleguide/source/assets/scss/02-molecules/_modal.scss
Labels: ready for review

#881 Fix best bet block styling on search results page
  styleguide/source/assets/scss/05-pages/_search-results.scss
Labels: ready for review
