Repository AmericanMedicalAssociation/ama-style-guide-2, pull requests merged in 2020-11, with the labels that each got.

#925 EWL-8255: Page Grouping (PG) Custom Block
  styleguide/source/assets/scss/00-base/_colors.scss
  styleguide/source/assets/scss/02-molecules/_page-grouping.scss
Labels: has D8 dependency, ready for review

#924 EWL-8144: Add rule to divide bio and index items on People Bio template
  styleguide/source/assets/scss/02-molecules/_tags.scss
  styleguide/source/assets/scss/03-organisms/_user-article-listing.scss
  styleguide/source/assets/scss/05-pages/_people_bio.scss
Labels: ok to merge, ready for review

#926 EWL-8339: Fix hover state of Related Content blocks on Article pages.
  styleguide/source/assets/scss/03-organisms/_column-teaser.scss
Labels: in review, ready for review

#939 bumped SG to 2.55.0
  styleguide/package-lock.json
  styleguide/package.json
Labels: ready for review

#941 EWL-8376: Adding marging to the bottom of custom video block according specs
  styleguide/source/assets/scss/02-molecules/_video-block.scss
Labels: ready for review

#936 evergreen hero fixes + embed button icon
  styleguide/source/assets/images/30-70-paragraph-embed-icon.png
  styleguide/source/assets/scss/02-molecules/_hero-evergreen.scss
Labels: ready for review

#935 EWL-8370: Allowing tags to be rendered properly on subtitle full text and trimmed text.
  styleguide/source/assets/js/index-page.js
Labels: in review, ready for review

#937 EWL-8332: Styling for clear search element on taxonomy pages.
  styleguide/source/assets/scss/01-atoms/_search-field.scss
  styleguide/source/assets/scss/02-molecules/_subcategory-page-article-stub.scss
  styleguide/source/assets/scss/03-organisms/_category-index.scss
  styleguide/source/assets/scss/03-organisms/_subcategory-index.scss
  styleguide/source/assets/scss/05-pages/_topic-index.scss
Labels: ready for review

#938 EWL-8382: Fixes padding issues for subcat article stub lists.
  styleguide/source/assets/scss/01-atoms/_content-grouping-header.scss
  styleguide/source/assets/scss/02-molecules/_article-stub.scss
  styleguide/source/assets/scss/03-organisms/_category-page-article-stub.scss
Labels: ready for review

#942 EWL-8143: people bio styling adjustment
  styleguide/source/assets/scss/02-molecules/_inline-bio.scss
  styleguide/source/assets/scss/03-organisms/_bio-image-with-body.scss
Labels: Needs second review, ready for review

#943 Move up right rail promos vertically on Subcategory pages.
  styleguide/source/assets/scss/04-templates/_two-column-right--75-25.scss
  styleguide/source/assets/scss/05-pages/_subcategory.scss
Labels: Needs second review, ready for review

#945 bumped SG to 2.55.1
  styleguide/package-lock.json
  styleguide/package.json
Labels: ready for review

#947 EWL-8232: Fixes tablet bottom padding for membership blocks on article pages.
  styleguide/source/assets/scss/03-organisms/_membership.scss
Labels: ready for review

#933 EWL-8304: Styling for Article Stub List embedded into article body text.
  styleguide/source/assets/scss/01-atoms/_content-grouping-header.scss
  styleguide/source/assets/scss/02-molecules/_article-stub.scss
  styleguide/source/assets/scss/02-molecules/_inline-bio.scss
  styleguide/source/assets/scss/05-pages/_news.scss
Labels: Needs second review, ready for review

#950 Fix js error causing topic search to not run more than once.
  styleguide/source/assets/js/index-page.js
Labels: ready for review

#944 Ewl 8260: subcat search full copy searchable
  styleguide/source/assets/scss/02-molecules/_subcategory-page-article-stub.scss
Labels: has D8 dependency, question

#946 EWL-8400: EWL-8400: updated twig to show block only once, and to be able to deal with mor
  styleguide/source/assets/scss/03-organisms/_category-page-article-stub.scss
  styleguide/source/assets/scss/03-organisms/_four-up-teaser.scss
  styleguide/source/assets/scss/03-organisms/_masthead.scss
  styleguide/source/assets/scss/05-pages/_category.scss
Labels: ready for review

#948 EWL-8255: Added bottom margin as per PR feedback.
  styleguide/source/assets/images/arrow-right.svg
  styleguide/source/assets/scss/02-molecules/_page-grouping.scss
Labels: Needs second review, ready for review

#951 bumped SG to 2.55.2
  styleguide/package-lock.json
  styleguide/package.json
Labels: ready for review

#955 Adds border back into cat/subcat listing view
  styleguide/source/assets/scss/02-molecules/_subcategory-page-article-stub.scss
Labels: ready for review

#956 EWL-8301: styles for atricle page grouping block.
  styleguide/source/assets/scss/02-molecules/_page-grouping.scss
  styleguide/source/assets/scss/02-molecules/_table-of-contents.scss
  styleguide/source/assets/scss/05-pages/_news.scss
Labels: Pending Travis Build, has D8 dependency, ok to merge

#957 updated category layout rules to keep left blocks aligned top.
  styleguide/source/assets/scss/05-pages/_category.scss
Labels: ready for review

#954 bumped SG to 2.55.3
  styleguide/package-lock.json
  styleguide/package.json
Labels: ready for review

#959 EWL-8301: updated article page grouping styles.
  styleguide/source/assets/scss/02-molecules/_page-grouping.scss
Labels: Pending Travis Build, has D8 dependency, ok to merge

#960 EWL-8309: 30 70 fixes
  styleguide/source/assets/scss/02-molecules/_hero-evergreen.scss
Labels: Pending Travis Build, has D8 dependency, ok to merge

#963 bumped SG to 2.55.5
  styleguide/package-lock.json
  styleguide/package.json
Labels: ready for review
