Repository AmericanMedicalAssociation/ama-style-guide-2, pull requests merged in 2021-07, with the labels that each got.

#1049 EWL-8885: Adjust CTA button styling in 30/70 custom block.
  styleguide/source/assets/scss/02-molecules/_hero-evergreen.scss
Labels: ready for review

#1052 bumped version to 2.64.0
  styleguide/package-lock.json
  styleguide/package.json
Labels: ready for review

#1053 EWL-8904: Styling and styleguide page for content type list view.
  styleguide/source/_patterns/03-organisms/content-type-index.json
  styleguide/source/_patterns/03-organisms/content-type-index.md
  styleguide/source/_patterns/03-organisms/content-type-index.twig
  styleguide/source/_patterns/05-pages/content-type-listing.json
  styleguide/source/_patterns/05-pages/content-type-listing.md
  styleguide/source/_patterns/05-pages/content-type-listing.twig
  styleguide/source/assets/scss/05-pages/_content-type-listing.scss
Labels: priority, ready for review

#1048 EWL-8878: Lightbox | Not working in ordered and unordered lists
  styleguide/source/assets/scss/02-molecules/_modal.scss
Labels: in review, priority, ready for review

#1051 EWL-8884: subcat read more android tablet fix.
  styleguide/source/assets/js/index-page.js
Labels: priority, ready for review

#1055 EWL-8846: Styles series tag to related article block series content
  styleguide/source/assets/scss/02-molecules/_series-tag.scss
Labels: ready for review

#1057 EWL-8846: Fixes series tags in article stubs when no image present.
  styleguide/source/assets/scss/02-molecules/_series-tag.scss
Labels: ready for review

#1058 bumped version to 2.64.3
  styleguide/package-lock.json
  styleguide/package.json
Labels: ready for review

#1059 EWL-0: Fixes whitespace bug on homepage when critical css loads.
  styleguide/source/assets/scss/03-organisms/_main-navigation.scss
Labels: priority, ready for review

#1060 bumped version to 2.64.4
  styleguide/package-lock.json
  styleguide/package.json
Labels: ready for review
