Repository AmericanMedicalAssociation/ama-style-guide-2, pull requests merged in 2021-06, with the labels that each got.

#1041 EWL-8823: Fix series index load more button styling.
  styleguide/source/assets/scss/05-pages/_series.scss
Labels: priority, ready for review

#1042 bumped version to 2.62.2
  styleguide/package-lock.json
  styleguide/package.json
Labels: ready for review

#1044 EWL-8751: Fix subscribe button footer styling on mobile.
  styleguide/source/assets/scss/03-organisms/_footer.scss
Labels: ready for review

#1043 EWL-8840: Styling for series tag.
  styleguide/source/assets/scss/02-molecules/_series-tag.scss
Labels: ok to merge, ready for review

#1045 bumped version to 2.63.0
  styleguide/package-lock.json
  styleguide/package.json
Labels: ready for review

#1047 EWL-8774: Gating Forms
  styleguide/source/assets/scss/01-atoms/_gate.scss
Labels: ready for review

#1050 EWL-8438: Adjust styling and script for load more section on topic an…
  styleguide/source/assets/js/index-page.js
  styleguide/source/assets/scss/05-pages/_topic-index.scss
Labels: ready for review

#1046 Adjust alert box behavior to prevent shifting of page content on load.
  styleguide/source/assets/js/alert.js
  styleguide/source/assets/scss/02-molecules/_alert.scss
Labels: ready for review
