Repository AmericanMedicalAssociation/ama-style-guide-2, pull requests merged in 2021-09, with the labels that each got.

#1068 EWL-9032: Adds annual/interim module mock ups to styleguide.
  styleguide/source/_patterns/03-organisms/annual-interim-meeting-block/annual-interim-meeting-block.json
  styleguide/source/_patterns/03-organisms/annual-interim-meeting-block/annual-interim-meeting-block.md
  styleguide/source/_patterns/03-organisms/annual-interim-meeting-block/annual-interim-meeting-block.twig
  styleguide/source/_patterns/03-organisms/annual-interim-meeting-block/annual-interim-meeting-block~active.json
  styleguide/source/assets/images/dot_pattern_web.svg
  styleguide/source/assets/scss/03-organisms/_annual-interum-block.scss
Labels: ready for review

#1064 EWL-9006: Fixes button functionality on header nav when sticky class is applied.
  styleguide/source/assets/scss/03-organisms/_main-navigation.scss
Labels: ready for review

#1070 EWL-8997: People Bio Template | Add vocabulary for pronouns
  styleguide/source/_patterns/03-organisms/bio-image-with-body.twig
  styleguide/source/assets/scss/03-organisms/_bio-image-with-body.scss
Labels: ready for review, in review

#1071 EWL-9008: CTA and messaging issues with Morning Rounds right rail promo
  styleguide/source/assets/scss/02-molecules/_subscribe-promo.scss
Labels: ready for review, in review

#1073 EWL-8596: Prevents search forms from submitting if nothing is entered…
  styleguide/source/assets/js/main-navigation.js
Labels: ready for review

#1065 EWL-8894: SERP- Results display too low on page.
  styleguide/source/assets/scss/04-templates/_two_column-left.scss
Labels: ready for review

#1072 EWL-8953: Updated styling for search bar on search page.
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-search-purple.twig
  styleguide/source/assets/icons/svg/icon-search-purple.svg
  styleguide/source/assets/scss/01-atoms/_icons.scss
  styleguide/source/assets/scss/01-atoms/_search-field.scss
  styleguide/source/assets/scss/02-molecules/_search-header.scss
  styleguide/source/assets/scss/04-templates/_two_column-left.scss
Labels: question

#1069 EWL-9037: Adds homepage social module designs to style guide.
  styleguide/source/_patterns/03-organisms/homepage-social-module/homepage-social-module-no-feature.json
  styleguide/source/_patterns/03-organisms/homepage-social-module/homepage-social-module-no-feature.twig
  styleguide/source/_patterns/03-organisms/homepage-social-module/homepage-social-module-three-up.json
  styleguide/source/_patterns/03-organisms/homepage-social-module/homepage-social-module-three-up.twig
  styleguide/source/_patterns/03-organisms/homepage-social-module/homepage-social-module.json
  styleguide/source/_patterns/03-organisms/homepage-social-module/homepage-social-module.md
  styleguide/source/_patterns/03-organisms/homepage-social-module/homepage-social-module.twig
  styleguide/source/assets/scss/03-organisms/_homepage-social-modual.scss
Labels: ready for review

#1075 EWL-9082: fixed incorrect icon positioning.
  styleguide/source/assets/scss/01-atoms/_select-menu.scss
Labels: ready for review

#1076 bumped release to v2.66.1
  styleguide/package-lock.json
  styleguide/package.json
Labels: ready for review

#1077 EWL-8973: Updated Annual/Interim module styling to account for longer link text.
  styleguide/source/assets/scss/03-organisms/_annual-interum-block.scss
Labels: priority, ready for review

#1079 EWL-8973: Annual Interim styling improvements.
  styleguide/source/assets/scss/03-organisms/_annual-interum-block.scss
Labels: priority, ready for review

#1081 Fix syntax to allow single spaces within search queries.
  styleguide/source/assets/js/main-navigation.js
Labels: ready for review
