Repository AmericanMedicalAssociation/ama-style-guide-2, pull requests merged in 2021-11, with the labels that each got.

#1107 EWL-8488: Global: Padding on topic term pills is incorrect
  styleguide/source/assets/scss/02-molecules/_tags.scss
Labels: ready for review

#1108 EWL-8730: Subcat | Page Grouper: Bottom Margin should be 35 px and not 28px
  styleguide/source/assets/scss/02-molecules/_page-grouping.scss
Labels: ready for review

#1104 EWL-8712: cta button design fix.
  styleguide/source/assets/scss/00-base/_webforms.scss
Labels: ready for review

#1105 EWL-9116: Fixes white space issue on subcategory on-page search filters
  styleguide/source/assets/scss/05-pages/_subcategory.scss
Labels: ready for review

#1109 EWL-8513: Fix mobile font size for subcategory list links on category pages.
  styleguide/source/assets/scss/03-organisms/_subcategory-exploration.scss
Labels: ready for review

#1110 EWL-8503: Fix color of border line on events page search fields.
  styleguide/source/assets/scss/01-atoms/_search-field.scss
Labels: ready for review

#1106 EWL-9107: Adjust styling Homepage Social Module for new text field.
  styleguide/source/assets/scss/03-organisms/_homepage-social-modual.scss
Labels: ready for review

#1111 EWL-8487: Adjust styling of video component in articles and category pages.
  styleguide/source/assets/scss/02-molecules/_video-block.scss
  styleguide/source/assets/scss/05-pages/_news.scss
Labels: in review

#1117 EWL-8485: Change color of related content inline stub.
  styleguide/source/assets/scss/02-molecules/_article-stub.scss
Labels: ready for review

#1118 changeing position.
  styleguide/source/assets/scss/02-molecules/_series-tag.scss
Labels: ready for review

#1119 EWL-8731: Fixes social icon cut off on people bio pages.
  styleguide/source/assets/scss/05-pages/_people_bio.scss
Labels: ready for review

#1114 EWL-9127: Adds script to prevent empty searches.
  styleguide/source/assets/js/main-navigation.js
Labels: priority, ready for review

#1121 EWL-8487: Adjust margins for video components.
  styleguide/source/assets/scss/02-molecules/_video-block.scss
  styleguide/source/assets/scss/02-molecules/hub/_hub-hero.scss
Labels: priority, ready for review, in review

#1123 bumped SG version to 2.69.2
  styleguide/package-lock.json
  styleguide/package.json
Labels: ready for review

#1122 EWL-9164: Position updated for tag.
  styleguide/source/assets/scss/02-molecules/_series-tag.scss
Labels: priority, question, in review

#1126 EWL-9188: Styling for content type taxonomy icon in search results display.
  styleguide/source/assets/scss/02-molecules/search-result/_search-result.scss
Labels: ready for review
