Repository AmericanMedicalAssociation/ama-style-guide-2, pull requests merged in 2021-01, with the labels that each got.

#972 EWL-7141: Adjust event tab image styling.
  styleguide/source/assets/scss/02-molecules/_event-stub.scss
Labels: ready for review

#973 EWL-7493: Remove extra whitespace within travel tab on Event Detail p…
  styleguide/source/assets/scss/02-molecules/_info-card.scss
Labels: ok to merge, priority

#971 EWL-8232: Adjust tablet breakpoints for membership block margins on a…
  styleguide/source/assets/scss/03-organisms/_membership.scss
  styleguide/source/assets/scss/05-pages/_news.scss
Labels: ok to merge, priority

#975 EWL-8424: Article Page Grouping block: Extra pipe displays in active state display of last page
  styleguide/source/assets/scss/02-molecules/_page-grouping.scss
Labels: in review, ready for review

#979 bumped sg to 2.57.2
  styleguide/package-lock.json
  styleguide/package.json
Labels: ready for review

#974 EWL-8461: added jquery-ui to theme
  styleguide/source/assets/js/vendor/jquery-ui.min.js
Labels: has D8 dependency, in review, priority
