Repository AmericanMedicalAssociation/ama-style-guide-2, pull requests merged in 2022-09, with the labels that each got.

#1238 EWL-9653: Styling for topic catalog links.
  styleguide/source/assets/scss/02-molecules/_tags.scss
  styleguide/source/assets/scss/03-organisms/_subcategory-index.scss
  styleguide/source/assets/scss/05-pages/_topic-index.scss
Labels: ready for review

#1231 EWL-9628: Fix article event date display.
  styleguide/source/assets/scss/05-pages/_news.scss
Labels: priority, ready for review

#1236 EWl-9677:Morning Rounds field text bolded in footer.
  styleguide/source/assets/scss/03-organisms/_footer.scss
Labels: priority

#1240 bugfix/fix block border padding issue
  styleguide/source/assets/scss/03-organisms/_membership.scss
Labels: priority, ready for review

#1235 EWL-9455: SOLR Display Series Index.
  styleguide/source/assets/scss/02-molecules/search-result/_search-result.scss
Labels: priority, ready for review

#1243 glossary styling
  styleguide/source/assets/scss/05-pages/_glossary.scss
Labels: priority, ready for review

#1245 Feature/filter rework
  styleguide/source/assets/js/glossary.js
  styleguide/source/assets/scss/05-pages/_glossary.scss
Labels: priority, ready for review

#1246 EWL-9658: AMA Locker | Create My Bookmarks Index Page
  styleguide/source/assets/images/BookmarkHoverIcon_Locker.svg
  styleguide/source/assets/images/BookmarkIcon_Locker.svg
  styleguide/source/assets/images/BookmarkedIcon_Locker.svg
  styleguide/source/assets/images/BookmarksMenuIcon_Locker.svg
  styleguide/source/assets/images/RemoveHoverIcon_Locker.svg
  styleguide/source/assets/images/RemoveIcon_Locker.svg
  styleguide/source/assets/scss/03-organisms/_bookmarks.scss
  styleguide/source/assets/scss/03-organisms/_masthead.scss
  styleguide/source/assets/scss/05-pages/_glossary.scss
Labels: priority, ready for review

#1248 EWL-9657: added styling for my topics index page.
  styleguide/source/assets/scss/03-organisms/_bookmarks.scss
Labels: priority, in review

#1249 EWL-9661: Styling for topic bookmark icons.
  styleguide/source/assets/images/FollowHoverIcon_Locker.svg
  styleguide/source/assets/images/FollowIcon_Locker@1x.svg
  styleguide/source/assets/images/FollowingIcon_Locker.svg
  styleguide/source/assets/scss/03-organisms/_bookmarks.scss
Labels: priority, ready for review

#1247 EWL-9660 bookmark associated pages
  styleguide/source/assets/scss/03-organisms/_bookmarks.scss
  styleguide/source/assets/scss/03-organisms/_masthead.scss
Labels: priority, ready for review

#1251 EWL-9659: Personal Nav Menu
  styleguide/source/assets/images/SubscribedIcon_Locker.svg
  styleguide/source/assets/images/SubscriptionsMenuIcon_Locker.svg
  styleguide/source/assets/images/TopicsMenuIcon_Locker.svg
  styleguide/source/assets/js/nav.js
  styleguide/source/assets/scss/03-organisms/_locker-navigation.scss
Labels: priority, ready for review

#1253 EWL-9659: Fixes un-bookmark styling.
  styleguide/source/assets/scss/03-organisms/_bookmarks.scss
Labels: priority, ready for review

#1255 Redirect for sign-in on marked glossary pages
  styleguide/source/assets/js/sign-in-redirect.js
Labels: in review

#1252 ADF-122: Prototype search bar ( AMA Doctor Finder)
  styleguide/source/_patterns/01-atoms/forms/search-field-dr-finder.json
  styleguide/source/_patterns/01-atoms/forms/search-field-dr-finder.md
  styleguide/source/_patterns/01-atoms/forms/search-field-dr-finder.twig
  styleguide/source/assets/scss/01-atoms/_search-field-dr-finder.scss
Labels: ready for review, AMA Dr Finder

#1258 Styling for showing and hiding bookmark removal message.
  styleguide/source/assets/scss/03-organisms/_bookmarks.scss
Labels: priority, ready for review

#1259 Styling for unfollow behavior on my topics index.
  styleguide/source/assets/scss/03-organisms/_bookmarks.scss
Labels: priority, ready for review
