Repository AmericanMedicalAssociation/ama-style-guide-2, pull requests merged in 2022-08, with the labels that each got.

#1224 EWL-9597: Add read more functionality to category view.
  styleguide/source/assets/js/index-page.js
  styleguide/source/assets/scss/05-pages/_category.scss
  styleguide/source/assets/scss/05-pages/_topic-index.scss
Labels: ready for review

#1227 EWL-9496: added address formatting for event addresses.
  styleguide/source/assets/scss/05-pages/_news.scss
Labels: priority, ready for review

#1225 EWL-9238: Article stub series link style update.
  styleguide/source/assets/scss/02-molecules/_article-stub.scss
Labels: ok to merge, has D8 dependency, Waiting on D8 PR update

#1203 updated pattern-lab core for php 8.0
  styleguide/composer.json
  styleguide/composer.lock
  styleguide/config/patternengines.json
  styleguide/package-lock.json
Labels: priority, ready for review

#1223 EWL-9593: Adjust image caption styling to keep wrap without whitespac…
  styleguide/source/assets/scss/05-pages/_news.scss
Labels: ready for review

#1229 EWL-9597: Read more style adjustment.
  styleguide/source/assets/scss/05-pages/_topic-index.scss
Labels: ready for review

#1228 changed address line height.
  styleguide/source/assets/scss/05-pages/_news.scss
Labels: priority

#1237 EWL-9521: topics catalog
  styleguide/source/_twig-components/functions/setattributes.function.php
  styleguide/source/assets/scss/05-pages/_glossary.scss
Labels: ready for review, Approve but DON'T MERGE
