Repository AmericanMedicalAssociation/ama-style-guide-2, pull requests merged in 2022-11, with the labels that each got.

#1294 ADF-259: Add Sticky JS to Drupal for Find Dr Main Navigation.
  styleguide/source/assets/js/dr-finder-sticky.js
Labels: ready for review, AMA Find A Doctor

#1286 EWL-9708: Adjust spacing of stub list titles.
  styleguide/source/assets/scss/02-molecules/_article-stub.scss
Labels: ready for review

#1279 Update subscribe button styling on series term pages.
  styleguide/source/assets/images/SubscribeHoverIcon_Locker.svg
  styleguide/source/assets/images/SubscribeIcon_Locker.svg
  styleguide/source/assets/scss/03-organisms/_bookmarks.scss
  styleguide/source/assets/scss/03-organisms/_series-subscribe.scss
  styleguide/source/assets/scss/05-pages/_series.scss
Labels: ready for review, is blocked

#1289 EWL-9656: Add style assets for My Subscriptions page
  styleguide/source/assets/images/UnsubscribeHoverIcon_Locker.svg
  styleguide/source/assets/images/UnsubscribeIcon_Locker.svg
  styleguide/source/assets/scss/03-organisms/_subscriptions.scss
Labels: priority

#1287 EWL-9768: Adjust spacing between text and image for ama locker pages.
  styleguide/source/assets/scss/03-organisms/_bookmarks.scss
Labels: priority, ready for review

#1288 EWL-9769: Set explicit line height on ama locker text.
  styleguide/source/assets/scss/03-organisms/_bookmarks.scss
Labels: priority, ready for review

#1290 EWL-9770: Adjust bookmark nav styling on mobile.
  styleguide/source/assets/scss/03-organisms/_locker-navigation.scss
Labels: priority, ready for review

#1296 EWL-9799: Fix ama locker nav icon clipping.
  styleguide/source/assets/scss/03-organisms/_locker-navigation.scss
Labels: priority, ready for review

#1292 EWL-9798: Bookmark cta icon update.
  styleguide/source/assets/scss/03-organisms/_bookmarks.scss
Labels: priority, ready for review

#1291 EWL-9771: Allow users to unbookmark article content on articles.
  styleguide/source/assets/scss/03-organisms/_bookmarks.scss
Labels: priority, ready for review

#1297 EWL-7670: Hub page last card display issue
  styleguide/source/assets/scss/02-molecules/hub/_hub-card.scss
Labels: priority, ready for review

#1295 EWL-9773: Fix nav alignment issue.
  styleguide/source/assets/scss/03-organisms/_locker-navigation.scss
Labels: priority, ready for review

#1299 ADF-277 Mobile theme profile header
  styleguide/source/_patterns/02-molecules/dr-finder-profile-header/dr-finder-profile-header.twig
  styleguide/source/_patterns/05-pages/dr-finder/dr-finder-with-modal.json
  styleguide/source/_patterns/05-pages/dr-finder/dr-finder-with-profile-clam.json
  styleguide/source/_patterns/05-pages/dr-finder/dr-finder-with-profile-complete.json
  styleguide/source/_patterns/05-pages/dr-finder/dr-finder-with-profile-complete.twig
  styleguide/source/_patterns/05-pages/dr-finder/dr-finder-with-profile-edit.json
  styleguide/source/_patterns/05-pages/dr-finder/dr-finder-with-search-results.json
  styleguide/source/_patterns/05-pages/dr-finder/dr-finder.json
  styleguide/source/assets/scss/02-molecules/_dr-finder-profile-header.scss
  styleguide/source/assets/scss/05-pages/_dr-finder.scss
Labels: ready for review

#1303 EWL-9769: Fix line heigh on ama locker pages.
  styleguide/source/assets/scss/05-pages/_glossary.scss
Labels: ready for review

#1300 EWL-9841: Adds styling for locker nav and series subscribe button
  styleguide/source/assets/scss/03-organisms/_locker-navigation.scss
  styleguide/source/assets/scss/03-organisms/_series-subscribe.scss
Labels: ready for review

#1304 EWL-9798: Fix bookmark page cta overlap.
  styleguide/source/assets/scss/03-organisms/_bookmarks.scss
Labels: ready for review

#1307 EWL-9776: Adjust styling of dot on search pages.
  styleguide/source/assets/scss/02-molecules/search-result/_search-result.scss
Labels: priority, ready for review

#1306 EWL-7670: Update CSS for 3-up hub card layout
  styleguide/source/assets/scss/02-molecules/hub/_hub-card.scss
Labels: priority, ready for review

#1305 EWL-9770: Fix ama locker nav alignment on mobile.
  styleguide/source/assets/scss/03-organisms/_locker-navigation.scss
Labels: priority, ready for review

#1301 ADF-276 Mobile Filters
  styleguide/source/_patterns/02-molecules/dr-finder-filter-buttons/dr-finder-filter-buttons.json
  styleguide/source/_patterns/02-molecules/dr-finder-filter-buttons/dr-finder-filter-buttons.twig
  styleguide/source/_patterns/02-molecules/dr-finder-filter-list/dr-finder-filter-list.json
  styleguide/source/_patterns/02-molecules/dr-finder-filter-list/dr-finder-filter-list.twig
  styleguide/source/_patterns/05-pages/dr-finder/dr-finder-with-search-results.json
  styleguide/source/assets/js/dr-finder-filter-buttons.js
  styleguide/source/assets/scss/02-molecules/_dr-finder-filter-list.scss
  styleguide/source/assets/scss/02-molecules/_dr_finder-filter-buttons.scss
  styleguide/source/assets/scss/05-pages/_dr-finder.scss
Labels: ready for review, AMA Find A Doctor

#1308 EWL-9656: Adjust styling for my subscription pages.
  styleguide/source/assets/scss/03-organisms/_subscriptions.scss
Labels: ready for review

#1310 EWL-9702: brightcove videos
  styleguide/source/assets/scss/01-atoms/_videos.scss
Labels: ready for review
