Repository AmericanMedicalAssociation/ama-style-guide-2, pull requests merged in 2023-03, with the labels that each got.

#1336 EWL-10016: Styling for partner promo redesign on category pages.
  styleguide/source/assets/scss/02-molecules/_partner-promo.scss
Labels: ok to merge, Pending Travis Build

#1338 Remove file creating saml redirect on styleguide pages to resolve err…
  styleguide/package-lock.json
  styleguide/source/assets/js/sign-in-redirect.js
Labels: ready for review

#1337 EWL-10018 subscribe promo category redesign
  styleguide/source/assets/scss/02-molecules/_subscribe-promo.scss
Labels: ready for review

#1335 EWL-10005 membership block category styling
  styleguide/source/assets/scss/03-organisms/_membership.scss
Labels: ready for review

#1346 EWL-9940: featured content block
  styleguide/source/assets/scss/00-base/_colors.scss
  styleguide/source/assets/scss/02-molecules/_category-hero.scss
  styleguide/source/assets/scss/05-pages/_category.scss
Labels: priority, ready for review

#1347 EWL-0: Fix styling errors for custom blocks on category pages.
  styleguide/source/assets/scss/02-molecules/_partner-promo.scss
  styleguide/source/assets/scss/02-molecules/_subscribe-promo.scss
  styleguide/source/assets/scss/03-organisms/_membership.scss
Labels: priority, ready for review, in review

#1339 EWL-10018 partner promo category styleguide
  styleguide/source/_patterns/01-atoms/image/image.json
  styleguide/source/_patterns/01-atoms/image/image~href.json
  styleguide/source/_patterns/02-molecules/membership/membership-category-page.twig
  styleguide/source/_patterns/02-molecules/membership/membership~category-page.json
  styleguide/source/_patterns/02-molecules/partner-promo/partner-promo-category-page.json
  styleguide/source/_patterns/02-molecules/partner-promo/partner-promo-category-page.twig
  styleguide/source/_patterns/02-molecules/partner-promo/partner-promo.json
  styleguide/source/_patterns/02-molecules/partner-promo/partner-promo.md
  styleguide/source/_patterns/02-molecules/partner-promo/partner-promo.twig
  styleguide/source/_patterns/02-molecules/partner-promo/partner-promo~as-homepage.json
Labels: ready for review

#1343 EWL-10005 membership block category styleguide
  styleguide/source/_patterns/02-molecules/membership/membership-category-page.json
  styleguide/source/_patterns/02-molecules/membership/membership-category-page.twig
  styleguide/source/assets/scss/03-organisms/_membership.scss
Labels: ready for review, has dependency!

#1344 EWL-10018 subscribe promo category styleguide
  styleguide/source/_patterns/02-molecules/subscribe-promo/subscribe-promo-category.json
  styleguide/source/_patterns/02-molecules/subscribe-promo/subscribe-promo-category.twig
  styleguide/source/_patterns/02-molecules/subscribe-promo/subscribe-promo.json
  styleguide/source/_patterns/02-molecules/subscribe-promo/subscribe-promo.md
  styleguide/source/_patterns/02-molecules/subscribe-promo/subscribe-promo.twig
  styleguide/source/_patterns/02-molecules/subscribe-promo/subscribe-promo~as-wide.json
  styleguide/source/assets/scss/02-molecules/_subscribe-promo.scss
Labels: ready for review, has dependency!

#1345 EWL-10007: Add category theme block styles
  styleguide/source/assets/scss/02-molecules/_category-block.scss
Labels: work in progress

#1350 EWL-9940: Final Polish
  styleguide/source/assets/scss/02-molecules/_category-hero.scss
Labels: priority, ready for review

#1351 EWL-9943: Add styling to keep membership content aligned to top of co…
  styleguide/source/assets/scss/03-organisms/_membership.scss
Labels: priority, ready for review

#1352 added align-right styles as well as date and tag updates.
  styleguide/source/assets/scss/02-molecules/_category-hero.scss
Labels: priority, ready for review, in review

#1353 Update cta font colors for category custom block redesigns.
  styleguide/source/assets/scss/02-molecules/_partner-promo.scss
  styleguide/source/assets/scss/02-molecules/_subscribe-promo.scss
  styleguide/source/assets/scss/03-organisms/_membership.scss
Labels: priority, ready for review

#1359 EWL-9975: Fix article stub list alignment on homepage.
  styleguide/source/assets/scss/05-pages/_homepage.scss
Labels: priority, ready for review

#1358 EWL-10002: Fix hamburger menu display when alert banner present.
  styleguide/source/assets/js/main-navigation.js
Labels: priority, ready for review

#1357 EWL-9943: Adjust button font styling and size for category membership…
  styleguide/source/assets/scss/03-organisms/_membership.scss
Labels: priority, ready for review

#1360 EWL-9940: featured content block
  styleguide/source/assets/scss/02-molecules/_category-hero.scss
Labels: priority, ready for review

#1361 EWL-10071: Update subscribe promo form styling for category pages.
  styleguide/source/assets/scss/02-molecules/_subscribe-promo.scss
  styleguide/source/assets/scss/03-organisms/_footer.scss
Labels: ready for review
