Repository AmericanMedicalAssociation/ama-style-guide-2, pull requests merged in 2023-07, with the labels that each got.

#1419 Ewl 10219 share bar print
  styleguide/source/assets/icons/svg/social-share-icons/print.svg
  styleguide/source/assets/icons/svg/social-share-icons/printed.svg
  styleguide/source/assets/scss/03-organisms/_masthead.scss
  styleguide/source/assets/scss/03-organisms/_social-share.scss
Labels: ready for review, has D8 dependency

#1423 EWL-10217: Share bar bookmark
  styleguide/source/assets/scss/03-organisms/_social-share.scss
Labels: priority

#1424 EWL-10189: Styling for index hero heading text field.
  styleguide/source/assets/scss/05-pages/_topic-index.scss
Labels: priority, ready for review

#1418 EWL-10194: Event Article Header Styling
  styleguide/source/assets/icons/svg/event-header-icons/AddtoCalendarIcon.svg
  styleguide/source/assets/icons/svg/event-header-icons/AddtoCalendarIconHover.svg
  styleguide/source/assets/icons/svg/event-header-icons/LocateOnGoogleMapsIcon.svg
  styleguide/source/assets/icons/svg/event-header-icons/LocateOnGoogleMapsIconHover.svg
  styleguide/source/assets/scss/05-pages/_news.scss
Labels: priority, has D8 dependency

#1416 Style for new subtitle on news article
  styleguide/source/assets/scss/03-organisms/_masthead.scss
Labels: priority

#1421 ADF-397, fixing back to search link
  styleguide/source/_patterns/02-molecules/dr-finder-profile-header/dr-finder-profile-header.twig
  styleguide/source/assets/js/dr-finder-back-to-search.js
Labels: priority

#1433 EWL-10133: full width article header
  styleguide/source/assets/scss/02-molecules/_inline-bio.scss
  styleguide/source/assets/scss/03-organisms/_social-share.scss
  styleguide/source/assets/scss/05-pages/_news.scss
Labels: ready for review

#1422 EWL-10132: Suppress Mobile Simplecast Image Display
  styleguide/source/assets/scss/02-molecules/_podcast_player.scss
Labels: priority, ready for review

#1431 EWL-10222: Adjust interaction share modal positioning across screen s…
  styleguide/source/assets/scss/03-organisms/_social-share.scss
Labels: ready for review

#1439 More series subscribe styling for icon and hover states
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-subscribe-hover.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-subscribe.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-unsubscribe-hover.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-unsubscribe.twig
  styleguide/source/assets/icons/svg/icon-subscribe-hover.svg
  styleguide/source/assets/icons/svg/icon-subscribe.svg
  styleguide/source/assets/icons/svg/icon-unsubscribe-hover.svg
  styleguide/source/assets/icons/svg/icon-unsubscribe.svg
  styleguide/source/assets/scss/00-base/__01.mixins/_ama-button.scss
  styleguide/source/assets/scss/01-atoms/_button.scss
  styleguide/source/assets/scss/03-organisms/_series-subscribe.scss
Labels: ready for review

#1437 removed unused link styles.
  styleguide/source/assets/scss/05-pages/_news.scss
Labels: ready for review

#1440 EWL-10194: Remove Event Header Top Border
  styleguide/source/assets/scss/05-pages/_news.scss
Labels: ready for review

#1443 EWL-10165: Remove extra padding on Subscribe
  styleguide/source/assets/scss/05-pages/_news.scss
Labels: ready for review

#1438 EWL-10220: Interaction bar side scroll functionality.
  styleguide/source/assets/scss/03-organisms/_social-share.scss
Labels: priority, ready for review

#1442 ADF-419: Change copy and button text/target on banner following successful page claim
  styleguide/source/_patterns/02-molecules/dr-finder-profile-header/dr-finder-profile-header~with-image.json
  styleguide/source/_patterns/05-pages/dr-finder/dr-finder-with-profile-complete.json
Labels: AMA Find A Doctor

#1444 event and header updates
  styleguide/source/assets/scss/03-organisms/_masthead.scss
  styleguide/source/assets/scss/05-pages/_news.scss
Labels: ready for review

#1441 ADF-416: Change copy and button text on the Claim Your Profile area of the physician page
  styleguide/source/_patterns/02-molecules/dr-finder-claim/dr-finder-claim.json
  styleguide/source/_patterns/02-molecules/dr-finder-claim/dr-finder-claim.twig
  styleguide/source/_patterns/02-molecules/dr-finder-profile-header/dr-finder-profile-header.json
  styleguide/source/_patterns/05-pages/dr-finder/dr-finder-with-profile-clam.json
  styleguide/source/assets/scss/02-molecules/_dr-finder-claim.scss
Labels: AMA Find A Doctor

#1450 EWL-10220: Remove errant share bar styling to prevent white space in …
  styleguide/source/assets/scss/03-organisms/_social-share.scss
Labels: priority, ready for review

#1449 make button fully clickable for logged out users.
  styleguide/source/assets/js/form-items.js
Labels: priority, ready for review

#1451 EWL-10133: remove purple border and top padding from article body.
  styleguide/source/assets/scss/05-pages/_news.scss
Labels: priority, ready for review

#1452 EWL-10195: reduced event size when there is no image. Commented out clickable ad…
  styleguide/source/assets/scss/05-pages/_news.scss
Labels: priority, ready for review

#1454 EWL-0: Adjust styling for slim membership block on subcat pages.
  styleguide/source/assets/scss/03-organisms/_membership.scss
Labels: ready for review

#1456 EWL-10220: removed hover styles from calendar.
  styleguide/source/assets/scss/05-pages/_news.scss
Labels: priority, ready for review

#1455 EWL-10220: changed color of all icons.
  styleguide/source/assets/icons/svg/social-share-icons/bookmark.svg
  styleguide/source/assets/icons/svg/social-share-icons/bookmarked.svg
  styleguide/source/assets/icons/svg/social-share-icons/copied.svg
  styleguide/source/assets/icons/svg/social-share-icons/copy.svg
  styleguide/source/assets/icons/svg/social-share-icons/email.svg
  styleguide/source/assets/icons/svg/social-share-icons/print.svg
  styleguide/source/assets/icons/svg/social-share-icons/share.svg
  styleguide/source/assets/icons/svg/social-share-icons/shared.svg
Labels: ready for review

#1459 Bugfix\subcat view updates to address image problems.
  styleguide/source/assets/scss/02-molecules/_subcategory-page-article-stub.scss
Labels: priority, ready for review

#1467 ADF-439, Fixing UI issues
  styleguide/source/assets/icons/svg/icon-menu-open.svg
  styleguide/source/assets/js/sign-in-dropdown.js
  styleguide/source/assets/scss/02-molecules/_dr-finder-filter-list.scss
  styleguide/source/assets/scss/02-molecules/_explore-menu.scss
Labels: AMA Find A Doctor

#1468 Style for membership promos
  styleguide/source/assets/scss/03-organisms/_membership.scss
Labels: priority

#1460 EWL-10220: Adjust share bar icon positioning on sticky/scroll.
  styleguide/source/assets/scss/03-organisms/_social-share.scss
Labels: priority, ready for review

#1463 ADF-395: Dr. Finder Specific Load More Button Styling
  styleguide/source/assets/scss/05-pages/_dr-finder.scss
Labels: ready for review, has dependency!, AMA Find A Doctor
