Repository AmericanMedicalAssociation/ama-style-guide-2, pull requests merged in 2023-12, with the labels that each got.

#1538 Fix Dr. Finder once() Implementations
  styleguide/source/assets/js/dr-finder-filter-buttons.js
  styleguide/source/assets/js/dr-finder-filter-list.js
Labels: work in progress, AMA Find A Doctor

#1532 EWL-10484: Fix page grouper and toc display.
  styleguide/source/assets/scss/02-molecules/_page-grouping.scss
  styleguide/source/assets/scss/02-molecules/_table-of-contents.scss
Labels: priority, ok to merge

#1529 EWL-10370: Remove hanging vertical line from 3 up article stubs.
  styleguide/source/assets/scss/02-molecules/_article-stub.scss
Labels: priority, ready for review

#1534 EWL-10385: Update instagram icon in footer.
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-instagram-logo-white-hover.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-instagram-logo-white-purple-hover.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-instagram-logo-white-purple.twig
  styleguide/source/assets/icons/svg/icon-instagram-logo-white-hover.svg
  styleguide/source/assets/icons/svg/icon-instagram-logo-white-purple.svg
  styleguide/source/assets/icons/svg/icon-instagram-white-hover.svg
  styleguide/source/assets/icons/svg/icon-instagram-white-purple.svg
  styleguide/source/assets/scss/02-molecules/_social-share.scss
Labels: priority, ok to merge

#1535 EWL-10055: Update membership block image ratio.
  styleguide/source/assets/scss/03-organisms/_membership.scss
Labels: priority, ok to merge

#1539 EWL-0: Remove outdated molecule styleguide components.
  styleguide/source/_patterns/02-molecules/agenda-table.json
  styleguide/source/_patterns/02-molecules/agenda-table.md
  styleguide/source/_patterns/02-molecules/agenda-table.twig
  styleguide/source/_patterns/02-molecules/agenda.json
  styleguide/source/_patterns/02-molecules/agenda.md
  styleguide/source/_patterns/02-molecules/agenda.twig
  styleguide/source/_patterns/02-molecules/alert.twig
  styleguide/source/_patterns/02-molecules/category-hero.json
  styleguide/source/_patterns/02-molecules/category-hero.twig
  styleguide/source/_patterns/02-molecules/explore-menu.json
  styleguide/source/_patterns/02-molecules/explore-menu.md
  styleguide/source/_patterns/02-molecules/explore-menu.twig
  styleguide/source/_patterns/02-molecules/social-share.json
  styleguide/source/_patterns/02-molecules/visual-subcategory.json
  styleguide/source/_patterns/02-molecules/visual-subcategory.md
  styleguide/source/_patterns/02-molecules/visual-subcategory.twig
  styleguide/source/assets/scss/02-molecules/_alert.scss
Labels: ready for review

#1540 EWL-0: Remove unused ribbon dropdown from styleguide.
  styleguide/source/_patterns/02-molecules/ribbon-dropdown/ribbon-dropdown.json
  styleguide/source/_patterns/02-molecules/ribbon-dropdown/ribbon-dropdown.md
  styleguide/source/_patterns/02-molecules/ribbon-dropdown/ribbon-dropdown.twig
  styleguide/source/_patterns/02-molecules/ribbon-dropdown/ribbon-dropdown~mobile-auth.json
  styleguide/source/_patterns/02-molecules/ribbon-dropdown/ribbon-dropdown~mobile.json
  styleguide/source/_patterns/02-molecules/ribbon-dropdown/ribbon-dropdown~user-menu-auth.json
  styleguide/source/_patterns/02-molecules/ribbon-user-menu/ribbon-user-menu.json
  styleguide/source/_patterns/02-molecules/ribbon-user-menu/ribbon-user-menu.md
  styleguide/source/_patterns/02-molecules/ribbon-user-menu/ribbon-user-menu.twig
  styleguide/source/_patterns/02-molecules/ribbon-user-menu/ribbon-user-menu~logged-in.json
  styleguide/source/_patterns/03-organisms/ribbon/ribbon.json
  styleguide/source/_patterns/03-organisms/ribbon/ribbon.md
  styleguide/source/_patterns/03-organisms/ribbon/ribbon.twig
  styleguide/source/_patterns/03-organisms/ribbon/ribbon~auth.json
Labels: ready for review

#1537 EWL-0: Remove defunct and unnecessary atom patterns from styleguide.
  styleguide/source/_patterns/01-atoms/content-grouping-header.json
  styleguide/source/_patterns/01-atoms/content-grouping-header.md
  styleguide/source/_patterns/01-atoms/content-grouping-header.twig
  styleguide/source/_patterns/01-atoms/skip-nav.twig
  styleguide/source/_patterns/02-molecules/event-stub/event-stub~as-sticky.json
  styleguide/source/assets/scss/01-atoms/_skip-nav.scss
Labels: ready for review
