Repository AmericanMedicalAssociation/ama-style-guide-2, pull requests merged in 2023-06, with the labels that each got.

#1403 EWL-10159: Click to Copy Styling
  styleguide/source/assets/scss/03-organisms/_social-share.scss
Labels: priority, ready for review, Waiting on D8 PR update

#1405 EWL-10157: Removes bookmark underline and fixes flag image on bookmarked
  styleguide/source/assets/scss/03-organisms/_social-share.scss
Labels: priority

#1404 EWL-10083: Inline Promo Styling
  styleguide/source/assets/scss/02-molecules/_partner-promo.scss
  styleguide/source/assets/scss/02-molecules/_subscribe-promo.scss
  styleguide/source/assets/scss/03-organisms/_membership.scss
Labels: priority, ready for review, Waiting on D8 PR update

#1407 EWL-10163: Index full-width listing updates
  styleguide/source/assets/scss/02-molecules/_article-stub.scss
  styleguide/source/assets/scss/02-molecules/_subcategory-page-article-stub.scss
  styleguide/source/assets/scss/03-organisms/_category-index.scss
Labels: priority

#1406 EWL-10156: social share styles.
  styleguide/source/assets/scss/03-organisms/_social-share.scss
Labels: priority, ready for review

#1409 EWL-10203: Fix mobile spacing issue for homepage slim membership block.
  styleguide/source/assets/scss/03-organisms/_membership.scss
Labels: priority, question

#1412 EWL-10108: changed share text to uppercase.
  styleguide/source/assets/scss/03-organisms/_social-share.scss
Labels: priority, ready for review

#1414 EWL-10083: Adjust full width index spacing.
  styleguide/source/assets/scss/02-molecules/_subcategory-page-article-stub.scss
Labels: ready for review
