Repository AmericanMedicalAssociation/ama-style-guide-2, pull requests merged in 2023-01, with the labels that each got.

#1318 EWL-9733: Set topic catalog filters links centered on mobile viewports.
  styleguide/source/assets/js/glossary.js
Labels: ready for review

#1323 EWL-9831: Related series description spacing.
  styleguide/source/assets/scss/02-molecules/_article-stub.scss
Labels: in review

#1324 EWL-9814: scss fixes
  styleguide/source/assets/scss/02-molecules/_brightcove_video.scss
  styleguide/source/assets/scss/03-organisms/_member-feature.scss
  styleguide/source/assets/scss/04-templates/_two-column-right--75-25.scss
  styleguide/source/assets/scss/05-pages/_category.scss
Labels: priority, ready for review, in review

#1325 EWL-9964: standardized padding between regular and hover states.
  styleguide/source/assets/scss/03-organisms/_contact-us-webform.scss
Labels: in review

#1327 EWL-9967: Upvote icon on mobile fix.
  styleguide/source/assets/scss/02-molecules/_upvote.scss
Labels: ready for review

#1328 EWL-9969: Fix padding for hub cards on article pages.
  styleguide/source/assets/scss/02-molecules/_article-stub.scss
Labels: ready for review
