Repository AmericanMedicalAssociation/ama-style-guide-2, pull requests merged in 2023-08, with the labels that each got.

#1471 EWL-10237: full/half width related coverage
  styleguide/source/assets/scss/03-organisms/_locker-navigation.scss
  styleguide/source/assets/scss/03-organisms/_related_coverage.scss
Labels: priority, ready for review

#1473 EWL-10051: Fix homepage calendar icon display issue.
  styleguide/source/assets/scss/02-molecules/_upcoming-event.scss
Labels: ready for review

#1465 EWL-10318: js cookie update
  styleguide/source/assets/js/alert.js
  styleguide/source/assets/js/wayfinder.js
Labels: priority, ready for review

#1472 EWL-10317: Partner Promo Embed
  styleguide/source/assets/scss/02-molecules/_partner-promo.scss
  styleguide/source/assets/scss/03-organisms/_membership.scss
Labels: priority, ready for review, ok to merge

#1474 EWL-10323: On sticky nav instances, remove id to prevent duplicate id's.
  styleguide/source/assets/js/locker-menu.js
  styleguide/source/assets/js/main-navigation.js
Labels: ready for review

#1475 EWL-10236: Fixes display of membership promos
  styleguide/source/assets/scss/03-organisms/_membership.scss
Labels: question, ready for review

#1476 EWL-10214: Locker UI Mobile Issue
  styleguide/source/assets/js/locker-menu.js
  styleguide/source/assets/scss/03-organisms/_locker-navigation.scss
Labels: ready for review

#1481 EWL-10342: Article upvote redesign styling.
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-upvote-active.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-upvote-hover.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-upvote.twig
  styleguide/source/assets/icons/svg/icon-upvote-active.svg
  styleguide/source/assets/icons/svg/icon-upvote-hover.svg
  styleguide/source/assets/icons/svg/icon-upvote.svg
  styleguide/source/assets/scss/02-molecules/_upvote.scss
Labels: ready for review

#1479 EWL-10334 article header mobile gap fix
  styleguide/source/assets/scss/03-organisms/_social-share.scss
  styleguide/source/assets/scss/05-pages/_news.scss
Labels: ready for review

#1486 EWL-10246: related articles custom block
  styleguide/source/assets/scss/02-molecules/_article-stub.scss
  styleguide/source/assets/scss/02-molecules/_tags.scss
Labels: ready for review

#1487 EWL-10359: Update twitter logo sitewide.
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-twitter-brand-hover.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-twitter-brand.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-twitter-white-hover.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-twitter-white-purple.twig
  styleguide/source/assets/icons/svg/icon-twitter-brand-hover.svg
  styleguide/source/assets/icons/svg/icon-twitter-brand.svg
  styleguide/source/assets/icons/svg/icon-twitter-white-hover.svg
  styleguide/source/assets/icons/svg/icon-twitter-white-purple.svg
  styleguide/source/assets/icons/svg/social-share-icons/twitter.svg
  styleguide/source/assets/scss/02-molecules/_inline-bio.scss
  styleguide/source/assets/scss/02-molecules/_social-share.scss
  styleguide/source/assets/scss/03-organisms/_social-share.scss
Labels: priority, ready for review

#1491 EWL-10311: Adjust spacing in article header on desktop.
  styleguide/source/assets/scss/05-pages/_news.scss
Labels: priority, ready for review

#1483 EWL-10335: Add Active State for Locker Icons
  styleguide/source/assets/scss/03-organisms/_locker-navigation.scss
Labels: priority, ready for review, in review

#1484 EWL-10354: Adjust icon sizing and hover in locker icons.
  styleguide/source/assets/scss/03-organisms/_locker-navigation.scss
Labels: priority, ready for review

#1485 EWL-10289: Update IDs for viewsreference fields
  styleguide/source/assets/scss/05-pages/_glossary.scss
Labels: priority, ready for review

#1488 EWL-8142: Update subscribe promo error icon.
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-error.twig
  styleguide/source/assets/icons/svg/icon-error.svg
Labels: priority, ready for review

#1492 EWL-10170: Update search page form to fix tab order
  styleguide/source/assets/scss/02-molecules/_search-header.scss
Labels: ready for review

#1489 EWL-10359: Adjust sizing of new twitter icon in author byline.
  styleguide/source/assets/scss/02-molecules/_inline-bio.scss
Labels: priority, ready for review

#1490 EWL-10245: display 3-up blockat 75% width
  styleguide/source/assets/scss/02-molecules/_article-stub.scss
Labels: priority, question, ready for review

#1496 EWL-10359: Update twitter icon alignment and sizing for share modal a…
  styleguide/source/assets/scss/02-molecules/_inline-bio.scss
  styleguide/source/assets/scss/03-organisms/_social-share.scss
Labels: priority, ready for review

#1498 EWL-10246: made header visible on mobile.
  styleguide/source/assets/scss/02-molecules/_article-stub.scss
Labels: priority, ready for review

#1495 EWL-10355: My Bookmark Index Read Time Spacing Issue
  styleguide/source/assets/scss/02-molecules/search-result/_search-result.scss
Labels: priority, question
