Repository AmericanMedicalAssociation/ama-style-guide-2, pull requests merged in 2023-10, with the labels that each got.

#1517 EWL-10295: Hub page minimal footer.
  styleguide/source/assets/scss/05-pages/_hub-page.scss
Labels: ok to merge

#1354 EWL-10012: Styleguide element
  styleguide/source/_patterns/03-organisms/annual-interim-meeting-block/annual-interim-meeting-block.md
  styleguide/source/_patterns/03-organisms/category-display-subcat.json
  styleguide/source/_patterns/03-organisms/category-display-subcat.md
  styleguide/source/_patterns/03-organisms/category-display-subcat.twig
Labels: priority, ready for review

#1514 EWL-10398 hub page hero styleguide component
  styleguide/source/_patterns/02-molecules/hub/hub-banner.twig
  styleguide/source/_patterns/02-molecules/hub/hub-page-hero.json
  styleguide/source/_patterns/02-molecules/hub/hub-page-hero.md
  styleguide/source/_patterns/02-molecules/hub/hub-page-hero.twig
  styleguide/source/_patterns/02-molecules/hub/hub-page-hero~one-button.json
  styleguide/source/_patterns/02-molecules/hub/hub-page-hero~white-background.json
  styleguide/source/_patterns/03-organisms/main-navigation/main-navigation-hub-page.twig
  styleguide/source/_patterns/05-pages/hub.json
  styleguide/source/_patterns/05-pages/hub.twig
  styleguide/source/assets/scss/03-organisms/_hub_page_hero.scss
Labels: priority, ready for review

#1520 EWL-10039: Media image caption wrap fix.
  styleguide/source/assets/scss/05-pages/_news.scss
Labels: ready for review, Approve but DON'T MERGE

#1521 EWL-10047: Fix hover state on suggested topics block.
  styleguide/source/assets/scss/05-pages/_glossary.scss
Labels: ready for review, Approve but DON'T MERGE

#1524 EWL-10176: Adjust subscribe promo checkbox.
  styleguide/source/assets/scss/02-molecules/_subscribe-promo.scss
Labels: ready for review, Approve but DON'T MERGE

#1497 EWL-10289: Update IDs for viewsreference fields
  styleguide/source/assets/scss/05-pages/_glossary.scss
Labels: has D8 dependency, Do not merge

#1527 Fix once implementations
  styleguide/source/assets/js/glossary.js
  styleguide/source/assets/js/index-page.js
  styleguide/source/assets/js/listicle.js
  styleguide/source/assets/js/locker-menu.js
Labels: in review
