Repository AmericanMedicalAssociation/ama-style-guide-2, pull requests merged in 2023-05, with the labels that each got.

#1384 EWL-10077: Fix displays issues on subscribe promo forms.
  styleguide/source/assets/scss/02-molecules/_subscribe-promo.scss
Labels: priority, ready for review

#1387 EWL-10110 subscribe promo index page
  styleguide/source/assets/scss/02-molecules/_partner-promo.scss
  styleguide/source/assets/scss/02-molecules/_subscribe-promo.scss
  styleguide/source/assets/scss/03-organisms/_membership.scss
  styleguide/source/assets/scss/05-pages/_topic-index.scss
Labels: priority, ready for review

#1391 EWL-10172: fixed height issue in category membership blocks
  styleguide/source/assets/scss/03-organisms/_membership.scss
Labels: ready for review, in review

#1392 EWL-10111: Adjust header styling for membership in hero blocks.
  styleguide/source/assets/scss/03-organisms/_membership.scss
Labels: ready for review

#1393 EWL-11179: Fix email label display on morning round footer form.
  styleguide/source/assets/scss/03-organisms/_footer.scss
Labels: ready for review

#1394 EWL-10087: changed focus properties.
  styleguide/source/assets/scss/02-molecules/_category-hero.scss
Labels: priority, ready for review

#1397 EWL-10112: partner promo bugfixes.
  styleguide/source/assets/scss/02-molecules/_partner-promo.scss
  styleguide/source/assets/scss/02-molecules/_subscribe-promo.scss
  styleguide/source/assets/scss/03-organisms/_membership.scss
Labels: priority, ready for review

#1399 EWL-10112: Remove errant spacing on partner promo text in hero slots
  styleguide/source/assets/scss/02-molecules/_partner-promo.scss
  styleguide/source/assets/scss/03-organisms/_membership.scss
Labels: priority, ready for review
