Repository AmericanMedicalAssociation/ama-style-guide-2, pull requests merged in 2023-04, with the labels that each got.

#1355 EWL-9971: Update styling for article stub list redesign.
  styleguide/source/assets/scss/01-atoms/_content-grouping-header.scss
  styleguide/source/assets/scss/02-molecules/_article-stub-metadata.scss
  styleguide/source/assets/scss/02-molecules/_article-stub.scss
  styleguide/source/assets/scss/02-molecules/_subcategory-page-article-stub.scss
  styleguide/source/assets/scss/03-organisms/_category-page-article-stub.scss
Labels: priority, ready for review

#1365 EWL-9941: Update cta text color for subscribe promo on category pages.
  styleguide/source/assets/scss/02-molecules/_subscribe-promo.scss
Labels: Do not merge

#1363 EWL-9938: Subcat Menu
  styleguide/source/assets/js/subcategory-exploration.js
  styleguide/source/assets/scss/02-molecules/_category-hero.scss
  styleguide/source/assets/scss/03-organisms/_subcategory-exploration.scss
Labels: priority, ready for review

#1356 EWL-10014 article stub list styleguide
  styleguide/source/_patterns/02-molecules/article-stub/article-stub-metadata.twig
  styleguide/source/_patterns/02-molecules/article-stub/article-stub.json
  styleguide/source/_patterns/02-molecules/article-stub/article-stub.twig
  styleguide/source/_patterns/03-organisms/category-page-article-stub.json
  styleguide/source/assets/scss/02-molecules/_article-stub.scss
  styleguide/source/assets/scss/03-organisms/_category-page-article-stub.scss
Labels: priority, question

#1370 EWL-9950: Remove italics from tags on category theme block.
  styleguide/source/assets/scss/02-molecules/_category-theme.scss
Labels: ready for review

#1371 EWL-9971: Fix article stub list padding on article pages.
  styleguide/source/assets/scss/02-molecules/_article-stub.scss
  styleguide/source/assets/scss/03-organisms/_four-up-teaser.scss
Labels: ready for review

#1373 EWL-9971: Article stub list style fixes.
  styleguide/source/assets/scss/02-molecules/_article-stub.scss
Labels: priority, ready for review

#1376 EWL-9971: Update styling for article stub redesign with three items.
  styleguide/source/assets/scss/02-molecules/_article-stub.scss
  styleguide/source/assets/scss/03-organisms/_subcategory-index.scss
  styleguide/source/assets/scss/05-pages/_category.scss
  styleguide/source/assets/scss/05-pages/_series.scss
  styleguide/source/assets/scss/05-pages/_topic-index.scss
Labels: ready for review

#1379 EWL-9949: updated category subcat block displays.
  styleguide/source/assets/scss/02-molecules/_category-theme.scss
Labels: ready for review

#1380 EWL-9950: New styles for category theme blocks. Removed all bold.
  styleguide/source/assets/scss/01-atoms/_content-grouping-header.scss
  styleguide/source/assets/scss/02-molecules/_category-theme.scss
  styleguide/source/assets/scss/02-molecules/_forum-topic.scss
  styleguide/source/assets/scss/02-molecules/_partner-promo.scss
  styleguide/source/assets/scss/02-molecules/_series-tag.scss
  styleguide/source/assets/scss/02-molecules/_subscribe-promo.scss
  styleguide/source/assets/scss/02-molecules/search-result/_search-result.scss
  styleguide/source/assets/scss/03-organisms/_membership.scss
  styleguide/source/assets/scss/05-pages/_application.scss
Labels: priority, ready for review

#1381 EWL-9975: Fix subscribe promo cta format.
  styleguide/source/assets/scss/02-molecules/_subscribe-promo.scss
Labels: priority, ready for review

#1382 EWL-10045: Follow topic hover icon fix.
  styleguide/source/assets/scss/03-organisms/_bookmarks.scss
Labels: priority, ready for review

#1378 EWL-10080: Improve contrast ratio of search page checkboxes.
  styleguide/source/assets/scss/01-atoms/_checkbox.scss
Labels: priority, ready for review

#1383 EWL-9996: Read more link keystroke access.
  styleguide/source/assets/js/index-page.js
Labels: priority, ready for review
