Repository AmericanMedicalAssociation/ama-style-guide-2, pull requests merged in 2024-09, with the labels that each got.

#1729 EWL-10994: Set active state on Page Grouper anchor links
  styleguide/source/assets/scss/02-molecules/_page-grouping.scss
Labels: priority, ready for review, in review

#1724 EWL-11025: Forum sort arrows
  styleguide/source/assets/scss/02-molecules/_forum-listing.scss
Labels: priority, question

#1721 EWL-10907: Add Pinned Comments
  styleguide/source/assets/scss/02-molecules/_forum-comments.scss
Labels: priority, ready for review, has D8 dependency

#1727 EWL-11026: Replies Column
  styleguide/source/assets/scss/02-molecules/_forum-listing.scss
Labels: priority, ready for review, in review

#1725 EWL-10904: Align Content with Menu Bar
  styleguide/source/assets/scss/02-molecules/_alert.scss
  styleguide/source/assets/scss/03-organisms/_product-nav.scss
Labels: priority, ready for review, has D8 dependency

#1733 EWL-11025: reverse sort arrows
  styleguide/source/_patterns/01-atoms/media/icons/svg/twistie-down.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/twistie-up.twig
  styleguide/source/assets/icons/svg/twistie-down.svg
  styleguide/source/assets/icons/svg/twistie-up.svg
  styleguide/source/assets/scss/02-molecules/_forum-listing.scss
Labels: priority, ready for review, in review

#1731 EWL-10994: Fix article column issue
  styleguide/source/assets/scss/04-templates/_two_column-article.scss
Labels: priority, ready for review, in review

#1730 EWL-11033: Set active link to display below page grouper title
  styleguide/source/assets/scss/02-molecules/_page-grouping.scss
Labels: priority, question

#1736 EWL-10994: Update mobile spacing for page grouper and page content.
  styleguide/source/assets/scss/02-molecules/_page-grouping.scss
  styleguide/source/assets/scss/04-templates/_two_column-article.scss
Labels: priority, ready for review, in review

#1707 DCP-210: Add Find A Doctor Overrides for Recent SG Font Change
  styleguide/source/assets/scss/02-molecules/_dr-finder-alert.scss
  styleguide/source/assets/scss/03-organisms/_membership.scss
Labels: priority, ready for review, AMA Find A Doctor

#1744 EWL-11029: fix Item Type display issue
  styleguide/source/assets/js/forum-styling.js
  styleguide/source/assets/scss/02-molecules/_forum-listing.scss
Labels: ready for review

#1743 EWL-10904: Adjust Mobile Alert Banner Close Button
  styleguide/source/assets/scss/02-molecules/_alert.scss
Labels: priority, ready for review

#1745 EWL-11017: Article Shift on Body Copy
  styleguide/source/assets/scss/04-templates/_two_column-article.scss
  styleguide/source/assets/scss/04-templates/_two_column-left.scss
  styleguide/source/assets/scss/04-templates/_two_column-right.scss
Labels: priority, ready for review

#1734 EWL-11028: Add recent column to style lists.
  styleguide/source/assets/scss/02-molecules/_forum-listing.scss
Labels: priority, ready for review, has D8 dependency

#1748 EWL-10904: Prevent Alert Banner Close Button Clipping
  styleguide/source/assets/scss/02-molecules/_alert.scss
Labels: priority, ready for review

#1747 EWL-11017: Article Shift Feedback
  styleguide/source/assets/scss/04-templates/_two_column-right.scss
Labels: priority, ready for review

#1749 EWL-10995: Mobile Page grouper regression fixes.
  styleguide/source/assets/scss/00-base/__01.mixins/_gutter_mixin.scss
  styleguide/source/assets/scss/02-molecules/_page-grouping.scss
  styleguide/source/assets/scss/04-templates/_two_column-left.scss
  styleguide/source/assets/scss/04-templates/_two_column-right.scss
Labels: priority, ready for review

#1750 EWL-10995: Update page grouper layout issue.
  styleguide/source/assets/scss/02-molecules/_page-grouping.scss
  styleguide/source/assets/scss/03-organisms/_locker-navigation.scss
  styleguide/source/assets/scss/04-templates/_two_column-left.scss
  styleguide/source/assets/scss/04-templates/_two_column-right.scss
Labels: priority, ready for review

#1752 EWL-11039: Update search page skip to main content.
  styleguide/source/assets/scss/02-molecules/_search-header.scss
  styleguide/source/assets/scss/05-pages/_search-results.scss
Labels: ready for review, in review

#1753 EWL-11023: Update page grouper link font.
  styleguide/source/assets/scss/02-molecules/_page-grouping.scss
Labels: ready for review, in review

#1754 EWL-11016: Update anchor link functionality and positioning.
  styleguide/build.config.json
  styleguide/source/assets/js/anchor_links.js
  styleguide/source/assets/js/toc.js
  styleguide/source/assets/scss/05-pages/_news.scss
Labels: ready for review

#1756 EWL-10997: Page grouping text field title case removed.
  styleguide/source/assets/scss/02-molecules/_page-grouping.scss
Labels: ready for review

#1757 EWL-11021: Set correct font style in bulleted lists.
  styleguide/source/assets/scss/01-atoms/_unordered-list.scss
Labels: ready for review

#1755 EWL-10919: Product Nav Block Mobile
  styleguide/build.config.json
  styleguide/source/_patterns/01-atoms/media/icons/svg/drop-arrow-down.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/drop-arrow-up.twig
  styleguide/source/assets/icons/svg/drop-arrow-down.svg
  styleguide/source/assets/icons/svg/drop-arrow-up.svg
  styleguide/source/assets/js/product-menu.js
  styleguide/source/assets/scss/03-organisms/_footer.scss
  styleguide/source/assets/scss/03-organisms/_product-nav.scss
Labels: ready for review

#1762 EWL-10919: Product Nav Accessibility
  styleguide/source/assets/scss/02-molecules/_forum-listing.scss
  styleguide/source/assets/scss/03-organisms/_product-nav.scss
Labels: ready for review

#1759 EWL-10893: Fix empty link issue on annual interim block.
  styleguide/source/assets/scss/03-organisms/_annual-interum-block.scss
Labels: ready for review

#1761 EWL-11061: restore new comment forum flag
  styleguide/source/assets/scss/02-molecules/_forum-listing.scss
Labels: priority, ready for review, in review

#1766 EWL-10919: Product Nav Height
  styleguide/source/assets/js/product-menu.js
Labels: priority, ready for review

#1763 EWL-11060: Sort order displaying on mobile for every topic
  styleguide/source/assets/js/forum-styling.js
  styleguide/source/assets/scss/02-molecules/_forum-listing.scss
Labels: priority, ready for review

#1764 EWL-11016: Update page grouper active link styling to account for mob…
  styleguide/source/assets/js/anchor_links.js
  styleguide/source/assets/scss/02-molecules/_page-grouping.scss
  styleguide/source/assets/scss/04-templates/_two_column-left.scss
  styleguide/source/assets/scss/05-pages/_news.scss
Labels: priority, ready for review

#1760 AWMEE-19: Prompt for Sign-in Throughout AMAOne
  styleguide/build.config.json
  styleguide/source/_patterns/02-molecules/sign-in-dropdown/sign-in-dropdown.json
  styleguide/source/_patterns/02-molecules/sign-in-dropdown/sign-in-dropdown.md
  styleguide/source/_patterns/02-molecules/sign-in-dropdown/sign-in-dropdown.twig
  styleguide/source/_patterns/02-molecules/sign-in-dropdown/sign-in-dropdown~logged-in.json
  styleguide/source/_patterns/02-molecules/sign-in-dropdown/sign-in-dropdown~logged-out-open.json
  styleguide/source/_patterns/02-molecules/sign-in-dropdown/sign-in-dropdown~logged-out.json
  styleguide/source/assets/js/explore-dropdown.js
  styleguide/source/assets/js/sign-in-dropdown.js
  styleguide/source/assets/js/vendor/js.cookie.min.js
  styleguide/source/assets/js/vendor/once.min.js
  styleguide/source/assets/scss/02-molecules/_sign-in-dropdown.scss
Labels: Approve but DON'T MERGE, javascript

#1769 EWL-10991: Fix offset of toc and page grouper anchor links.
  styleguide/source/assets/js/anchor_links.js
Labels: priority
