Repository AmericanMedicalAssociation/ama-style-guide-2, pull requests merged in 2024-07, with the labels that each got.

#1663 EWL-10864: Redesign for article page grouper.
  styleguide/source/assets/scss/02-molecules/_page-grouping.scss
Labels: priority, ready for review

#1666 EWL-10854: Subcat Pills Feedback
  styleguide/source/assets/scss/03-organisms/_subcategory-exploration.scss
Labels: priority, ready for review, in review

#1668 EWL-10853: 30/70 block desktop sizing fix.
  styleguide/source/assets/scss/02-molecules/_thirty-seventy-block.scss
Labels: priority, ready for review

#1669 EWL-10864: Page grouper mobile fix.
  styleguide/source/assets/scss/02-molecules/_page-grouping.scss
Labels: priority, ready for review

#1670 EWL-10864: Update page grouper links horizontal sizing
  styleguide/source/assets/scss/02-molecules/_page-grouping.scss
Labels: priority, ready for review, in review

#1671 EWL-10854: Focus on Subcat Links
  styleguide/source/assets/scss/03-organisms/_subcategory-exploration.scss
Labels: priority, ready for review

#1673 EWL-10873: Fix header overlapping content on resize.
  styleguide/source/assets/js/nav.js
Labels: ready for review

#1676 EWL-10644: Update gating block styling to display appropriate heading…
  styleguide/source/assets/scss/03-organisms/_gating-block.scss
Labels: priority, ready for review

#1675 EWL-10732: Add spacing below Did you mean?
  styleguide/source/assets/scss/02-molecules/_global-search.scss
Labels: priority, ready for review, in review

#1658 DCP-106: Update Styling for Claim Box on Profile Page
  styleguide/source/_patterns/02-molecules/dr-finder-profile-header/dr-finder-profile-header.twig
  styleguide/source/assets/scss/02-molecules/_dr-finder-claim.scss
  styleguide/source/assets/scss/02-molecules/_dr-finder-profile-header.scss
Labels: priority, ready for review, in review, has dependency!, AMA Find A Doctor

#1679 EWL-10882: Update article listicle styling.
  styleguide/source/assets/js/listicle.js
  styleguide/source/assets/scss/01-atoms/_listicle.scss
Labels: priority, ready for review, in review

#1677 EWL-10888: create search suggestions styles
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-search-grey.twig
  styleguide/source/assets/icons/svg/icon-search-grey.svg
  styleguide/source/assets/js/search-suggestions.js
  styleguide/source/assets/scss/02-molecules/_search-suggestions.scss
Labels: priority, ready for review, in review

#1681 EWL-10695: Update article toc markup for better ada compliance
  styleguide/source/assets/scss/02-molecules/_table-of-contents.scss
Labels: question, ready for review

#1682 EWL-10888: create search suggestions styles
  styleguide/source/assets/js/search-suggestions.js
  styleguide/source/assets/scss/02-molecules/_search-suggestions.scss
Labels: priority, ready for review, in review

#1685 EWL-10900: Update hamburger menu styling.
  styleguide/source/assets/scss/01-atoms/_menu-icon.scss
Labels: ready for review, in review

#1686 EWL-10882: Update listicle styling.
  styleguide/source/assets/scss/01-atoms/_listicle.scss
Labels: priority, ready for review, in review

#1688 EWL-10888: changed icon. Refined padding.
  styleguide/source/assets/icons/svg/icon-search-gray.svg
  styleguide/source/assets/icons/svg/icon-search-grey.svg
  styleguide/source/assets/scss/02-molecules/_search-suggestions.scss
Labels: priority, ready for review, in review

#1691 EWL-10879: Forum style updates
  styleguide/source/assets/js/forum-styling.js
  styleguide/source/assets/scss/02-molecules/_forum-listing.scss
Labels: priority, ready for review, in review
