Repository AmericanMedicalAssociation/ama-style-guide-2, pull requests merged in 2024-11, with the labels that each got.

#1808 AWMEE-671: AMAOne: Logged Out - Quick Links v2
  styleguide/source/_patterns/01-atoms/media/icons/svg/quick-links/icon-advocacy-purple.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/quick-links/icon-advocacy-white.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/quick-links/icon-ambulance-purple.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/quick-links/icon-ambulance-white.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/quick-links/icon-career-purple.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/quick-links/icon-career-white.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/quick-links/icon-documents-purple.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/quick-links/icon-documents-white.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/quick-links/icon-event-purple.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/quick-links/icon-event-white.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/quick-links/icon-hospital-purple.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/quick-links/icon-hospital-white.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/quick-links/icon-house-purple.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/quick-links/icon-house-white.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/quick-links/icon-lightbulb-purple.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/quick-links/icon-lightbulb-white.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/quick-links/icon-prescription-purple.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/quick-links/icon-prescription-white.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/quick-links/icon-search-purple.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/quick-links/icon-search-white.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/quick-links/icon-stethoscope-purple.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/quick-links/icon-stethoscope-white.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/quick-links/icon-syringe-purple.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/quick-links/icon-syringe-white.twig
  styleguide/source/_patterns/02-molecules/personalized-quick-links/personalized-quick-links.md
  styleguide/source/_patterns/02-molecules/personalized-quick-links/personalized-quick-links.twig
  styleguide/source/_patterns/03-organisms/discover-ama-cta/discover-ama-cta.json
  styleguide/source/_patterns/03-organisms/discover-ama-cta/discover-ama-cta.md
  styleguide/source/_patterns/03-organisms/discover-ama-cta/discover-ama-cta.twig
  styleguide/source/_patterns/03-organisms/discover-ama-cta/discover-ama-cta~quick-links.json
  styleguide/source/assets/icons/svg/quick-links/icon-advocacy-purple.svg
  styleguide/source/assets/icons/svg/quick-links/icon-advocacy-white.svg
  styleguide/source/assets/icons/svg/quick-links/icon-ambulance-purple.svg
  styleguide/source/assets/icons/svg/quick-links/icon-ambulance-white.svg
  styleguide/source/assets/icons/svg/quick-links/icon-career-purple.svg
  styleguide/source/assets/icons/svg/quick-links/icon-career-white.svg
  styleguide/source/assets/icons/svg/quick-links/icon-documents-purple.svg
  styleguide/source/assets/icons/svg/quick-links/icon-documents-white.svg
  styleguide/source/assets/icons/svg/quick-links/icon-event-purple.svg
  styleguide/source/assets/icons/svg/quick-links/icon-event-white.svg
  styleguide/source/assets/icons/svg/quick-links/icon-hospital-purple.svg
  styleguide/source/assets/icons/svg/quick-links/icon-hospital-white.svg
  styleguide/source/assets/icons/svg/quick-links/icon-house-purple.svg
  styleguide/source/assets/icons/svg/quick-links/icon-house-white.svg
  styleguide/source/assets/icons/svg/quick-links/icon-lightbulb-purple.svg
  styleguide/source/assets/icons/svg/quick-links/icon-lightbulb-white.svg
  styleguide/source/assets/icons/svg/quick-links/icon-prescription-purple.svg
  styleguide/source/assets/icons/svg/quick-links/icon-prescription-white.svg
  styleguide/source/assets/icons/svg/quick-links/icon-search-purple.svg
  styleguide/source/assets/icons/svg/quick-links/icon-search-white.svg
  styleguide/source/assets/icons/svg/quick-links/icon-stethoscope-purple.svg
  styleguide/source/assets/icons/svg/quick-links/icon-stethoscope-white.svg
  styleguide/source/assets/icons/svg/quick-links/icon-syringe-purple.svg
  styleguide/source/assets/icons/svg/quick-links/icon-syringe-white.svg
  styleguide/source/assets/scss/03-organisms/_discover-ama-cta.scss
  styleguide/source/assets/scss/03-organisms/_personalized-account-hub.scss
Labels: priority, ready for review

#1800 EWL-11090: Homepage background
  styleguide/source/assets/scss/00-base/_colors.scss
  styleguide/source/assets/scss/05-pages/_homepage.scss
Labels: priority

#1804 EWL-11143: Update image link fix on articles
  styleguide/source/assets/scss/05-pages/_news.scss
Labels: priority, ready for review

#1810 EWL-11156: restore dropdown cookie.
  styleguide/source/assets/js/sign-in-dropdown.js
Labels: priority, ready for review

#1809 EWL-11155: exclude links with a /#/ component from acting as anchor links.
  styleguide/source/assets/js/anchor_links.js
Labels: priority, ready for review

#1811 EWL-11099: Update sign in menu alignment on mobile
  styleguide/source/assets/scss/02-molecules/_sign-in-dropdown.scss
Labels: priority, ready for review

#1805 EWL-11129: Update morning rounds promo homepage design.
  styleguide/source/assets/scss/02-molecules/_subscribe-promo.scss
  styleguide/source/assets/scss/05-pages/_homepage.scss
Labels: priority, ready for review

#1813 AWMEE-685: AMAOne: Safari mobile view for V2 Quick links
  styleguide/source/assets/scss/03-organisms/_discover-ama-cta.scss
  styleguide/source/assets/scss/03-organisms/_personalized-account-hub.scss
Labels: in review

#1814 EWL-11135: Homepage Hero
  styleguide/source/assets/scss/02-molecules/_full_hero_banner.scss
  styleguide/source/assets/scss/03-organisms/_personalized-account-hub.scss
Labels: ready for review, in review

#1818 EWL-11080: Update homepage testimonial styling
  styleguide/source/assets/images/arrow-right-purple-alt.png
  styleguide/source/assets/scss/03-organisms/_homepage-social-modual.scss
Labels: priority, ready for review

#1820 EWL-11140: update font edge cases and scaling.
  styleguide/source/assets/scss/00-base/__01.mixins/_font-variables.scss
  styleguide/source/assets/scss/00-base/_typography.scss
  styleguide/source/assets/scss/02-molecules/_partner-promo.scss
  styleguide/source/assets/scss/02-molecules/_sign-in-dropdown.scss
  styleguide/source/assets/scss/02-molecules/_subscribe-promo.scss
  styleguide/source/assets/scss/03-organisms/_annual-interum-block.scss
  styleguide/source/assets/scss/03-organisms/_category-page-article-stub.scss
  styleguide/source/assets/scss/03-organisms/_membership.scss
  styleguide/source/assets/scss/03-organisms/_product-nav.scss
  styleguide/source/assets/scss/03-organisms/_subcategory-exploration.scss
Labels: ready for review

#1817 bugfix/make users click twice if they don't have an account.
  styleguide/source/assets/js/sign-in-dropdown.js
Labels: priority, ready for review

#1819 EWL-11129: Update homepage morning rounds styling.
  styleguide/source/assets/scss/02-molecules/_sign-in-dropdown.scss
  styleguide/source/assets/scss/02-molecules/_subscribe-promo.scss
  styleguide/source/assets/scss/05-pages/_homepage.scss
Labels: priority, ready for review

#1821 EWL-11135: Hero Feedback
  styleguide/source/assets/scss/00-base/__01.mixins/_ama-button.scss
  styleguide/source/assets/scss/02-molecules/_full_hero_banner.scss
Labels: priority, ready for review

#1824 EWL-11129: Fix homepage subscribe promo spacing.
  styleguide/source/assets/scss/02-molecules/_subscribe-promo.scss
Labels: priority, ready for review

#1823 EWL-11087: Homepage testimonial design update.
  styleguide/source/assets/scss/03-organisms/_homepage-social-modual.scss
Labels: priority, ready for review, in review

#1827 EWL-11140: switch colors back. Convert promo h2s to h3s
  styleguide/source/assets/scss/00-base/__01.mixins/_ama-button.scss
  styleguide/source/assets/scss/00-base/_typography.scss
  styleguide/source/assets/scss/01-atoms/_display-switch.scss
  styleguide/source/assets/scss/01-atoms/_links.scss
  styleguide/source/assets/scss/01-atoms/_listicle.scss
  styleguide/source/assets/scss/01-atoms/_search-field.scss
  styleguide/source/assets/scss/01-atoms/_select-menu.scss
  styleguide/source/assets/scss/02-molecules/_alert.scss
  styleguide/source/assets/scss/02-molecules/_category-hero.scss
  styleguide/source/assets/scss/02-molecules/_global-search.scss
  styleguide/source/assets/scss/02-molecules/_jama.scss
  styleguide/source/assets/scss/02-molecules/_partner-promo.scss
  styleguide/source/assets/scss/02-molecules/_promo.scss
  styleguide/source/assets/scss/02-molecules/_search-suggestions.scss
  styleguide/source/assets/scss/02-molecules/_sign-in-dropdown.scss
  styleguide/source/assets/scss/02-molecules/_subscribe-promo.scss
  styleguide/source/assets/scss/02-molecules/_table-of-contents.scss
  styleguide/source/assets/scss/02-molecules/_tags.scss
  styleguide/source/assets/scss/02-molecules/_thirty-seventy-block.scss
  styleguide/source/assets/scss/02-molecules/_trending-block.scss
  styleguide/source/assets/scss/02-molecules/hub/_hub-form.scss
  styleguide/source/assets/scss/03-organisms/_category-nav.scss
  styleguide/source/assets/scss/03-organisms/_category-page-article-stub.scss
  styleguide/source/assets/scss/03-organisms/_discover-ama-cta.scss
  styleguide/source/assets/scss/03-organisms/_featured-links.scss
  styleguide/source/assets/scss/03-organisms/_filter.scss
  styleguide/source/assets/scss/03-organisms/_footer.scss
  styleguide/source/assets/scss/03-organisms/_home-page-hero.scss
  styleguide/source/assets/scss/03-organisms/_homepage-social-modual.scss
  styleguide/source/assets/scss/03-organisms/_masthead.scss
  styleguide/source/assets/scss/03-organisms/_membership.scss
  styleguide/source/assets/scss/03-organisms/_personalized-account-hub.scss
  styleguide/source/assets/scss/03-organisms/_social-share.scss
  styleguide/source/assets/scss/03-organisms/_subcategory-exploration.scss
  styleguide/source/assets/scss/05-pages/_glossary.scss
  styleguide/source/assets/scss/05-pages/_homepage.scss
  styleguide/source/assets/scss/05-pages/_hub-page.scss
  styleguide/source/assets/scss/05-pages/_news.scss
Labels: priority, ready for review

#1830 EWL-11129: Homepage morning rounds styling update.
  styleguide/source/assets/scss/02-molecules/_subscribe-promo.scss
Labels: priority, ready for review

#1834 EWL-11175: Update hero banner to make heading text clickable.
  styleguide/source/assets/scss/02-molecules/_full_hero_banner.scss
Labels: priority, ready for review, in review

#1833 EWL-11172: Fix sign in drop down menu border clipping issue.
  styleguide/source/assets/scss/03-organisms/_product-nav.scss
Labels: priority, ready for review, in review

#1832 EWL-11101: Close sign in drop down after tab through
  styleguide/source/assets/js/sign-in-dropdown.js
Labels: priority, ready for review, in review
