Repository AmericanMedicalAssociation/ama-style-guide-2, pull requests merged in 2024-02, with the labels that each got.

#1549 EWL-0: Clean up organism templates, remove defunct templates.
  styleguide/source/_patterns/03-organisms/homepage-social-module/homepage-social-module-no-feature.json
  styleguide/source/_patterns/03-organisms/homepage-social-module/homepage-social-module-three-up.json
  styleguide/source/_patterns/03-organisms/homepage-social-module/homepage-social-module.json
  styleguide/source/_patterns/03-organisms/masthead/masthead.json
  styleguide/source/_patterns/03-organisms/masthead/masthead~as-indented.json
  styleguide/source/_patterns/03-organisms/masthead/masthead~as-no-title.json
  styleguide/source/_patterns/03-organisms/masthead/masthead~as-series-is-subscribed.json
  styleguide/source/_patterns/03-organisms/masthead/masthead~as-series-subscribe.json
  styleguide/source/_patterns/03-organisms/masthead/masthead~as-title-only.json
  styleguide/source/_patterns/03-organisms/masthead/masthead~with-subtitle-as-centered.json
  styleguide/source/_patterns/03-organisms/masthead/masthead~with-subtitle-as-indented.json
  styleguide/source/_patterns/03-organisms/masthead/masthead~with-subtitle.json
  styleguide/source/_patterns/03-organisms/news_header/news_header.json
  styleguide/source/_patterns/03-organisms/news_header/news_header.md
  styleguide/source/_patterns/03-organisms/news_header/news_header.twig
Labels: ready for review

#1564 EWL-10659: Fix layout builder error preventing article previews from …
  styleguide/source/assets/scss/02-molecules/_form.scss
Labels: priority, ready for review

#1558 EWL-10431: Set focus state on hub page elements
  styleguide/source/assets/scss/00-base/__01.mixins/_ama-button-base.scss
  styleguide/source/assets/scss/02-molecules/hub/_hub-card.scss
  styleguide/source/assets/scss/03-organisms/_hub_page_hero.scss
  styleguide/source/assets/scss/03-organisms/_main-navigation.scss
Labels: priority, ready for review

#1541 EWL-10583: User Profile Page Updates
  styleguide/source/assets/scss/05-pages/_user.scss
Labels: priority, ready for review, in review

#1562 EWL-10616: Update subheading color to improve contrast.
  styleguide/source/assets/scss/02-molecules/_block-quote.scss
  styleguide/source/assets/scss/05-pages/_news.scss
Labels: priority, ready for review, in review

#1565 EWL-10586: Set half-width promos to full width on mobile.
  styleguide/source/assets/scss/03-organisms/_related_coverage.scss
Labels: priority, ready for review

#1559 EWL-0: Remove various unused molecule components from styleguide.
  styleguide/source/_patterns/02-molecules/agenda-table.json
  styleguide/source/_patterns/02-molecules/agenda-table.md
  styleguide/source/_patterns/02-molecules/agenda-table.twig
  styleguide/source/_patterns/02-molecules/agenda.json
  styleguide/source/_patterns/02-molecules/agenda.md
  styleguide/source/_patterns/02-molecules/agenda.twig
  styleguide/source/_patterns/02-molecules/alert.twig
  styleguide/source/_patterns/02-molecules/explore-menu.json
  styleguide/source/_patterns/02-molecules/explore-menu.md
  styleguide/source/_patterns/02-molecules/explore-menu.twig
  styleguide/source/_patterns/02-molecules/social-share.json
  styleguide/source/_patterns/02-molecules/visual-subcategory.json
  styleguide/source/_patterns/02-molecules/visual-subcategory.md
  styleguide/source/_patterns/02-molecules/visual-subcategory.twig
  styleguide/source/assets/scss/02-molecules/_alert.scss
Labels: ready for review, in review

#1561 EWL-10055: Fix category promo blocks image aspect ratio.
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-menu-open.twig
  styleguide/source/assets/scss/02-molecules/_partner-promo.scss
  styleguide/source/assets/scss/02-molecules/_subscribe-promo.scss
  styleguide/source/assets/scss/03-organisms/_membership.scss
Labels: ready for review, in review

#1536 EWL-10549: Fix dropdown menu issue on contact page.
  styleguide/source/assets/scss/03-organisms/_contact-us-webform.scss
Labels: priority, ready for review

#1567 EWL-10431: Add focus state to hub banner cta's.
  styleguide/source/assets/scss/05-pages/_hub-page.scss
Labels: priority, ready for review

#1568 EWL-10431: Add tab navigation and focus state to hub page hero headin…
  styleguide/source/assets/js/hub-banner.js
  styleguide/source/assets/scss/03-organisms/_hub_page_hero.scss
Labels: priority, ready for review

#1569 EWL-10627: Update policy finder position on search page.
  styleguide/source/assets/scss/02-molecules/search-result/_search-connector.scss
Labels: priority, ready for review

#1572 EWL-10623: Add focus state to alert and main nav elements.
  styleguide/source/assets/js/main-navigation.js
  styleguide/source/assets/scss/00-base/__01.mixins/_ama-button-base.scss
  styleguide/source/assets/scss/01-atoms/_site_logo.scss
  styleguide/source/assets/scss/02-molecules/_alert.scss
  styleguide/source/assets/scss/02-molecules/_global-search.scss
  styleguide/source/assets/scss/02-molecules/_hero-evergreen.scss
  styleguide/source/assets/scss/02-molecules/_sign-in-dropdown.scss
  styleguide/source/assets/scss/03-organisms/_category-nav.scss
  styleguide/source/assets/scss/03-organisms/_main-navigation.scss
  styleguide/source/assets/scss/03-organisms/_org-nav.scss
  styleguide/source/assets/scss/03-organisms/_product-nav.scss
Labels: priority, ready for review

#1574 EWL-10670: Set headings on search connector blocks
  styleguide/source/assets/scss/02-molecules/search-result/_search-connector.scss
Labels: priority, ready for review

#1575 EWL-10626: Styling for Redesigned 30/70 Block
  styleguide/source/assets/scss/02-molecules/_thirty-seventy-block.scss
Labels: priority, ready for review, has D8 dependency
