Repository AmericanMedicalAssociation/ama-style-guide-2, pull requests merged in 2024-08, with the labels that each got.

#1693 DCP-207: Update Claim Button Styling
  styleguide/source/assets/scss/02-molecules/_dr-finder-claim.scss
  styleguide/source/assets/scss/02-molecules/_dr-finder-profile-header.scss
Labels: priority, ready for review, AMA Find A Doctor

#1694 Bugfix/convert-sticky-js-to-css
  styleguide/source/assets/js/main-navigation.js
  styleguide/source/assets/js/nav.js
  styleguide/source/assets/scss/02-molecules/_global-search.scss
  styleguide/source/assets/scss/03-organisms/_main-navigation.scss
Labels: priority, ready for review, Do not merge

#1687 bugfix/resolve interaction errors for the sign-in menu
  styleguide/source/assets/js/sign-in-dropdown.js
Labels: priority, ready for review

#1698 EWL-10961: Shift Article Body Content Right
  styleguide/source/assets/scss/04-templates/_two_column-left.scss
Labels: question, ready for review, has D8 dependency

#1699 EWL-10924: Update mobile alert banner padding.
  styleguide/source/assets/scss/02-molecules/_alert.scss
Labels: priority, ready for review, in review

#1700 EWL-10908: Update featured link list styling.
  styleguide/source/assets/scss/03-organisms/_featured-links.scss
Labels: priority, ready for review, in review

#1701 EWL-10884: Font Change
  styleguide/source/assets/scss/00-base/__01.mixins/_font-variables.scss
  styleguide/source/assets/scss/00-base/_typography.scss
  styleguide/source/assets/scss/01-atoms/_unordered-list.scss
  styleguide/source/assets/scss/02-molecules/_category-theme.scss
  styleguide/source/assets/scss/02-molecules/_forum-topic.scss
  styleguide/source/assets/scss/02-molecules/_partner-promo.scss
  styleguide/source/assets/scss/02-molecules/_subcategory-page-article-stub.scss
  styleguide/source/assets/scss/02-molecules/_tool.scss
  styleguide/source/assets/scss/02-molecules/_upcoming-event.scss
  styleguide/source/assets/scss/02-molecules/search-result/_search-connector.scss
  styleguide/source/assets/scss/02-molecules/search-result/_search-result.scss
  styleguide/source/assets/scss/03-organisms/_annual-interum-block.scss
  styleguide/source/assets/scss/03-organisms/_footer.scss
  styleguide/source/assets/scss/03-organisms/_homepage-social-modual.scss
  styleguide/source/assets/scss/03-organisms/_hub_page_hero.scss
  styleguide/source/assets/scss/03-organisms/_membership.scss
  styleguide/source/assets/scss/05-pages/_hub-page.scss
  styleguide/source/assets/scss/05-pages/_people-listing.scss
  styleguide/source/assets/scss/05-pages/_topic-index.scss
Labels: priority, ready for review

#1695 EWL-10199: Add clear search to catalog of topics.
  styleguide/source/assets/scss/05-pages/_glossary.scss
Labels: ready for review

#1703 EWL-10884: Font Change Feedback
  styleguide/source/assets/scss/00-base/__01.mixins/_font-variables.scss
Labels: priority, ready for review

#1684 EWL-10822: Fix subscribe button padding for unauthenticated users.
  styleguide/source/assets/scss/03-organisms/_series-subscribe.scss
Labels: ready for review

#1702 EWL-10917: Update Article Page Grouper position and design.
  styleguide/source/assets/scss/02-molecules/_page-grouping.scss
  styleguide/source/assets/scss/04-templates/_two_column-left.scss
  styleguide/source/assets/scss/04-templates/_two_column-right.scss
  styleguide/source/assets/scss/05-pages/_news.scss
Labels: priority, ready for review, in review

#1706 EWL-10884: Font Change Feedback #2
  styleguide/source/assets/scss/02-molecules/_alert.scss
  styleguide/source/assets/scss/02-molecules/_promo.scss
  styleguide/source/assets/scss/02-molecules/search-result/_search-result.scss
Labels: priority, ready for review

#1705 EWL-10908: Update featured link list padding on mobile.
  styleguide/source/assets/scss/03-organisms/_featured-links.scss
Labels: priority, ready for review

#1704 EWL-10906: hide resolution column
  styleguide/source/assets/scss/02-molecules/_forum-listing.scss
Labels: priority, ready for review, in review

#1711 EWL-10917: Update page grouper styling to fix on focus styling.
  styleguide/source/assets/scss/02-molecules/_page-grouping.scss
Labels: priority, ready for review, in review

#1712 EWL-10923: Fix vertical padding issue on 30-70 mobile CTA.
  styleguide/source/assets/scss/02-molecules/_thirty-seventy-block.scss
Labels: ready for review

#1715 EWL-10954: Search header mobile styling updates.
  styleguide/source/assets/js/main-navigation.js
  styleguide/source/assets/scss/02-molecules/_global-search.scss
Labels: priority, ready for review

#1714 EWL-10917: Fix list styling issue on article pages.
  styleguide/source/assets/scss/01-atoms/_ordered-list.scss
  styleguide/source/assets/scss/02-molecules/_page-grouping.scss
Labels: priority, ready for review

#1717 EWL-10917: grouper top border fix
  styleguide/source/assets/scss/02-molecules/_page-grouping.scss
Labels: ready for review

#1713 EWL-10921: Update Morning Rounds Thank You page.
  styleguide/source/assets/scss/00-base/_webform_confirmation.scss
Labels: priority, ready for review

#1719 EWL-10798: Display pronoun fields on people listing pages.
  styleguide/source/assets/scss/02-molecules/_people-listing.scss
Labels: priority, ready for review

#1722 EWL-10995: Update page grouper design and functionality on mobile
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-opendropdown-black.twig
  styleguide/source/assets/icons/svg/icon-opendropdown-black.svg
  styleguide/source/assets/scss/02-molecules/_page-grouping.scss
  styleguide/source/assets/scss/03-organisms/_locker-navigation.scss
  styleguide/source/assets/scss/03-organisms/_main-navigation.scss
Labels: priority, ready for review, in review

#1726 EWL-10892: Update homepage blocks to fix tab order.
  styleguide/source/assets/scss/02-molecules/_product.scss
  styleguide/source/assets/scss/02-molecules/_upcoming-event.scss
  styleguide/source/assets/scss/03-organisms/_annual-interum-block.scss
Labels: priority, ready for review
