Repository AmericanMedicalAssociation/ama-style-guide-2, pull requests merged in 2024-05, with the labels that each got.

#1608 EWL-10757: Set sticky scroll on product nav bar.
  styleguide/source/assets/js/locker-menu.js
  styleguide/source/assets/js/main-navigation.js
  styleguide/source/assets/js/nav.js
  styleguide/source/assets/scss/02-molecules/_sign-in-dropdown.scss
  styleguide/source/assets/scss/03-organisms/_main-navigation.scss
Labels: priority, ready for review

#1621 EWL-10757: Reconfigure main nav, product nav and bookmark bar to use …
  styleguide/source/assets/js/locker-menu.js
  styleguide/source/assets/js/nav.js
  styleguide/source/assets/scss/02-molecules/_sign-in-dropdown.scss
  styleguide/source/assets/scss/03-organisms/_main-navigation.scss
Labels: priority, ready for review

#1626 EWL-10812: Fix spacing issue with membership custom blocks on articles.
  styleguide/source/assets/scss/03-organisms/_membership.scss
Labels: priority, ready for review

#1619 EWL-10783: Fix subscribe button padding for mobile articles.
  styleguide/source/assets/scss/05-pages/_news.scss
Labels: priority, ready for review

#1627 EWL-10801: banner redesign
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-alert-alert.twig
  styleguide/source/assets/icons/svg/icon-alert-alert.svg
  styleguide/source/assets/scss/02-molecules/_alert.scss
Labels: priority, ready for review, in review

#1630 EWL-10520: Update hub page banner styling when single cta is used
  styleguide/source/assets/scss/05-pages/_hub-page.scss
Labels: priority, ready for review

#1629 EWL-10521: Update padding when single cta is used on hub page hero bl…
  styleguide/source/assets/scss/03-organisms/_hub_page_hero.scss
Labels: priority, ready for review

#1632 EWL-10783: Fix vertical alignment of subscribe button on mobile artic…
  styleguide/source/assets/scss/03-organisms/_series-subscribe.scss
  styleguide/source/assets/scss/05-pages/_news.scss
Labels: priority, ready for review, in review

#1624 Restore Dr. Finder Main Navigation Styles
  styleguide/source/assets/scss/03-organisms/_main-navigation.scss
Labels: priority, ready for review, in review, AMA Find A Doctor

#1628 DCP-192: Add SEO Canned Text to Physician Pages
  styleguide/source/_patterns/02-molecules/dr-finder-profile-header/dr-finder-profile-header.twig
  styleguide/source/assets/scss/02-molecules/_dr-finder-profile-header.scss
  styleguide/source/assets/scss/02-molecules/_dr-finder-profile.scss
  styleguide/source/assets/scss/03-organisms/_dr-finder-search.scss
Labels: priority, ready for review, in review, has dependency!, AMA Find A Doctor

#1625 DCP-196: Styling for Enhanced Claim Text
  styleguide/source/_patterns/02-molecules/dr-finder-profile-header/dr-finder-profile-header.twig
Labels: priority, ready for review, has dependency!, AMA Find A Doctor
