Repository AmericanMedicalAssociation/ama-style-guide-2, pull requests merged in 2024-03, with the labels that each got.

#1577 Add thirty seventy block pattern
  styleguide/source/_patterns/02-molecules/thirty-seventy-block/thirty-seventy-block.json
  styleguide/source/_patterns/02-molecules/thirty-seventy-block/thirty-seventy-block.md
  styleguide/source/_patterns/02-molecules/thirty-seventy-block/thirty-seventy-block.twig
  styleguide/source/_patterns/02-molecules/thirty-seventy-block/thirty-seventy-block~as-double-button.json
  styleguide/source/_patterns/02-molecules/thirty-seventy-block/thirty-seventy-block~as-full.json
  styleguide/source/_patterns/02-molecules/thirty-seventy-block/thirty-seventy-block~as-single-button.json
Labels: priority

#1579 EWL-10626: Remove Text Underline on Hover
  styleguide/source/assets/scss/02-molecules/_thirty-seventy-block.scss
Labels: priority, ready for review

#1571 DCP-183: Add Status Message Icons and Update Styling
  styleguide/source/assets/images/dr-finder/error.svg
  styleguide/source/assets/images/dr-finder/info.svg
  styleguide/source/assets/images/dr-finder/status.svg
  styleguide/source/assets/images/dr-finder/warning.svg
  styleguide/source/assets/scss/05-pages/_dr-finder-messages.scss
Labels: priority, ready for review, in review, AMA Find A Doctor

#1582 EWL-10626: Remove Bottom Border from Block When Placed in Index Page
  styleguide/source/assets/scss/02-molecules/_thirty-seventy-block.scss
Labels: priority, ready for review

#1583 EWL-10627: Fix search connector block display on mobile.
  styleguide/source/assets/scss/02-molecules/search-result/_search-connector.scss
Labels: priority, ready for review

#1584 adjust margins for article block placement
  styleguide/source/assets/scss/02-molecules/_thirty-seventy-block.scss
Labels: in review

#1588 EWL-10679: Update trending block with heading elements.
  styleguide/source/assets/scss/02-molecules/_trending-block.scss
  styleguide/source/assets/scss/02-molecules/_trending-icon.scss
Labels: priority, ready for review

#1576 Add Explore Menu Pattern Back to SG for Dr. Finder
  styleguide/source/_patterns/02-molecules/dr-finder-explore-menu/dr-finder-explore-menu.json
  styleguide/source/_patterns/02-molecules/dr-finder-explore-menu/dr-finder-explore-menu.md
  styleguide/source/_patterns/02-molecules/dr-finder-explore-menu/dr-finder-explore-menu.twig
  styleguide/source/_patterns/03-organisms/dr-finder-main-navigation/dr-finder-main-navigation-logged-in.twig
  styleguide/source/_patterns/03-organisms/dr-finder-main-navigation/dr-finder-main-navigation-non-physician.twig
  styleguide/source/_patterns/03-organisms/dr-finder-main-navigation/dr-finder-main-navigation.twig
  styleguide/source/assets/scss/02-molecules/_explore-menu.scss
Labels: priority, ready for review, AMA Find A Doctor

#1573 DCP-187: Update Padding for Profile Buttons
  styleguide/source/assets/scss/02-molecules/_dr-finder-modal.scss
  styleguide/source/assets/scss/02-molecules/_dr-finder-profile-header.scss
  styleguide/source/assets/scss/02-molecules/_dr-finder-profile.scss
Labels: priority, AMA Find A Doctor

#1587 EWL-10686: Set hover state on subscribe promo.
  styleguide/source/assets/scss/02-molecules/_subscribe-promo.scss
Labels: priority, ready for review

#1591 EWL-10667: Forums Resolution label
  styleguide/source/assets/scss/02-molecules/_forum-listing.scss
Labels: priority, ready for review

#1592 EWL-10666: Topics Subscribe
  styleguide/source/assets/scss/03-organisms/_series-subscribe.scss
Labels: priority, ready for review

#1585 EWL-10681: Fix display of dropdown menus on forms.
  styleguide/source/assets/scss/03-organisms/_contact-us-webform.scss
Labels: priority, ready for review

#1590 EWL-10721: Trending block markup update
  styleguide/source/assets/scss/02-molecules/_trending-block.scss
Labels: priority, ready for review

#1593 EWL-10754: Update forum topic display to prevent table header wrapping.
  styleguide/source/assets/scss/02-molecules/_forum-listing.scss
Labels: priority, ready for review

#1581 EWL-10715: Update heading elements for topic page.
  styleguide/source/assets/scss/01-atoms/_content-grouping-header.scss
Labels: ready for review

#1580 EWL-10716: Structure category headings.
  styleguide/source/assets/scss/03-organisms/_tools.scss
Labels: ready for review

#1594 EWL-10741: Adds border line below last row on category pages.
  styleguide/source/assets/scss/05-pages/_category.scss
Labels: ready for review
