Repository AmericanMedicalAssociation/ama-style-guide-2, pull requests merged in 2024-06, with the labels that each got.

#1635 DCP-196: Move Path() Function to Theme Twig
  styleguide/source/_patterns/02-molecules/dr-finder-profile-header/dr-finder-profile-header.twig
Labels: priority, ready for review, has dependency!, AMA Find A Doctor

#1636 Add Dr. Finder Specific Alert Banner Styling
  styleguide/source/assets/scss/02-molecules/_dr-finder-alert.scss
Labels: priority, ready for review, AMA Find A Doctor

#1640 EWL-10844: forum mobile design
  styleguide/source/assets/scss/02-molecules/_forum-list.scss
  styleguide/source/assets/scss/02-molecules/_forum-listing.scss
  styleguide/source/assets/scss/02-molecules/_forum-topic.scss
Labels: priority, ready for review

#1638 EWL-10818: Homepage Org/Cat Navigation
  styleguide/source/assets/scss/03-organisms/_category-nav.scss
  styleguide/source/assets/scss/03-organisms/_org-nav.scss
  styleguide/source/assets/scss/05-pages/_homepage.scss
Labels: priority, ready for review, in review, has D8 dependency

#1642 EWL-10542: Update promo as inline custom block font sizing.
  styleguide/source/assets/scss/02-molecules/_promo.scss
Labels: priority, ready for review

#1641 EWL-10829: Update product navigation bar design.
  styleguide/source/assets/scss/03-organisms/_product-nav.scss
Labels: priority, ready for review

#1639 DCP-192: Update Claim Text to Use Formatted Variables
  styleguide/source/_patterns/02-molecules/dr-finder-profile-header/dr-finder-profile-header.twig
Labels: priority, ready for review, has dependency!, AMA Find A Doctor

#1647 update forum styling.
  styleguide/source/assets/scss/02-molecules/_forum-listing.scss
Labels: priority, ready for review

#1651 EWL-10818: Cat/Org Menu Feedback
  styleguide/source/assets/scss/05-pages/_homepage.scss
Labels: priority, ready for review

#1652 EWL-10829: Update product nav bar styling.
  styleguide/source/assets/scss/03-organisms/_product-nav.scss
Labels: priority, ready for review, in review

#1653 Bugfix: Update Claim Text Login and Create Account Variables
  styleguide/source/_patterns/02-molecules/dr-finder-profile-header/dr-finder-profile-header.twig
Labels: AMA Find A Doctor

#1656 EWL-10829: Product nav bar styling fixes.
  styleguide/source/assets/scss/03-organisms/_product-nav.scss
Labels: priority, ready for review

#1657 EWL-10818: Cat/Org Nav on Homepage
  styleguide/source/assets/scss/03-organisms/_org-nav.scss
  styleguide/source/assets/scss/05-pages/_homepage.scss
Labels: priority, ready for review, in review

#1659 EWL-10854: Subcat Pills on Cat Pages
  styleguide/source/assets/scss/03-organisms/_subcategory-exploration.scss
Labels: priority, ready for review

#1660 EWL-10853: Feature/ewl 10853 30/70 redesign
  styleguide/source/assets/scss/02-molecules/_thirty-seventy-block.scss
Labels: priority, ready for review

#1661 EWL-10878: 30/70 article redesign - based off of EWL-10853
  styleguide/source/assets/scss/02-molecules/_thirty-seventy-block.scss
Labels: priority, ready for review

#1662 EWL-10853: Add Styling Fixes for PR Feedback
  styleguide/source/assets/scss/02-molecules/_thirty-seventy-block.scss
Labels: priority, ready for review, in review
