Repository AmericanMedicalAssociation/ama-style-guide-2, pull requests merged in 2024-04, with the labels that each got.

#1597 EWL-10750: Restore breadcrumbs to articles.
  styleguide/source/assets/scss/03-organisms/_masthead.scss
Labels: priority, ready for review, in review

#1599 EWL-10750: Restore breadcrumbs to articles.
  styleguide/source/assets/js/form-items.js
Labels: priority, ready for review, in review

#1600 EWL-10772: Style new hub page forms.
  styleguide/source/assets/images/check_confirmation.svg
  styleguide/source/assets/js/form-items.js
  styleguide/source/assets/scss/02-molecules/hub/_hub-form.scss
Labels: priority, ready for review

#1603 EWL-10702: Changes for the form error when salesforce fails.
  styleguide/source/assets/scss/02-molecules/hub/_hub-form.scss
Labels: priority, ready for review

#1602 Fix Promo Block Style Regression
  styleguide/source/assets/scss/03-organisms/_membership.scss
Labels: priority, ready for review, AMA Find A Doctor

#1604 EWL-10750: Update subcat breadcrumb styling.
  styleguide/source/assets/scss/05-pages/_subcategory.scss
Labels: priority, ready for review, in review

#1605 EWL-10772: Hub page media styling fix.
  styleguide/source/assets/scss/02-molecules/hub/_hub-form.scss
Labels: priority, ready for review, in review

#1601 EWL-10779: Update focus states to use focus-visibility for better usa…
  styleguide/source/assets/scss/00-base/__01.mixins/_ama-button-base.scss
  styleguide/source/assets/scss/01-atoms/_site_logo.scss
  styleguide/source/assets/scss/02-molecules/_global-search.scss
  styleguide/source/assets/scss/02-molecules/hub/_hub-card.scss
  styleguide/source/assets/scss/02-molecules/hub/_hub-form.scss
  styleguide/source/assets/scss/03-organisms/_hub_page_hero.scss
  styleguide/source/assets/scss/03-organisms/_main-navigation.scss
  styleguide/source/assets/scss/05-pages/_hub-page.scss
Labels: priority, ready for review

#1598 DCP-195: Fix SERP Search and Filter Button Styling
  styleguide/source/assets/scss/01-atoms/_search-field-dr-finder.scss
  styleguide/source/assets/scss/02-molecules/_dr_finder-filter-buttons.scss
Labels: priority, ready for review, AMA Find A Doctor

#1609 EWL-10759: Apply focus state on tab through instead of click.
  styleguide/source/assets/scss/02-molecules/_global-search.scss
  styleguide/source/assets/scss/02-molecules/_sign-in-dropdown.scss
Labels: priority, ready for review, in review

#1611 EWL-10780: Featured Links custom block
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-next-blue.twig
  styleguide/source/assets/icons/svg/icon-next-blue.svg
  styleguide/source/assets/scss/03-organisms/_featured-links.scss
Labels: priority, ready for review, in review

#1612 EWL-10766: Add Styling for Mobile Share Bar Contextual Link
  styleguide/source/assets/scss/03-organisms/_social-share.scss
Labels: priority, ready for review, has D8 dependency

#1606 EWL-10608: Add doximity to share menu
  styleguide/source/assets/icons/svg/social-share-icons/doximity.svg
  styleguide/source/assets/scss/03-organisms/_social-share.scss
Labels: ready for review

#1542 EWL-0: Remove defunct event listing components from styleguide.
  styleguide/source/_patterns/03-organisms/event-list.json
  styleguide/source/_patterns/03-organisms/event-list.md
  styleguide/source/_patterns/03-organisms/event-list.twig
  styleguide/source/_patterns/03-organisms/page-content-tabs.json
  styleguide/source/_patterns/03-organisms/page-content-tabs.md
  styleguide/source/_patterns/03-organisms/page-content-tabs.twig
  styleguide/source/_patterns/05-pages/event-listing.json
  styleguide/source/_patterns/05-pages/event-listing.twig
  styleguide/source/_patterns/05-pages/event.json
  styleguide/source/_patterns/05-pages/event.md
  styleguide/source/_patterns/05-pages/event.twig
Labels: ready for review
