Repository AmericanMedicalAssociation/ama-style-guide-2, pull requests merged in 2024-01, with the labels that each got.

#1553 EWL-10560: Adds checkmark list stlying to wysiwyg for gating.
  styleguide/source/assets/images/check_mark_icon.svg
  styleguide/source/assets/scss/00-base/__01.mixins/_ama-button.scss
  styleguide/source/assets/scss/01-atoms/_dr-finder-badge.scss
  styleguide/source/assets/scss/01-atoms/_unordered-list.scss
  styleguide/source/assets/scss/02-molecules/_dr-finder-filter-list.scss
  styleguide/source/assets/scss/02-molecules/_dr-finder-profile-header.scss
  styleguide/source/assets/scss/02-molecules/_dr-finder-search-results-header.scss
  styleguide/source/assets/scss/02-molecules/_dr-finder-search-suggestions.scss
  styleguide/source/assets/scss/02-molecules/_dr_finder-filter-buttons.scss
Labels: ready for review

#1555 EWL-10557: Gated Teaser Styling
  styleguide/source/assets/scss/05-pages/_news.scss
Labels: in review

#1556 Feature/ewl 10597 custom block styling
  styleguide/source/assets/scss/00-base/_colors.scss
  styleguide/source/assets/scss/01-atoms/_unordered-list.scss
  styleguide/source/assets/scss/03-organisms/_gating-block.scss
Labels: ready for review, in review

#1557 EWL-10597: gating block styles.
  styleguide/source/assets/scss/03-organisms/_gating-block.scss
Labels: ready for review

#1548 EWL-0: Remove defunct and unnecessary atom patterns from styleguide.
  styleguide/source/_patterns/01-atoms/skip-nav.twig
  styleguide/source/_patterns/02-molecules/event-stub/event-stub~as-sticky.json
  styleguide/source/assets/scss/01-atoms/_skip-nav.scss
Labels: ready for review
