Repository AmericanMedicalAssociation/ama-style-guide-2, pull requests merged in 2025-05, with the labels that each got.

#1938 EWL-11375: Promo lean custom block styling.
  styleguide/source/_patterns/01-atoms/media/icons/svg/social-share-icons/v1-icon-subscribe-white.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/social-share-icons/v1-icon-subscribed-filled.twig
  styleguide/source/assets/icons/svg/social-share-icons/v1-icon-subscribe-white.svg
  styleguide/source/assets/icons/svg/social-share-icons/v1-icon-subscribed-filled.svg
  styleguide/source/assets/scss/00-base/_colors.scss
  styleguide/source/assets/scss/02-molecules/_article-stub.scss
  styleguide/source/assets/scss/02-molecules/_dr-finder-sign-in-dropdown.scss
  styleguide/source/assets/scss/02-molecules/_global-search.scss
  styleguide/source/assets/scss/02-molecules/_partner.scss
  styleguide/source/assets/scss/02-molecules/_sign-in-dropdown.scss
  styleguide/source/assets/scss/03-organisms/_main-navigation.scss
  styleguide/source/assets/scss/03-organisms/_personalized-account-hub.scss
Labels: priority, ready for review, has D8 dependency

#1939 DCP-212: Update Physician Page Boilerplate Text
  styleguide/source/_patterns/02-molecules/dr-finder-profile-header/dr-finder-profile-header.twig
Labels: ready for review, AMA Find A Doctor

#1943 EWL-11343: add numbers to listicle h3s.
  styleguide/source/assets/scss/01-atoms/_listicle.scss
Labels: priority, ready for review

#1948 EWL-11454: Hamburger menu keyboard accessibility
  styleguide/source/assets/js/main-navigation.js
  styleguide/source/assets/scss/01-atoms/_menu-icon.scss
  styleguide/source/assets/scss/03-organisms/_main-navigation.scss
Labels: priority, ready for review, in review
