Repository AmericanMedicalAssociation/ama-style-guide-2, pull requests merged in 2025-02, with the labels that each got.

#1851 DCP-230: Override Current AMA One SG Changes
  styleguide/source/assets/scss/00-base/_typography.scss
Labels: has dependency!, AMA Find A Doctor

#1855 EWL-11228: Add secondary CTA to homepage hero.
  styleguide/source/assets/scss/02-molecules/_full_hero_banner.scss
Labels: priority, ready for review

#1859 EWL-11238: update text and spacing styles.
  styleguide/source/assets/js/stub-list-height.js
  styleguide/source/assets/scss/02-molecules/_article-stub.scss
Labels: ready for review

#1858 EWL-11302: Fix article focus states.
  styleguide/source/assets/scss/02-molecules/_inline-bio.scss
  styleguide/source/assets/scss/05-pages/_news.scss
Labels: ready for review

#1856 EWL-11240: article action bar
  styleguide/source/assets/icons/svg/social-share-icons/v1-icon-copy-not-selected.svg
  styleguide/source/assets/icons/svg/social-share-icons/v1-icon-copy-selected.svg
  styleguide/source/assets/icons/svg/social-share-icons/v1-icon-print-not-selected.svg
  styleguide/source/assets/icons/svg/social-share-icons/v1-icon-print-selected.svg
  styleguide/source/assets/icons/svg/social-share-icons/v1-icon-save-not-selected.svg
  styleguide/source/assets/icons/svg/social-share-icons/v1-icon-save-selected.svg
  styleguide/source/assets/icons/svg/social-share-icons/v1-icon-share-doximity.svg
  styleguide/source/assets/icons/svg/social-share-icons/v1-icon-share-email.svg
  styleguide/source/assets/icons/svg/social-share-icons/v1-icon-share-facebook.svg
  styleguide/source/assets/icons/svg/social-share-icons/v1-icon-share-linkedin.svg
  styleguide/source/assets/icons/svg/social-share-icons/v1-icon-share-not-selected.svg
  styleguide/source/assets/icons/svg/social-share-icons/v1-icon-share-selected.svg
  styleguide/source/assets/icons/svg/social-share-icons/v1-icon-share-twitter.svg
  styleguide/source/assets/scss/00-base/__01.mixins/_ama-button-base.scss
  styleguide/source/assets/scss/00-base/__01.mixins/_ama-button.scss
  styleguide/source/assets/scss/01-atoms/_button.scss
  styleguide/source/assets/scss/03-organisms/_social-share-footer.scss
  styleguide/source/assets/scss/03-organisms/_social-share.scss
  styleguide/source/assets/scss/05-pages/_news.scss
Labels: priority, ready for review

#1862 EWL-11240: Feedback and new icon
  styleguide/source/assets/icons/svg/social-share-icons/v1-icon-share-doximity.svg
  styleguide/source/assets/scss/00-base/__01.mixins/_ama-button.scss
  styleguide/source/assets/scss/03-organisms/_social-share.scss
Labels: priority, question

#1861 EWL-11302: Update article category focus state and styling.
  styleguide/source/assets/scss/02-molecules/_inline-bio.scss
  styleguide/source/assets/scss/05-pages/_news.scss
Labels: ready for review, in review

#1865 EWL-11240: Update Share Bar Height and Scroll Margins
  styleguide/source/assets/scss/03-organisms/_social-share.scss
  styleguide/source/assets/scss/05-pages/_news.scss
Labels: priority, ready for review, in review

#1866 EWL-11304: Action Bar Subscribe
  styleguide/source/assets/icons/svg/social-share-icons/v1-icon-subscribe.svg
  styleguide/source/assets/icons/svg/social-share-icons/v1-icon-subscribed.svg
  styleguide/source/assets/scss/00-base/__01.mixins/_ama-button-base.scss
  styleguide/source/assets/scss/00-base/__01.mixins/_ama-button.scss
  styleguide/source/assets/scss/03-organisms/_series-subscribe.scss
  styleguide/source/assets/scss/03-organisms/_social-share.scss
  styleguide/source/assets/scss/05-pages/_news.scss
Labels: priority, ready for review

#1867 EWL-11304: Ticket Feedback
  styleguide/source/assets/scss/03-organisms/_series-subscribe.scss
Labels: priority, ready for review

#1868 EWL-11228: Update secondary cta styling for homepage hero.
  styleguide/source/assets/scss/02-molecules/_full_hero_banner.scss
Labels: priority, ready for review, in review

#1871 EWL-11304: Fixes the focus state for the subscribe button
  styleguide/source/assets/scss/03-organisms/_series-subscribe.scss
Labels: priority, ready for review

#1874 EWL-11347: Subscription Paragraph & EWL-11346: Unexpected Text Transform
  styleguide/source/assets/scss/02-molecules/_article-stub.scss
Labels: priority, ready for review

#1879 EWL-11321: Styling for homepage hero subtitle field.
  styleguide/source/assets/scss/02-molecules/_full_hero_banner.scss
Labels: priority, ready for review
