Repository AmericanMedicalAssociation/ama-style-guide-2, pull requests merged in 2025-03, with the labels that each got.

#1864 EWL-10969: Clear main nav search input after running a search.
  styleguide/source/assets/js/main-navigation.js
Labels: priority, ok to merge

#1880 EWL-11353: 50 50 form styling.
  styleguide/source/assets/js/form-items.js
  styleguide/source/assets/scss/02-molecules/hub/_hub-form.scss
  styleguide/source/assets/scss/03-organisms/_form-50-50.scss
Labels: priority, ready for review

#1882 EWL-11294: Add secondary cta to event header.
  styleguide/source/assets/scss/05-pages/_news.scss
Labels: priority, ready for review, in review

#1875 EWL-11225: Adjust anchor link script to fix external anchor links not…
  styleguide/source/assets/js/anchor_links.js
Labels: priority, question, ready for review

#1881 EWL-11206: Update inline promo styling.
  styleguide/source/assets/scss/02-molecules/_promo.scss
Labels: priority, ready for review, in review

#1884 EWL-10969: Show search suggestions block on all pages.
  styleguide/source/assets/js/search-suggestions.js
Labels: priority, ready for review, in review

#1885 EWL-11361: Underline and HTML entities
  styleguide/source/assets/scss/02-molecules/_article-stub.scss
Labels: priority, ready for review, in review

#1886 EW:-11294: Update mobile button styling for event cta's
  styleguide/source/assets/scss/05-pages/_news.scss
Labels: priority, ready for review, in review

#1891 EWL-11206: inline promo redesign
  styleguide/source/assets/js/listicle.js
  styleguide/source/assets/scss/02-molecules/_promo.scss
Labels: priority

#1893 EWL-11306: Redesign main header
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-chevron.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-search-purple.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-usermenu-outline-purple.twig
  styleguide/source/assets/icons/svg/icon-chevron.svg
  styleguide/source/assets/icons/svg/icon-search-purple.svg
  styleguide/source/assets/icons/svg/icon-usermenu-outline-purple.svg
  styleguide/source/assets/scss/01-atoms/_icons.scss
  styleguide/source/assets/scss/01-atoms/_menu-icon.scss
  styleguide/source/assets/scss/01-atoms/_site_logo.scss
  styleguide/source/assets/scss/02-molecules/_global-search.scss
  styleguide/source/assets/scss/02-molecules/_search-suggestions.scss
  styleguide/source/assets/scss/02-molecules/_sign-in-dropdown.scss
  styleguide/source/assets/scss/03-organisms/_category-navigation-menu.scss
  styleguide/source/assets/scss/03-organisms/_main-navigation.scss
Labels: priority, ready for review

#1896 bugfix/smartmenus issues
  styleguide/source/assets/js/category-menu.js
  styleguide/source/assets/js/vendor/jquery.smartmenus.js
  styleguide/source/assets/js/vendor/jquery.smartmenus.min.js
Labels: priority, ready for review, in review

#1897 Update product nav styling
  styleguide/source/assets/scss/02-molecules/_global-search.scss
  styleguide/source/assets/scss/03-organisms/_product-nav.scss
Labels: priority, ready for review

#1898 EWL-11306: Fix product nav styling for header redesign.
  styleguide/source/assets/scss/03-organisms/_product-nav.scss
Labels: priority, ready for review

#1869 EWL-11182: Remove uppercase stying from category headings.
  styleguide/source/assets/scss/05-pages/_category.scss
Labels: priority, ready for review

#1899 EWL-11387: Update partner block on article styling.
  styleguide/source/assets/scss/02-molecules/_partner.scss
Labels: priority, ready for review, in review

#1857 EWL-11284: Update event heading date and location styling
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-event-calendar.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-event-location.twig
  styleguide/source/assets/icons/svg/icon-event-calendar.svg
  styleguide/source/assets/icons/svg/icon-event-location.svg
  styleguide/source/assets/scss/05-pages/_news.scss
Labels: priority, ready for review, in review

#1901 EWL-11292: Update Promo as Inline block CTA Focus States
  styleguide/source/assets/scss/02-molecules/_promo.scss
Labels: priority, ready for review

#1870 EWL-11181: Remove bottom border from category/org nav.
  styleguide/source/assets/scss/05-pages/_homepage.scss
Labels: priority, ready for review

#1889 EWL-11126: Adjust spacing on forum author listing.
  styleguide/source/assets/scss/02-molecules/_forum-listing.scss
Labels: priority, ready for review

#1903 EWL-10980: forum sort block styling.
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-drop-arrow-down-black.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/twistie-down-blue.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/twistie-up-blue.twig
  styleguide/source/assets/icons/svg/icon-drop-arrow-down-black.svg
  styleguide/source/assets/icons/svg/twistie-down-blue.svg
  styleguide/source/assets/icons/svg/twistie-up-blue.svg
  styleguide/source/assets/scss/02-molecules/_forum-listing.scss
  styleguide/source/assets/scss/02-molecules/_forum_sort.scss
Labels: priority, ready for review

#1904 EWL-11306: Header Design Feedback
  styleguide/source/assets/scss/02-molecules/_global-search.scss
  styleguide/source/assets/scss/02-molecules/_sign-in-dropdown.scss
  styleguide/source/assets/scss/03-organisms/_main-navigation.scss
Labels: priority, ready for review

#1905 EWL-11306: Header Mobile Search
  styleguide/source/assets/js/main-navigation.js
Labels: priority, ready for review

#1909 EWL-11387: Feedback
  styleguide/source/assets/scss/02-molecules/_partner.scss
Labels: priority, ready for review

#1906 EWL-11284: Fix Event Location Text Alignment
  styleguide/source/assets/scss/05-pages/_news.scss
Labels: priority, ready for review

#1912 EWL-11306: Header Update
  styleguide/source/assets/scss/02-molecules/_global-search.scss
  styleguide/source/assets/scss/03-organisms/_main-navigation.scss
Labels: priority, ready for review
