Repository AmericanMedicalAssociation/ama-style-guide-2, pull requests merged in 2025-04, with the labels that each got.

#1918 EWL-11306: hide block before padding overflow
  styleguide/source/assets/js/search-suggestions.js
  styleguide/source/assets/scss/02-molecules/_search-suggestions.scss
Labels: priority, ready for review

#1920 EWL-11264: Update article inline hyperlink styles.
  styleguide/source/assets/scss/05-pages/_news.scss
Labels: priority, ready for review

#1922 EWL-11043: Update subcat pill button markup
  styleguide/source/assets/scss/03-organisms/_subcategory-exploration.scss
Labels: priority, ready for review

#1914 EWL-11399: Homepage and 3070 buttons
  styleguide/source/assets/scss/01-atoms/_button.scss
  styleguide/source/assets/scss/02-molecules/_full_hero_banner.scss
  styleguide/source/assets/scss/02-molecules/_thirty-seventy-block.scss
  styleguide/source/assets/scss/03-organisms/_footer.scss
  styleguide/source/assets/scss/03-organisms/_form-50-50.scss
Labels: priority, ready for review

#1860 EWL-11224: Add blank card option to article stub list
  styleguide/source/assets/scss/02-molecules/_article-stub.scss
Labels: priority

#1925 EWL-11409: Adjust anchor link script to fix external anchor link func…
  styleguide/source/assets/js/anchor_links.js
Labels: priority, ready for review, in review

#1927 EWL-11414: Change Forum Blockquote Background Color
  styleguide/source/assets/scss/02-molecules/_block-quote.scss
Labels: priority, ready for review

#1917 Feature/layout builder improvements
  styleguide/source/assets/images/layout-builder-block-examples/30-70-block-right.png
  styleguide/source/assets/images/layout-builder-block-examples/30-70.png
  styleguide/source/assets/images/layout-builder-block-examples/article-stub-list.png
  styleguide/source/assets/images/layout-builder-block-examples/featured-content-1.png
  styleguide/source/assets/images/layout-builder-block-examples/featured-content-3.png
  styleguide/source/assets/images/layout-builder-block-examples/featured-content-7.png
  styleguide/source/assets/images/layout-builder-block-examples/membership-right-rail.png
  styleguide/source/assets/images/layout-builder-block-examples/membership-slim-subcat.png
  styleguide/source/assets/images/layout-builder-block-examples/membership.png
  styleguide/source/assets/images/layout-builder-block-examples/page-grouping-subcat-view-mode.png
  styleguide/source/assets/images/layout-builder-block-examples/partner-promo-right-rail.png
  styleguide/source/assets/images/layout-builder-block-examples/subscribe-promo-right-rail.png
  styleguide/source/assets/images/layout-builder-block-examples/theme-2.png
  styleguide/source/assets/images/layout-builder-block-examples/theme-3.png
  styleguide/source/assets/images/layout-builder-block-examples/theme-4.png
  styleguide/source/assets/images/layout-builder-block-examples/tools-list.png
  styleguide/source/assets/images/layout-builder-block-examples/video-left-right.png
  styleguide/source/assets/images/layout-builder-block-examples/video.png
  styleguide/source/assets/js/form-items.js
  styleguide/source/assets/scss/02-molecules/_expand-list.scss
  styleguide/source/assets/scss/02-molecules/_layout-builder.scss
  styleguide/source/assets/scss/03-organisms/_filter.scss
  styleguide/source/assets/scss/03-organisms/_org-nav.scss
Labels: priority, ready for review, Approve but DON'T MERGE

#1931 EWL-11399: Adjust button component styling for homepage hero and 30-7…
  styleguide/source/assets/scss/02-molecules/_thirty-seventy-block.scss
Labels: priority, ready for review

#1932 EWL-11401: Inline promo button styling fix
  styleguide/source/assets/scss/02-molecules/_promo.scss
Labels: priority, ready for review

#1934 EWL-11401: Article inline promo and form 50/50 mobile style fix
  styleguide/source/assets/scss/02-molecules/_promo.scss
  styleguide/source/assets/scss/03-organisms/_form-50-50.scss
Labels: priority, ready for review

#1935 EWL-11319: Remove Bold Style From Find A Doctor Footer Link
  styleguide/source/assets/scss/03-organisms/_footer.scss
Labels: priority, ready for review, AMA Find A Doctor

#1933 EWL-11400: Event header button component styling
  styleguide/source/assets/scss/05-pages/_news.scss
Labels: ready for review

#1936 DCP-230: Restore Kepler STD Font On Body Copy
  styleguide/source/assets/scss/00-base/_typography.scss
Labels: AMA Find A Doctor
