Repository AmericanMedicalAssociation/ama-style-guide-2, pull requests merged in 2025-01, with the labels that each got.

#1840 EWL-11095: don't scroll when accordions are opened on desktop.
  styleguide/source/assets/js/anchor_links.js
Labels: priority

#1841 EWL-11205: Article Header Update
  styleguide/source/assets/scss/02-molecules/_inline-bio.scss
  styleguide/source/assets/scss/05-pages/_news.scss
Labels: priority, in review

#1839 EWL-11219: Hub Card Button Styling Updates
  styleguide/source/assets/scss/02-molecules/hub/_hub-card.scss
Labels: priority, ready for review

#1843 EWL-11151: Footer CTAs not displaying correctly
  styleguide/source/assets/scss/05-pages/_hub-page.scss
Labels: priority, ready for review, in review

#1844 EWL-11122: Forum Covers Search Suggestions
  styleguide/source/assets/scss/02-molecules/_search-suggestions.scss
Labels: priority, ready for review, in review

#1845 EWL-10951: Listicle Line wrap issue
  styleguide/source/assets/scss/01-atoms/_listicle.scss
Labels: priority, ready for review, in review

#1848 EWL-11205: News Header Feedback
  styleguide/source/assets/scss/01-atoms/_date-block.scss
  styleguide/source/assets/scss/02-molecules/_inline-bio.scss
  styleguide/source/assets/scss/05-pages/_news.scss
Labels: priority, ready for review

#1849 EWL-11205 and EWL-11122: Feedback
  styleguide/source/assets/scss/02-molecules/_global-search.scss
  styleguide/source/assets/scss/03-organisms/_main-navigation.scss
  styleguide/source/assets/scss/05-pages/_news.scss
Labels: priority, ready for review, in review

#1852 EWL-11205: Remove margin on twitter icon
  styleguide/source/assets/scss/02-molecules/_inline-bio.scss
Labels: ready for review

#1846 EWL-11238: card styles.
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-headphones.twig
  styleguide/source/_patterns/01-atoms/media/icons/svg/icon-play-2.twig
  styleguide/source/assets/icons/svg/icon-headphones.svg
  styleguide/source/assets/icons/svg/icon-play-2.svg
  styleguide/source/assets/js/stub-list-height.js
  styleguide/source/assets/scss/02-molecules/_article-stub.scss
Labels: priority, ready for review
