Repository AmericanMedicalAssociation/ama-style-guide-2, pull requests merged in 2025-09, with the labels that each got.

#2019 EWL-11604: adjust block breakpoint to stack on medium.
  styleguide/source/assets/scss/03-organisms/_form-50-50.scss
Labels: priority, ready for review

#2018 EWL-11642: Social Share | Add Bluesky Icon and Styling
  styleguide/source/assets/icons/svg/social-share-icons/bluesky.svg
  styleguide/source/assets/scss/03-organisms/_social-share-footer.scss
  styleguide/source/assets/scss/03-organisms/_social-share.scss
Labels: priority, ready for review, in review, has D8 dependency

#2023 EWL-11635: update block padding.
  styleguide/source/assets/scss/02-molecules/_full_hero_banner.scss
Labels: priority, ready for review, in review

#2022 EWL-11593: Update mobile sign in menu with keyboard navigation
  styleguide/source/assets/js/sign-in-dropdown.js
Labels: priority, ready for review, in review, has D8 dependency

#2025 EWL-11617: Four Up Lists | Section Subtitle Styling
  styleguide/source/assets/scss/03-organisms/_four-up-lists.scss
Labels: priority, ready for review, in review, has D8 dependency
